### ISSUE TITLE
BUG: An error may occur during model training unless the “Whether the model has pitch guidance” checkbox is checked, regardless of the previously selected pitch algorithm.

### ISSUE THREAD

**Issue by crichu894** [IAHispano/Applio#168]
## Environment
- OS: Windows 11 23H2 (build 22631.2861)
- Python Version: 3.9.8.
- Hardware: NVIDIA GeForce RTX 40 Series.

## Issue Description:
-
Just like there are models trained for singing, there are also models specifically trained for speech. However, if you intend to train a model solely for speech, you may encounter errors when you uncheck the “Whether the model has pitch guidance” checkbox. These errors can include:
INFO:jude:Loaded pretrained assets/pretrained_v2/f0G40k.pth
Process Process-1:
Traceback (most recent call last):
  File "E:\Applio-RVC-Fork\lib\modules\train\train.py", line 280, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "E:\Applio-RVC-Fork\lib\modules\train\utils.py", line 212, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "E:\Applio-RVC-Fork\lib\modules\train\train.py", line 318, in run
    net_g.module.load_state_dict(
  File "E:\Applio-RVC-Fork\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid_nono:
        Unexpected key(s) in state_dict: "enc_p.emb_pitch.weight", "dec.m_source.l_linear.weight", "dec.m_source.l_linear.bias", "dec.noise_convs.0.weight", "dec.noise_convs.0.bias", "dec.noise_convs.1.weight", "dec.noise_convs.1.bias", "dec.noise_convs.2.weight", "dec.noise_convs.2.bias", "dec.noise_convs.3.weight", "dec.noise_convs.3.bias".

## Attempted solutions
-
1. In the latest available version of Applio, I conducted tests with different pitch algorithms (rmvpe / rmvpe_gpu) to determine if the issue occurred with multiple algorithms or just one. After unchecking the "Whether the model has pitch guidance" checkbox, I observed that the error occurred with both algorithms.
2. I utilized the RVC (https://github.com/rVC-Project/Retrieval-based-Voice-Conversion-WebUI) to test the pitch algorithms (rmvpe / rmvpe_gpu). Then, I selected the "false" option  "Whether the model has pitch guidance" (required for singing, optional for speech).
As a result, I can confirm that the model has been trained successfully.

**Comment by Qualzz** [comment]
I confirm 
Here is where the error came from when unchecking model guidance

```
def latest_checkpoint_path(dir_path, regex="G_*.pth"):
    f_list = glob.glob(os.path.join(dir_path, regex))
    f_list.sort(key=lambda f: int("".join(filter(str.isdigit, f))))
    x = f_list[-1]
    logger.debug(x)
    return x
```
