### ISSUE TITLE
have been struggling with this ModuleNotFoundError: No module named 'lib.globals'

### ISSUE THREAD

**Issue by samlyn696** [IAHispano/Applio#181]
## Environment
- OS: windows 11
- Python Version: 3.9
- Hardware: trust me very powerfull

## Issue Description:
infer-web.py", line 14, in <module>
    import lib.globals.globals as rvc_globals
ModuleNotFoundError: No module named 'lib.globals'

## Attempted solutions
everything i tried for python 3.9 never worked     
any help would be appreciated

**Comment by aitronssesin** [comment]
Check this https://docs.applio.org/faq/installation-method/conda/tensorboard-dependency/

**Comment by samlyn696** [comment]
actually it was strange as i tried everything even within the code itself but none solve the problem
then solution came to create __init__.py file in lib folder and problem solved
