### ISSUE TITLE
BUG: Trained voice is different than anticipated

### ISSUE THREAD

**Issue by shalevc1098** [IAHispano/Applio#186]
## Environment
- OS: Windows 11
- Python Version: 3.10.11

## Issue Description:
- Hello, I've trained a model of the singer Eyal Golan but got an entirely different voice of someone I never heard. Why is that? What did I do wrong? Thanks for helping! Used **rmvpe_gpu**.

**Comment by shalevc1098** [comment]
> Use the conversor in the Extra -> Processing section, or download the latest version

Why do I need to use it? I don't want to merge/process the models

**Comment by shalevc1098** [comment]
> The last option. ![image](https://private-user-images.githubusercontent.com/133521603/294946047-71d412ca-b7b1-4d76-961c-7cbd4137b850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjcwNTAsIm5iZiI6MTcwNDcyNjc1MCwicGF0aCI6Ii8xMzM1MjE2MDMvMjk0OTQ2MDQ3LTcxZDQxMmNhLWI3YjEtNGQ3Ni05NjFjLTdjYmQ0MTM3Yjg1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTEyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODE4MmE1ZjQ4MGIzNzNhNzQ4ZjIzN2JiZWFkMjcyNDA3ZDRlNDkzMTNiMWNmYTRjNTJlNGFkMWI1ZjY2NjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KCLcZUtxkye6mN08SeR4W_6dZpdc0R2OOeyjAU8bPHY)

What does it do and how would it help?

**Comment by shalevc1098** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/51709332/2826c7af-20f5-4fa9-8f41-e8c85215ec8c)
Btw is this a good sign? It trains so fast but I don't know if it should do that

**Comment by AG89** [comment]
I also have the same issue, and processing the model did not fix anything.

**Comment by aitronssesin** [comment]
> ## Environment
> * OS: Windows 11
> * Python Version: 3.10.11
> 
> ## Issue Description:
> * Hello, I've trained a model of the singer Eyal Golan but got an entirely different voice of someone I never heard. Why is that? What did I do wrong? Thanks for helping! Used **rmvpe_gpu**.

If you used **rmvpe_gpu** we have to tell you that is officialy broken https://github.com/IAHispano/Applio/issues/171

**Comment by aitronssesin** [comment]
If you had more issues we are rn working in the V3 of applio so the support of this version isn't our priority
