### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lancealotlink** [IAHispano/Applio#191]
**Describe the bug**
Wont start after executing run-applio.bat

Traceback (most recent call last):
  File "c:\Users\DSEPC\Desktop\Applio-3.0.0\app.py", line 8, in <module>
    from tabs.inference.inference import inference_tab
  File "c:\Users\DSEPC\Desktop\Applio-3.0.0\tabs\inference\inference.py", line 8, in <module>
    from core import (
  File "c:\Users\DSEPC\Desktop\Applio-3.0.0\core.py", line 6, in <module>
    from rvc.lib.tools.validators import (
ModuleNotFoundError: No module named 'rvc.lib'

**Comment by centrdev** [comment]
hey, im getting the same error trying to run the run-applio.bat

**Comment by bygimenez** [comment]
We are working on this, please wait a moment and update.

**Comment by aitronssesin** [comment]
We fixed finally fixed the issue, there was a mising folder when oding the update please download again the source zip

**Comment by Qualzz** [comment]
thank you for the quick update !

**Comment by aitronssesin** [comment]
Yep the installer downloads the files in the Applio folder so when you e download the zip you need to run the installer again
