### ISSUE TITLE
[BUG] Missing logs folder

### ISSUE THREAD

**Issue by Qualzz** [IAHispano/Applio#193]
After installing 3.0.1 and using "run-applio.bat'

`FileNotFoundError: 'path\\rvc\\logs'`

Full message:
```
Traceback (most recent call last):
  File "redacted\rvc\app.py", line 35, in <module>
    inference_tab()
  File "redacted\rvc\tabs\inference\inference.py", line 206, in inference_tab
    best_default_index_path = match_index(model_file.value)
  File "redacted\rvc\tabs\inference\inference.py", line 132, in match_index
    for filename in os.listdir(directory):
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'redacted\\rvc\\logs'
```

Manually creating the folder is enough to get the localhost server running.

**Comment by blaise-tk** [comment]
Install it again

**Comment by Qualzz** [comment]
Do I really need to install it if creating the folder manually was enough ? 
You can close this issue if the GitHub release already fixed it. The issue happened with `3.0.1`

**Comment by Keiser04** [comment]
> Do I really need to install it if creating the folder manually was enough ? You can close this issue if the GitHub release already fixed it. The issue happened with the hotfix `3.0.1` release

i think if we do git pull will work anyway but yes, creating manualy is enough

**Comment by blaise-tk** [comment]
Solved.
