### ISSUE TITLE
[FEEDBACK] French Translation issues

### ISSUE THREAD

**Issue by Qualzz** [IAHispano/Applio#194]
Issue Description:
The French translations within the Applio software seem to be AI-generated and lack contextual accuracy. This leads to several instances where sentences are awkwardly structured or contain literal mistranslations, or using translation for words that we also use the English version, affecting the overall user experience for French-speaking users.

Specific Examples:

Misinterpretation of "**Single**": The word "Single" has been translated to "**célibataire**," which is a literal translation suited for _marital status_. However, in the context of Applio, "Single" refers to processing a single audio file as opposed to batch processing. A more contextually appropriate translation would be "Individuel" or "Fichier individuel".

Here is a fully better translated French version: 
[fr_FR.json](https://github.com/IAHispano/Applio/files/13995925/fr_FR.json)

One of the only one I have hard time to translate is "Search Feature Ratio", which I don't really get what does that mean even in English. 
I translated it to "**Rapport de Caractéristiques de Recherche**"

**Comment by bygimenez** [comment]
I recommend you to make a **pull request**.

**Comment by blaise-tk** [comment]
I don't know what you expected, that we would hire French proofreaders? Hahah. Open a PR and we will add your translation, thanks for improving it.

**Comment by Qualzz** [comment]
> I don't know what you expected, that we would hire French proofreaders? Hahah. Open a PR and we will add your translation, thanks for improving it.

Ofc not lol, It was just to decorate the github issue instead of just saying "lol translation sucks pls improve" hehehehe

**Comment by blaise-tk** [comment]
❤️
