### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by Keiser04** [IAHispano/Applio#197]
**Describe the bug**

El error que se muestra en la imagen es un IndexError: list index out of range en Python. Este error indica que se intentó acceder a un índice fuera del rango de una lista. El error ocurrió en la línea 221 del archivo “infer.py”. 

En este caso, parece que el programa intentó acceder al elemento en el índice 10 de la lista sys.argv, pero ese índice no existe en la lista.

![imagen](https://github.com/IAHispano/Applio/assets/146493916/2a0a058f-a359-49cf-98fe-228c564f51d5)

**To Reproduce**
1. Ejecutar el webui
2. Ir a inferencia por lote e meter las ubicaciones
3. Darle a convertir
4. Sale el error

**Expected behavior**
Que se me inferan los audios en la carpeta especificada

**Assets**
![imagen](https://github.com/IAHispano/Applio/assets/146493916/fe7ce83c-348b-441e-90f8-837d8f9980bc)

**Desktop (please complete the following information):**
![imagen](https://github.com/IAHispano/Applio/assets/146493916/c989fc81-62fc-4855-a739-7f444ded91e9)

**Additional context**

**Comment by blaise-tk** [comment]
La carpeta debe contener solo audios.

**Comment by Keiser04** [comment]
> La carpeta debe contener solo audios.

ok vere

**Comment by Keiser04** [comment]
no habia otros archivos aparte de wav. pense que podria ser porque tenian txt en el nombre pero no parece ser asi

**Comment by Keiser04** [comment]
ah creo que puede ser porque en inferencia normal puedes hacer dividir audio pero en el otro no. ya que me dijste que solo la pasabas por la inferencia normal con un for puede deberse a ello ya que lo del split audio no se puede ni activar ni desactibvar en lote @blaise-tk

**Comment by Keiser04** [comment]
![imagen](https://github.com/IAHispano/Applio/assets/146493916/93c0b58f-347f-4e32-9ddf-805b35bca07d)
Con un try catch pa que no pete sirve si es que se supone que debe verse asi
![imagen](https://github.com/IAHispano/Applio/assets/146493916/438746bb-8906-4ef8-9f57-f333f591fc73)

**Comment by Keiser04** [comment]
asi que si era eso

**Comment by blaise-tk** [comment]
Okey, gracias por arreglarlo. ahora lo añadimos
