### ISSUE TITLE
[BUG] File not found

### ISSUE THREAD

**Issue by noborhys** [IAHispano/Applio#198]
Every time I open "run-applio.bat" I keep getting this issue and I have no idea why, I'm new to all this so I thought I'd ask for help.
![Screenshot (11)](https://github.com/IAHispano/Applio/assets/157185871/b5f4ccab-59d3-4b41-942b-d4c5e50aa0eb)

**Comment by blaise-tk** [comment]
Please show a screenshot of the AI folder inside the desktop

**Comment by noborhys** [comment]
![Screenshot (12)](https://github.com/IAHispano/Applio/assets/157185871/accdcdd6-2049-4810-8c26-2760f6a286ce)

**Comment by blaise-tk** [comment]
https://github.com/IAHispano/Applio/archive/refs/tags/3.0.1.zip

Download the .zip file, run [run-install.bat](https://github.com/IAHispano/Applio/blob/main/run-install.bat) and then [run-applio.bat](https://github.com/IAHispano/Applio/blob/main/run-applio.bat) - Make sure to install it on the main system drive (C), then you can have it wherever you want and do not run as administrator the bat file.

**Comment by noborhys** [comment]
Ahhh, for some reason my brain skipped over the "download the zip file" I'll do that now, I'll let you know if I have an issue with it.

**Comment by noborhys** [comment]
![Screenshot (13)](https://github.com/IAHispano/Applio/assets/157185871/2f50bb15-f277-4c4f-8de8-ff246b546c6e)
I now seem to have this issue

**Comment by aitronssesin** [comment]
Wait to the precompilled version with I'm just making it.

**Comment by deadniell** [comment]
> ![Screenshot (13)](https://private-user-images.githubusercontent.com/157185871/298244799-2f50bb15-f277-4c4f-8de8-ff246b546c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTUyMjksIm5iZiI6MTcwNTcxNDkyOSwicGF0aCI6Ii8xNTcxODU4NzEvMjk4MjQ0Nzk5LTJmNTBiYjE1LWYyNzctNGM0Zi04ZGU4LWZmMjQ2YjU0NmM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMTQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTc3MWUzYjkzY2E0ZjM1MTUxNGIzM2ZiYTljNmM2NjZlMTVmZGQ2YmE5N2U1ZDBmZDI2OWI5NTVkNDE3NmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KtmgIdRXjER79BFCtcFd0F3DG4-Yp2lkHO1MFzvGqNY) I now seem to have this issue

Same issue here xd

**Comment by noborhys** [comment]
> Wait to the precompilled version with I'm just making it.

Is there an ETA?

**Comment by noborhys** [comment]
> > ![Screenshot (13)](https://private-user-images.githubusercontent.com/157185871/298244799-2f50bb15-f277-4c4f-8de8-ff246b546c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTUyMjksIm5iZiI6MTcwNTcxNDkyOSwicGF0aCI6Ii8xNTcxODU4NzEvMjk4MjQ0Nzk5LTJmNTBiYjE1LWYyNzctNGM0Zi04ZGU4LWZmMjQ2YjU0NmM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMTQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTc3MWUzYjkzY2E0ZjM1MTUxNGIzM2ZiYTljNmM2NjZlMTVmZGQ2YmE5N2U1ZDBmZDI2OWI5NTVkNDE3NmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KtmgIdRXjER79BFCtcFd0F3DG4-Yp2lkHO1MFzvGqNY) I now seem to have this issue
> 
> Same issue here xd

Haha problem twins

**Comment by aitronssesin** [comment]
> > Wait to the precompilled version with I'm just making it.
> 
> Is there an ETA?

Aproximately 15 minutes or less if all is right

**Comment by noborhys** [comment]
Sounds great, Thanks for all the hard work!

**Comment by deadniell** [comment]
> > > ![Screenshot (13)](https://private-user-images.githubusercontent.com/157185871/298244799-2f50bb15-f277-4c4f-8de8-ff246b546c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTUyMjksIm5iZiI6MTcwNTcxNDkyOSwicGF0aCI6Ii8xNTcxODU4NzEvMjk4MjQ0Nzk5LTJmNTBiYjE1LWYyNzctNGM0Zi04ZGU4LWZmMjQ2YjU0NmM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMTQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTc3MWUzYjkzY2E0ZjM1MTUxNGIzM2ZiYTljNmM2NjZlMTVmZGQ2YmE5N2U1ZDBmZDI2OWI5NTVkNDE3NmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KtmgIdRXjER79BFCtcFd0F3DG4-Yp2lkHO1MFzvGqNY) I now seem to have this issue
> > 
> > 
> > Same issue here xd
> 
> Haha problem twins

any solution on this ???

**Comment by deadniell** [comment]
> > > > ![Screenshot (13)](https://private-user-images.githubusercontent.com/157185871/298244799-2f50bb15-f277-4c4f-8de8-ff246b546c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTUyMjksIm5iZiI6MTcwNTcxNDkyOSwicGF0aCI6Ii8xNTcxODU4NzEvMjk4MjQ0Nzk5LTJmNTBiYjE1LWYyNzctNGM0Zi04ZGU4LWZmMjQ2YjU0NmM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMTQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTc3MWUzYjkzY2E0ZjM1MTUxNGIzM2ZiYTljNmM2NjZlMTVmZGQ2YmE5N2U1ZDBmZDI2OWI5NTVkNDE3NmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KtmgIdRXjER79BFCtcFd0F3DG4-Yp2lkHO1MFzvGqNY) I now seem to have this issue
> > > 
> > > 
> > > Same issue here xd
> > 
> > 
> > Haha problem twins
> 
> any solution on this ???

I just reinstalled all over again. This time the run-install.bat installed more things included that pytorch. Then I ran the run-applio.bat and got no errors!

Solved, fixed 👍
