### ISSUE TITLE
[BUG]  Trying to run-applio.bat 

### ISSUE THREAD

**Issue by deadniell** [IAHispano/Applio#199]
After I ran the run-install.bat , when I try to run the run-applio.bat shows this error. 
Should I installed all of these in the main C root ??? 

![imagen_2024-01-19_203618018](https://github.com/IAHispano/Applio/assets/143788296/92ee4113-8966-471d-99a5-ee1d1749bc7a)

**Comment by aitronssesin** [comment]
https://github.com/IAHispano/Applio/issues/198
