### ISSUE TITLE
[BUG] Voice Model Selection

### ISSUE THREAD

**Issue by KillauraHacks** [IAHispano/Applio#201]
Not sure if this is a bug or intended why is both the D and G file in the model selection also can you make it so it also displays the checkpoint number in the name
![image](https://github.com/IAHispano/Applio/assets/29743840/9873f594-b3e9-4aa8-aa52-6355d551eb2a)

**Comment by KillauraHacks** [comment]
I realized now I can't inference with G or D "checkpoints" I dont think its saving the checkpoints correctly it only saves the final checkpoint correctly

**Comment by blaise-tk** [comment]
Fixed
