### ISSUE TITLE
[BUG] Applio doesn't save a pth of the trained model after hitting each save point

### ISSUE THREAD

**Issue by AG89** [IAHispano/Applio#203]
I've checked to see if there were any folders modified and the only ones that were were files in the logs folder of my model, but i see no pth at all after training for 400 epochs. it's supposed to go to 500 but i stopped it early as I didn't need that many. I have also checked the log for my model and it doesn't say anything about where the pth is saved. I have noticed that it has saved several of the G and D models. but none of the actual usable model. And It also resets my epoch count back to 1 if i try retraining it.

This is the settings I have set: 
![image](https://github.com/IAHispano/Applio/assets/22873716/a50777d2-c97b-4a8c-8d80-3f5c2f10ab81)

The log:
[train.log](https://github.com/IAHispano/Applio/files/13996783/train.log)

**Expected behavior**
Applio is supposed to at least save a pth of the model i have been training.

**Assets**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi

**Comment by blaise-tk** [comment]
Hi, we will investigate what you say, but the G and D file should be saved at each save point if you select the Save only latest option, and the final pth is generated at the end of the training.

**Comment by AG89** [comment]
The only issue with that is that in 2.0 it would also save a pth file, but it did not with this version.

**Comment by blaise-tk** [comment]
Should be fixed

**Comment by chopra-anuj** [comment]
I am also facing same issue. Is it not fixed yet?

**Comment by AG89** [comment]
AFAIK no. I don't think there has been any attempt to fix this issue at all
