### ISSUE TITLE
[BUG]Not compatible with python 3.11

### ISSUE THREAD

**Issue by zc402** [IAHispano/Applio#204]
**Describe the bug**
The run-install.sh says "Please install Python3 or 3.11 manually." However, using python 3.11 under linux results in an exception of fairseq: 

```
FaValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory. 
```

This issue is discussed here: https://github.com/facebookresearch/fairseq/issues/5012

I installed a custom version of fairseq to avoid this issue: 
`pip install git+https://github.com/One-sixth/fairseq.git`

Also, the range input component on the web page for "pitch" can be put on float numbers, which results in the following exception:
```
Voice conversion failed: invalid literal for int() with base 10: '8.7'
```

**To Reproduce**
conda create --name applio python=3.11
conda activate applio
./run-install.sh

**Comment by sonphantrung** [comment]
Well, the same can be said with most major AI tools: <=3.10 is supported.

**Comment by blaise-tk** [comment]
Added info to readme about this issue + pitch slider fixed. They are free to do PR to improve linux, I don't have linux.

**Comment by zc402** [comment]
> Well, the same can be said with most major AI tools: <=3.10 is supported.

You are right. Most of the time I use python=3.8, but since the installing script explicitly says 3.11. Anyway, I'm really appreciate for this tool that integrates the TTS and RVC pipeline together. The quality of voice generated is so much better than TTS only!
