### ISSUE TITLE
[BUG] FileExistsError when trying to preprocess an already preprocessed dataset

### ISSUE THREAD

**Issue by AlexeyArtemev** [IAHispano/Applio#206]
**Describe the bug**
During the training preps, if the dataset is already preprocessed, another preprocessing for the same model throws FileExistsError

**To Reproduce**
1. Start pretraining and wait it to finish
2. Try to start it again
3. See FileExistsError in the console

**Expected behavior**
One of the following:
- An alert in WebUI telling me that the folder already exists for me to choose what to do with it(like removing it myself or renaming the model);
- Using the existing dir while clearing the old preprocess results;

**Assets**
```
Traceback (most recent call last):
  File "C:\Users\rival\Downloads\Applio\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\rival\Downloads\Applio\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\rival\Downloads\Applio\env\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "C:\Users\rival\Downloads\Applio\env\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\rival\Downloads\Applio\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\rival\Downloads\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\Users\rival\Downloads\Applio\env\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\rival\Downloads\Applio\env\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\rival\Downloads\Applio\core.py", line 172, in run_preprocess_script
    os.mkdir(os.path.join(logs_path, str(model_name)))
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:\\Users\\rival\\Downloads\\Applio\\logs\\repetur'
```

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Applio commit: 3e3852bc623f3c67d528cd597b6e32cd60edc65d (HEAD -> main, tag: 3.0.2, origin/main, origin/HEAD), latest at the moment of opening the issue

**Comment by blaise-tk** [comment]
check if this path exists `C:\\Users\\rival\\Downloads\\Applio\\logs\\repetur`

**Comment by AlexeyArtemev** [comment]
> check if this path exists

It exists

**Comment by AlexeyArtemev** [comment]
> Delete the folder and do it again

I'm sorry, maybe i explained something wrong in the op. The thing is i want the app to delete it for me if it already exists or use it for the updated dataset(like how i explained in **Expected behavior** section)

**Comment by blaise-tk** [comment]
So it's not a bug, it's that you want the program to have one more feature.

**Comment by AlexeyArtemev** [comment]
> So it's not a bug

it's an error while using a process that was implemented in any other RVC implementation. Even Applio V2 has this functionality(i.e. i won't get an error doing the steps described in **To Reproduce** section of op post), and i just don't have any clue why you've not implemented the industry-wide practice and now presenting it here as "one more feature". So for me(and anyone who will expect the app to remove the dir) it's an error. Maybe not a bug, but definitely something that has to be fixed

**Comment by AlexeyArtemev** [comment]
@blaise-tk as i can see in `infer-web.py`, `def preprocess_dataset`, line 807:

```os.makedirs("%s/logs/%s" % (now_dir, exp_dir), exist_ok=True)```

if `exist_ok` does what i think it does(which is allowing the dir creation even if it exists) then i think it's a bug

**Comment by blaise-tk** [comment]
Fixed.
