### ISSUE TITLE
[BUG] No carga modelos preentrenados para el entrenamiento

### ISSUE THREAD

**Issue by monotoab97** [IAHispano/Applio#208]
Antes de nada, escribo en español ya que sois devs hispanos, pero si necesitáis que lo vuelva a redactar en inglés todo sin problema lo hago 👍

## Problema
A la hora de entrenar, tanto el preprocesamiento como la extracción de características no dan ningún tipo de error.
El problema es que al darle a entrenar no veo que cargue la información del modelo preentrenado por defecto. En la consola desde el CMD no aparece nada.
Me he dado cuenta ya que en la otra versión de Applio cuando dejaba la ruta por defecto del modelo preentrenado vacía, avisaba de que no se había cargado ningún modelo preentrenado y además los valores de loss_mel salían bastante altos para lo que debería ser (>50)
Adjunto una imagen en la que se ve como en ningún lado aparece que se han cargado los modelos preentrenados
![image](https://github.com/IAHispano/Applio/assets/106434946/f11da8d5-28ab-4a2a-a77d-bcb03fc1fe14)

## Reproducción del problema
![image](https://github.com/IAHispano/Applio/assets/106434946/499e45d4-158d-4a9b-9823-2128e19df760)
![image](https://github.com/IAHispano/Applio/assets/106434946/c6bab20b-313e-4c2a-872c-39cbce167083)

Lo único que he hecho ha sido darle a los 3 botones de procesar > extraer > entrenar
He probado tanto marcar en otra prueba los 32000, como los 40000 en esta última prueba que envío aquí
Ya se que son pocos epochs, pero son suficientes como para que al menos la inferencia con el modelo suene humana. Adjunto también un audio con la inferencia del modelo de 20 epochs (suena igual que cuando borraba la ruta del modelo preentrenado en la otra versión de applio, por eso supongo que no está cargando los pretrained)

## Resultado de la inferencia
http://sndup.net/xj2w

 - OS: Windows 11
 - Chrome

**Comment by blaise-tk** [comment]
Si los carga, solo que no hace el log.

**Comment by monotoab97** [comment]
pero es que esa inferencia suena a que no ha cargado el modelo preentrenado, por eso he abierto el ticket

**Comment by blaise-tk** [comment]
Ya hemos dicho que el entrenamiento no está funcionando bien, lo estamos investigando.
