### ISSUE TITLE
Trojan detected in v3.0.2

### ISSUE THREAD

**Issue by joneschunghk** [IAHispano/Applio#211]
When I unzip source.zip, it was blocked by Kaspersky. It detected a Trojan named "HEUR:Trojan.BAT.Agent.gen". But no problem was found in v3.0.1

[HEUR:Trojan.BAT.Agent.gen](https://threats.kaspersky.com/en/threat/HEUR:Trojan.BAT.Agent.gen/?function=search&VN=HEUR:Trojan.BAT.Agent.gen)

**Comment by blaise-tk** [comment]
That is because the .bat downloads files from online, you have the code to see it.

**Comment by superiorenby** [comment]
("HEUR") Heuristic analyses detect passed on behavior patterns (roughly)
VirusTotal results.
https://www.virustotal.com/gui/file/f6286d27c3595d8ef94ee700b1ebec7919642f393ea6b6da284225d1446fbb32/detection

Indicators based on general behavior.
https://www.hybrid-analysis.com/sample/3a5660e111b27ca208c599cf6422247f539985cbb9d27e88502aefc7f3133a91/65b37c643ee09ec62a0dbe84

But behavior testing on systems finds no real threats.
https://www.virustotal.com/gui/file/f6286d27c3595d8ef94ee700b1ebec7919642f393ea6b6da284225d1446fbb32/behavior

The run bat is also undetected.
https://www.hybrid-analysis.com/sample/9bd5b39ffb74aca014831855cd70d4f98a6afbca654f64783624ba031f1c710b
https://www.virustotal.com/gui/file/9bd5b39ffb74aca014831855cd70d4f98a6afbca654f64783624ba031f1c710b

And I have personally installed this version with no issues.
