### ISSUE TITLE
[REQUEST] Overtraining feature and Percentage of progress

### ISSUE THREAD

**Issue by rappc87** [IAHispano/Applio#217]
Can we add the Overtraining feature in v3? If there is no improvement while training, it will stop automatically.And while train, can it appear as a percentage instead of a waiting animation in the interface? For example, if the total epoch is 500 and the current epoch is 132, 132/500 = 0,264 (26,4%).

**Comment by blaise-tk** [comment]
We will consider your idea for future updates.
