### ISSUE TITLE
[BUG]Doesn't support AMD video cards?

### ISSUE THREAD

**Issue by Witwike** [IAHispano/Applio#218]
![Screenshot_1](https://github.com/IAHispano/Applio/assets/129380848/d2409e0c-88d0-426b-8bac-2d40e4bdf6b5)

I have a video card from AMD. It turns out that the script will run on the CPU?

**Comment by blaise-tk** [comment]
Thanks for your support ❤️ Unfortunately training with AMD is very complicated, we will try an integration with DirectML for inference but right now we want to prioritize the correct operation.

**Comment by Witwike** [comment]
Thanks for the answer❤️. My carelessness
