### ISSUE TITLE
[BUG] Stop training button is missing

### ISSUE THREAD

**Issue by deadniell** [IAHispano/Applio#231]
![image](https://github.com/IAHispano/Applio/assets/143788296/a36424c9-6a69-4cdc-8f2f-8854e77ddd1c)

Applio 3.0.4
When pressing the same "start training" button does nothing, it doesn't stop anyways

**Comment by blaise-tk** [comment]
![IMG_2333](https://github.com/IAHispano/Applio/assets/133521603/fb18a1c2-7b9a-47e5-ba0b-6fc18c6f0f61)

**Comment by thomaskarado** [comment]
Just go to setings and hit Restart Apllio
