### ISSUE TITLE
[BUG] Doesn't recognize the tuning/pitch.

### ISSUE THREAD

**Issue by Anteros-B** [IAHispano/Applio#236]
When I was doing my index conversion of a song it works well until I realized that the pitch -12 wasn't applied to the final product. 
[Uploading recording.webm…]()
I was using Crepe with hop-length 128.

**Comment by blaise-tk** [comment]
Uploading recording.webm… Can you upload it?

**Comment by aitronssesin** [comment]
This issue is being closed due to inactivity. If you still encounter this problem or have additional information, please feel free to reopen the issue.
