### ISSUE TITLE
Please provide documentation on usage

### ISSUE THREAD

**Issue by inhahe** [IAHispano/Applio#240]
I'd like some kind of documentation to figure out how to use this program. I could probably get by with the "Inference" section if I had a model, but the program didn't seem to come with any (the pull-down is empty), and I don't know how to get one without paying $10/month to applio.org. So I guess I'd have to use the "Train" feature, but I have no idea how to use it--what any of the options mean, which buttons I have to press, what kinds of files have to be in the dataset path and how to make them, guidelines for making an effective recording to use for training, etc..
Thanks

**Comment by blaise-tk** [comment]
where you can pay 10$ to applio.org? wtf.
if you want more info you can join to the discord or check the docs

**Comment by inhahe** [comment]
thanks, can you tell me where the docs are?
i looked briefly in my applio directory and couldn't find any

I guess it's not applio.org you pay the $10/month to, but there's a link in the UI to find models, which brings you to a website with 500,000 models, but apparently to download them you need to subscribe. I thought it was applio.org because when I hovered over the link the URL to check again where it goes to, it showed applio.org.

**Comment by blaise-tk** [comment]
discord.gg/iahispano
docs.applio.org
