### ISSUE TITLE
Not really an issue just a request for batch support for TTS 

### ISSUE THREAD

**Issue by viktorblack** [IAHispano/Applio#242]
a request for batch support for TTS  would make my life easier ;)

**Comment by blaise-tk** [comment]
wdym?

**Comment by viktorblack** [comment]
i mean having the ability to have multiple text file converted to tts+rvc

**Comment by viktorblack** [comment]
like with the audio but for text :)

**Comment by blaise-tk** [comment]
yeah but the only way to do this is creating multiple textboxes for the input text?

**Comment by viktorblack** [comment]
ah so there is no way to make it read the text from a .txt file? well if its not a option that's fine the tool is amazing anyway;)

**Comment by blaise-tk** [comment]
working on this :D
