### ISSUE TITLE
[BUG] Doesn't see AMD GPU

### ISSUE THREAD

**Issue by Darknight-5157** [IAHispano/Applio#244]
**Describe the bug**
the program does not see my AMD graphics card and sends errors on steps "Feature Extraction", "Model Training" and "Index File Generation"

**Feature Extraction**
I have a message "slow_conv2d_cpu" not implemented for 'Half'
![image](https://github.com/IAHispano/Applio/assets/118758682/607eddf3-9647-413a-89f6-287dab40349f)

**Model Training**
"Failed to train index: need at least one array to concatenate"
![image](https://github.com/IAHispano/Applio/assets/118758682/9cfa8b47-baab-477c-b1f0-3a787fc0561a)

**Index File Generation**
again "Failed to train index: need at least one array to concatenate"

what i do wrong?

**Desktop:**
 - OS: Windows 10
 - Browser : Yandex Browser

**Comment by blaise-tk** [comment]
AMD cards are not supported for training.
