### ISSUE TITLE
Can you add audio cover generation?

### ISSUE THREAD

**Issue by DartPower** [IAHispano/Applio#247]
Can you implement audio cover generation like here?
https://github.com/SociallyIneptWeeb/AICoverGen

**Comment by blaise-tk** [comment]
what exactly? because you can do cover gen with applio

**Comment by DartPower** [comment]
> what exactly? because you can do cover gen with applio

AICoverGen automaticly don't remove the music with new voice and can seperate vocals, dereverbed locals, music without voice and etc

**Comment by aitronssesin** [comment]
Yes it removes the music(instrumental) from the audio and next it inferences the audio without instrumental and finally it merges the 2 audios
![image](https://github.com/IAHispano/Applio/assets/74368135/a140059d-3bcd-4fb6-9dcb-a2514def08b4)

**Comment by aitronssesin** [comment]
Currently, we do not have plans to incorporate that feature. Instead, we encourage users to explore alternative programs such as UVR, where they can enjoy a wide range of customization options to suit their preferences.
