### ISSUE TITLE
[BUG] I found some errors

### ISSUE THREAD

**Issue by mikhail2013ru** [IAHispano/Applio#251]
If I add my trained model, how can I not use the TTS voice? In the advanced settings, by default, synthesis is set for TTS and RVC: tts_output.wav and tts_rvc_output.wav. Is it possible to select only the voice model if I work with my own model? Is it also possible to select mp3 or wav synthesis by default? Can you add a character counter to the text input field? Is it possible to add a real-time synthesis mode? That is, do not wait for the conversion to the end and then listen, but listen during synthesis? If tts_rvc_output.wav is in the directory C:\ApplioV3.0.3\assets\audios\tts_rvc_output.wav already there, is it possible to add a new file with a different index at the next conversion, and not replace the old one? For example: tts_rvc_output(1).wav

**Comment by aitronssesin** [comment]
I think there was an error with the tts try now

**Comment by aitronssesin** [comment]
Any update?

**Comment by aitronssesin** [comment]
Issue closed because inactivity
