### ISSUE TITLE
Hello, how can I get the older versions, before the UI update?

### ISSUE THREAD

**Issue by SpanishHearts** [IAHispano/Applio#258]
Since the new UI update, I have a couple of persisting issues. The recording button is hidden behind the "Upload Your File" panel. I cannot change the output path frequently, and the most notable is that the generation speed is 3-4 times slower on my 3080 Ti. (even though it was running on the GPU and not the CPU)

The previous version's performance was leap and bounds ahead, so how can I get the older one? Thanks!

**Comment by blaise-tk** [comment]
You can download the previous version in the other branch, the bug of the micro, is a gradio bug. If you need specific help join the discord server.
