### ISSUE TITLE
how can I put the number of epochs over 1000?

### ISSUE THREAD

**Issue by XKMEXX** [IAHispano/Applio#265]
Hi, how can I put the number of epochs over 1000?
![Screenshot 2024-02-02 202009](https://github.com/IAHispano/Applio/assets/158604216/01e17c39-fd9c-4184-8389-19c7c54d5597)

**Comment by blaise-tk** [comment]
why you want more than 1k epochs??

**Comment by blaise-tk** [comment]
yes, we don’t recommend training over 1k epochs, usually with 500 epochs you can get a very decent model, if you want to get more, you can modify the tabs/train/ file - i was asking only for curiosity, maybe is something relevant and we have to add more epochs range
