### ISSUE TITLE
The problem with reading speed

### ISSUE THREAD

**Issue by mikhail2013ru** [IAHispano/Applio#266]
The reading speed is set in 4 ways: 0.5x - 1x - 1.5x - 2x. Is it possible to add between 0.5 and 1 more values to fine-tune the reading? 1.5 - 2 in practice are not useful.

**Comment by blaise-tk** [comment]
about what are you talking?

**Comment by mikhail2013ru** [comment]
When the TTS synthesis is completed, I press the play button, and the reading speed of 1x is quite high, there are not enough pauses in intonation. Is it possible to add at least 0.75x more? Or add a separate scale with a reading tempo setting?

**Comment by blaise-tk** [comment]
we can’t manipulate the tts speed because we use a microsoft api, but we will try to found better options for tts customization

**Comment by mikhail2013ru** [comment]
Is it possible to add real-time synthesis? Added text to TTS, pressed the envelope button and the reading started? So you don't have to wait? Is it possible to select synthesis only from a trained voice model without TTS voice? At the moment, without a TTS voice, it immediately gives an error?

**Comment by blaise-tk** [comment]
voice to voice yes https://github.com/w-okada/voice-changer

text to voice realtime rn no

**Comment by mikhail2013ru** [comment]
Is it still possible to work on the accent of the voice? I trained my voice model, tried ready-made ones - I get an "Estonian accent". Can this be eliminated?

**Comment by blaise-tk** [comment]
This depends on the TTS method you use, understand that we have not created the TTS, only implemented it. If you want better assistance in specific cases join our discord https://discord.gg/iahispano
