### ISSUE TITLE
[Enhancement] Support for stereo inferences

### ISSUE THREAD

**Issue by klinok64** [IAHispano/Applio#269]
While I am not a professional programmer, I would like to share my suggestion.

As far as I know, neither rvc nor applio support stereo audio conversion. Therefore, I propose the following solution:

1. **Splitting stereo into two mono files:**

We use ffmpeg to split the stereo audio into two mono files.

[https://trac.ffmpeg.org/wiki/AudioChannelManipulation#stereo2monofiles](url)

2. **Processing mono files:**

We run the mono files through inference.

3. **Combining mono files into stereo:**

We use ffmpeg again to combine the processed mono files into a single stereo file.

[https://trac.ffmpeg.org/wiki/AudioChannelManipulation#a2monostereo](url)

I understand that this method will require twice the processing time compared to the standard method. However, I think it is a quite useful option.

**Comment by JackVinati** [comment]
BUT WHY? you can simply inference on a mono and using ffmpeg and convert it to stereo

**Comment by klinok64** [comment]
Because I am lazy lol
I use applio too often and my disk full of files like example_L.wav and example_R.wav
I just want to press a button and boom magic or something

**Comment by klinok64** [comment]
I also want to specify that I don't want to do it MANUALLY, that whole process is very time consuming

**Comment by blaise-tk** [comment]
As it is something extra, we would appreciate a PR from your side adding these features
