### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by onasre** [IAHispano/Applio#276]
Hi
i get this error while trying to Train a model , 

`Training has been successfully completed with 8 epoch and 16 steps.
Saving final checkpoint: Success!
Failed to train index: need at least one array to concatenate
Index training finished!`

i get the pth model but dose not create index file due to the error 

Windows 10 64bit
16GB ram
No GPU
Intel 620

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio/assets/74368135/d7291718-7dc6-4586-8f61-87f45db84efe)
https://docs.applio.org/get-started/training/
