### ISSUE TITLE
[BUG] pretrain fail without gpu 

### ISSUE THREAD

**Issue by alphaleadership** [IAHispano/Applio#280]
**Describe the bug**
"slow_conv_2d_cpu" not implemented for 'Half' when you try to pretrain without gpu 

**Expected behavior**
pretrain correctly file 

**Assets**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox

**Additional context**

**Comment by blaise-tk** [comment]
why are you trying this without a gpu?
