### ISSUE TITLE
Create tts_output.wav and find tts_rvc_output.wav.[BUG]

### ISSUE THREAD

**Issue by newkincode** [IAHispano/Applio#287]
**Describe the bug**
When you create a voice in tts, it creates tts_output.wav and finds tts_rvc_output.wav, and you get an error saying the file does not exist.

**To Reproduce**
1. Go tts
2. Complete the settings
3. Click Convert

**Expected behavior**
A voice file appears.

**Assets**
![image](https://github.com/IAHispano/Applio/assets/94734506/4551ab68-53b9-4833-8dfc-a0027cc5a90a)
![image](https://github.com/IAHispano/Applio/assets/94734506/4d5db36b-98b8-49d1-be4f-29751e7c9c5d)

**Desktop (please complete the following information):**
 - OS: macos 14
 - Browser: firefox

**Additional context**

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio/assets/74368135/8d7943db-8274-4c1e-9916-82b09c218e10)
It's not officially supported by now
