### ISSUE TITLE
[BUG] Wrong precompiled link on Release Page Applio 3.0.6

### ISSUE THREAD

**Issue by cheesypy** [IAHispano/Applio#289]
**Describe the bug**
On release page for Applio 3.0.6, precompiled link points to:
https://huggingface.co/IAHispano/applio/resolve/main/Applio%20V3%20Precompiled/ApplioV3.0.6.zip?download=true
Which gives me an error.

Maybe you meant this one ?
https://huggingface.co/IAHispano/Applio/resolve/main/Compiled/ApplioV3.0.6.zip?download=true

**To Reproduce**

1. Go to ['Applio 3.0.6 Release page'](https://github.com/IAHispano/Applio/releases/tag/3.0.6)
2. Click on [precompiled](https://huggingface.co/IAHispano/applio/resolve/main/Applio%20V3%20Precompiled/ApplioV3.0.6.zip?download=true)
3. See error

**Expected behavior**
I wanted to download the precompiled version of the project ApplioV3.0.6.zip from huggingface by clicking the link

**Comment by blaise-tk** [comment]
yeah we are doing some changes, check the readme for the links

**Comment by cheesypy** [comment]
K, was just relating in case you weren't aware of it. The link for the precompiled directory in the readme page is also a 404.

**Comment by aitronssesin** [comment]
Fixed
