### ISSUE TITLE
[BUG] error for saving final .pth model file

### ISSUE THREAD

**Issue by RatDotRaw** [IAHispano/Applio#294]
**Describe the bug**
Models are not saving because (see error below).

**To Reproduce**
It happens with model training process at the saving part, changing settings doesn't matter.

**Expected behavior**
To find the final `.pth` files in the weights directory.

**Assets**
here is the error from the console:
```
Saved model 'C:\...\Applio-RVC-Fork\logs\pop_smoke\G_2333333.pth' (epoch 100)
Saved model 'C:\...\GitHub\Applio-RVC-Fork\logs\pop_smoke\D_2333333.pth' (epoch 100)
Process Process-1:
Traceback (most recent call last):
  File "C:\...\Applio-RVC-Fork\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\...\Applio-RVC-Fork\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\...\Applio-RVC-Fork\rvc\train\train.py", line 261, in run
    train_and_evaluate(
  File "C:\...\Applio-RVC-Fork\rvc\train\train.py", line 562, in train_and_evaluate
    ckpt,
UnboundLocalError: local variable 'ckpt' referenced before assignment
Index training finished!
```
![image](https://github.com/IAHispano/Applio/assets/33757638/436f1198-d2c9-4f1e-a4fb-8d9fed76c77a)

**Desktop:**
 - OS: Windows 11
 - Browser: Librewolf (Firefox)

**Additional context**
My previous installation broke and did a complete reinstallation to the newest version (commit 35f15830b4a7ff00cc541e6c1ca862b0cda0f16b). 
Reinstalling the newest version doesn't work either.

If there are any further questions, I'll do my best to answer them.

**Comment by blaise-tk** [comment]
Fixed, you can get it cloning the repo or waiting to the next release!

**Comment by RatDotRaw** [comment]
I think this is the same bug https://github.com/IAHispano/Applio/issues/293
