### ISSUE TITLE
[BUG] Dataset Creator does not work on different disks

### ISSUE THREAD

**Issue by kurgansprize** [IAHispano/Applio#298]
**Describe the bug**
it don't work

**To Reproduce**
1. try to use dataset creator
2. name the dataset and select the audio file
3. ???

**Expected behavior**
an operational feature

**Assets**
![cmd_iAMxkt1zox](https://github.com/IAHispano/Applio/assets/145931953/3697e1dd-ad70-4919-bf5d-7881cb856759)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox

**Additional context**

**Comment by blaise-tk** [comment]
Please read
![image](https://github.com/IAHispano/Applio/assets/133521603/cf871f2d-9bfe-448a-9f4b-f39091ec00f5)

**Comment by aitronssesin** [comment]
That's also normal because applio should't work in a different disk that isn't C: also your user has spaces in it's name
