### ISSUE TITLE
[BUG] Install Script is forcing Brew + Python 3.11 on macos

### ISSUE THREAD

**Issue by Chilluminati91** [IAHispano/Applio#303]
Right now its a PITA to install on macos due to incompatible dependencies.
Even if you have brew + python installed the installer-script on line 77 is forcing the install of Python 3.11.7 (latest?).
I'd suggest changing that to python@3.10 as long as the dependencies are broken.
Line 54 installs cu117 pytorch, which is also incompatible (apple silicon) and can be replaced with "pip3 install torch torchvision torchaudio". Latest versions are working.

```
torch                     2.2.0
torchaudio                2.2.0
torchcrepe                0.0.21
torchvision               0.17.0
```

**Comment by blaise-tk** [comment]
Feel free to open a PR

**Comment by Morac2** [comment]
The PR above will allow this to install on macOS by using Python 3.10.  I found upgrading numpy or using torch 2.2 or 2.2.1 would install, but would just hang indefinitely in conversion so I left those alone.
