### ISSUE TITLE
Missing 32k pretrain option for model merging.

### ISSUE THREAD

**Issue by litsa-the-dancer** [IAHispano/Applio#308]
Well, as the title suggest, applio doesnt support 32k merging and only supports 40k and 48k. Please tend to this as it is very crucial for a lot of models and wouldnt hurt to have. Most models should be trained on 32k anyway. Thanks for listening.  :3

**Comment by blaise-tk** [comment]
![image](https://github.com/IAHispano/Applio/assets/133521603/0015974a-13d4-4e3e-81d5-6e96e32844ba)
Model fusion is not working right now, we have to investigate the issue.
