### ISSUE TITLE
No module named gradio

### ISSUE THREAD

**Issue by diegoalejo15** [IAHispano/Applio#315]
I´ve installed Applio 3.0.7 in Windows 10, when I try to run run-applio.bat I get the error modulenotfounderror: no module named gradio. What shall I do?

Thx

**Comment by blaise-tk** [comment]
Use the compiled version https://huggingface.co/IAHispano/Applio/tree/main/Compiled

**Comment by ZeusLT** [comment]
> I´ve installed Applio 3.0.7 in Windows 10, when I try to run run-applio.bat I get the error modulenotfounderror: no module named gradio. What shall I do?
> 
> Thx

Had same problems, "compiled" version didn't work either. Fixed it by ditching conda enviroments and creating my own setup and run .bat files:

Setup.bat:
```
call python -m venv .
call .\Scripts\activate.bat
call python -m pip install --upgrade pip
call pip3 install -r requirements.txt
```

Run.bat:
```
call .\Scripts\activate.bat
python app.py --open
```

Tensorboard.bat:
```
call .\Scripts\activate.bat
python core.py tensorboard
```


I tried all the install methods and nothing else worked. Can't believe it was that simple.
