### ISSUE TITLE
[BUG] errors when running run-install.bat

### ISSUE THREAD

**Issue by amarillosebas** [IAHispano/Applio#324]
`
Exception calling "ExtractToDirectory" with "2" argument(s): "End of Central Directory record could not be found."
At line:1 char:63
+ ... ileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory('F:\A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidDataException
`

Well, no matter what I do it seems that GitHub will always want to "format" the error code I pasted straight out of the command prompt. Here's an image:

[image](https://imgur.com/GPyUsFM)

**Comment by blaise-tk** [comment]
HuggingFace is down right now, try it again in a few hours
