### ISSUE TITLE
[BUG] After the last update 3.0.8 I can no longer convert audio

### ISSUE THREAD

**Issue by SpanishHearts** [IAHispano/Applio#325]
After the last update, when I record and try to covert audio I got this error

" File "H:\A.I. Software\Apollo RVC\Applio\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\A.I. Software\\Apollo RVC\\Applio\\assets\\audios\\2024-02-29_07-34-57_output.wav'"

**Comment by sanebg** [comment]
Yeah, I was just about to report the same issue. Bummer.

**Comment by truong0493** [comment]
me too

**Comment by blaise-tk** [comment]
Duplicated https://github.com/IAHispano/Applio/issues/214
