### ISSUE TITLE
Training with 40k Sample Rate

### ISSUE THREAD

**Issue by Tox1cPhantom** [IAHispano/Applio#327]
i was trying to train it from WSL without GUI, but i have noticed an issue with the configs, on GUI we specify v2 and it trains the model whether they are old models or the OV2 by SimplCup pretrained high quality models, even without having the v1 config, but when i run it with WSL it gives me the error of v2/40000.json, it won't work with v1 saying:

size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256])

**Comment by blaise-tk** [comment]
OV2 pretraineds are only available for v2.

**Comment by Tox1cPhantom** [comment]
That's weird i tried selecting v2 and 40k on GUI and used those custom pretrained OV2 and it started but when i try to do it with WSL it fails and give error

![image](https://github.com/IAHispano/Applio/assets/14037573/ad9a00ea-3802-4d19-9921-97f18f1178e8)
