### ISSUE TITLE
[BUG] Setting the pitch value to float will not process the audio

### ISSUE THREAD

**Issue by ghaffur** [IAHispano/Applio#329]
**Describe the bug**
In the TTS tab, if you set the pitch value to float numbers, it will not run the conversion.

For example, setting the pitch value to 10 works, but 10.2 does not.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge

**Comment by blaise-tk** [comment]
It's not a bug, pitch must be an integer
