### ISSUE TITLE
Inference Model Selection Doesn't Auto Select Index File

### ISSUE THREAD

**Issue by Prodabic** [IAHispano/Applio#332]
**Describe the bug**
Whenever selecting a model to inference with, the index file doesn't auto select itself.

**To Reproduce**
1. Go to 'Inference'
2. Select a model

**Expected behavior**
The model selects its index file when selecting said model automatically.
model.pth and added_model.index

**Desktop:**
 - OS: Windows 10
 - Browser: Opera GX

**Additional context**
This has been happening since version 3.0.5 or 3.0.6.

**Comment by aitronssesin** [comment]
If a model doesn't have the correct format for the index, try using another model, as some models can't be auto-selected due to incompatible formatting.
