### ISSUE TITLE
Formant Shifting suggestion

### ISSUE THREAD

**Issue by SilvazeYakko** [IAHispano/Applio#335]
I love the new Applio updates, but, I would like to have the formant shift section there for the interface. That way, I can convert male to female voices, along with the 50HZ to 11hz inference frequencies, just like from the previous version. I'm glad that the inferencing times are faster.

**Comment by Subraiz** [comment]
you really don't need Applio for this just use [parselmouth](https://parselmouth.readthedocs.io/en/stable/)

`
from parselmouth.praat import call

def shift_formant(audio_path: str, factor: float) -> str:
    """Shift audio formant and preserve pitch

    Args:
        audio_path (str): path to file
        factor (float): factor of formant shift to apply

    Returns:
        str: path of saved file
    """
    shifted_audio_path = audio_path.replace(".wav", "_shifted.wav")

    sound = parselmouth.Sound(audio_path)
    shifted_sound = call(sound, "Change gender", 100, 500, factor, 0, 1, 1)

    shifted_sound.save(shifted_audio_path, "WAV")

    return shifted_audio_path
`
