### ISSUE TITLE
Using Voice blender for two different models that has different bit depths

### ISSUE THREAD

**Issue by Mokapella** [IAHispano/Applio#336]
Okay it seems like Applio's voice blender doesn't allow me to blend two different models with different bit-depths

One is the model that I trained myself, which is 48k, 24 bit and the other one is a downloaded model from AI hub and seems like it's trained as 40K 16 bit.

if I wanted to blend these two models, do I have to train my model again as 16 bit or is there a way to convert and match one to the other?

**Comment by blaise-tk** [comment]
The training settings need to be matched; pitch... But the dataset is not relevant. We haven't tested that section much yet, but you can see it by looking at the information of the models in the Extra section and then trying to merge them.
