### ISSUE TITLE
Split audio option when converting audios in batches

### ISSUE THREAD

**Issue by Mokapella** [IAHispano/Applio#338]
When converting audios in batches, if I select the split audio option, it doesn't unite the chunked audio file.
I only can find the folders that contain chunk audios, is it suppose to do this way?

**Comment by tomakorea** [comment]
Exact same issue here on Linux

**Comment by Chilluminati91** [comment]
Does your output folder exist prior to conversion? Could be related to the bug that the output folder HAS to exist, otherwise the files wont be saved. It is not automatically created.

**Comment by aitronssesin** [comment]
Closing this issue due to lack of response. Feel free to reopen if needed.
