### ISSUE TITLE
[BUG] Failed to train index

### ISSUE THREAD

**Issue by ZeusLT** [IAHispano/Applio#342]
At the end of training it says:
```
Failed to train index: need at least one array to concatenate
If you are running this code in a virtual environment, make sure you have enough GPU available to generate the Index file.
```

I also noticed that it says `Unfortunately, there is no compatible GPU available to support your training.` in the advanced gpu settings. I have RTX 3060. I updated my "game ready" drivers.

At the start of the training there is this warning: 

```
Starting training...
C:\Users\ZeusLT\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\__init__.py:251: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at ..\torch\csrc\distributed\c10d\reducer.cpp:334.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
```

**Comment by brcisna** [comment]
Failed to train index: need at least one array to concatenate
If you are running this code in a virtual environment, make sure you have enough GPU available to generate the Index file.

Linux Debian 12,  python-3.10.12 

I am getting the same error, Running on CPU only 
Everything else appears to be working correctly on this install of Applio,,,although am new to this,,May be other underlaying problems,have not hit yet?

Thanks,,This looks like amazing for voice cloning

**Comment by ZeusLT** [comment]
It seems that "extract features" doesn't generate any files into the folder "3_feature768".

**Comment by ZeusLT** [comment]
`3_feature256` and `3_feature768` folders are empty, when I use "extract features" I get a bunch of these:
```
"slow_conv2d_cpu" not implemented for 'Half'
"slow_conv2d_cpu" not implemented for 'Half'
"slow_conv2d_cpu" not implemented for 'Half'
"slow_conv2d_cpu" not implemented for 'Half'
"slow_conv2d_cpu" not implemented for 'Half'
```
Does this mean that the files failed to generate, hence the "need at least one array to concatenate"?

**Comment by ZeusLT** [comment]
Okay I fixed it. It was passing 16bit float where it was supposed to be 32bit. I'm unsure what is the best solution, but converting it too 32bit works. 
Inside `\Applio\rvc\train\extract\extract_feature_print.py` line` 86`

Before:
```
                    inputs = {
                        "source": feats.to(device),
                        "padding_mask": padding_mask.to(device),
                        "output_layer": 9 if version == "v1" else 12,
                    }
```
After:
```
                    inputs = {
                        "source": feats.to(device).float(),
                        "padding_mask": padding_mask.to(device),
                        "output_layer": 9 if version == "v1" else 12,
                    }
```

**Comment by ZeusLT** [comment]
Okay it seems like it was not a proper solution. 
I've noticed my torch was not a cuda version.
"pip list" before:
![image](https://github.com/IAHispano/Applio/assets/22300013/72b56584-fb22-4ed0-961e-a5b781344c00)

Running this pip command fixed it for me:
`pip install --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

"pip list" after:
![image](https://github.com/IAHispano/Applio/assets/22300013/1a1320c8-7206-488a-9d94-1b13a3b6c8ae)

**Comment by brcisna** [comment]
Adding:

On the Google Colab of Applio when training a voice the training always went well and generated a pth file,and then post process to makle the index file I got the above mentioned error.
This also happened if i tried to simply generate the index without doing the training button itself.
ERROR:
Failed to train index: need at least one array to concatenate
If you are running this code in a virtual environment, make sure you have enough GPU available to generate the Index file.

This was using the T4 GPU. Never did try it will the cpu runtime.

**Comment by brcisna** [comment]
@ZeusLT 

Are you getting any saved .pth files? 
When i click on 'start traning' end up with two .index files,,,and no .pth file?

Ideas?
Am on Debian 12 Linux , Python=3.10.12

Did just do a 'git pull,',and pulled down 6 new py files,,,but made no difference.

Thanks

**Comment by ZeusLT** [comment]
> @ZeusLT
> 
> Are you getting any saved .pth files? When i click on 'start traning' end up with two .index files,,,and no .pth file?
> 
> Ideas? Am on Debian 12 Linux , Python=3.10.12
> 
> Did just do a 'git pull,',and pulled down 6 new py files,,,but made no difference. If i run the Google Colab it does generate the 'pht files.
> 
> Thanks

Without any output log it would be hard to tell.

**Comment by brcisna** [comment]
`Process dataset{

No supported Nvidia GPU found
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
Starting preprocessing...
Preprocessing completed!


Extract features: (rmvpe)

No supported Nvidia GPU found
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
Starting preprocessing...
Preprocessing completed!

Start training:  2 - 10 - 100 , settings ,,,check only Save only latest 

rocess Process-1:
Traceback (most recent call last):
  File "/home/brcisna/.pyenv/versions/3.10.12/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/brcisna/.pyenv/versions/3.10.12/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brcisna/MyPrograms/applio1/Applio1/rvc/train/train.py", line 143, in run
    train_sampler = DistributedBucketSampler(
  File "/home/brcisna/MyPrograms/applio1/Applio1/rvc/train/data_utils.py", line 363, in __init__
    self.buckets, self.num_samples_per_bucket = self._create_buckets()
  File "/home/brcisna/MyPrograms/applio1/Applio1/rvc/train/data_utils.py", line 385, in _create_buckets
    total_batch_size - (len_bucket % total_batch_size)
ZeroDivisionError: integer division or modulo by zero
Saved index file '/home/brcisna/MyPrograms/applio1/Applio1/logs/linneal32k/added_IVF591_Flat_nprobe_1_v2.index'



`

**Comment by ZeusLT** [comment]
> total_batch_size - (len_bucket % total_batch_size)
> ZeroDivisionError: integer division or modulo by zero
This would indicate that "total_batch_size" ended up a zero. Check if there are files in:
/logs/linneal32k/0_gt_wavs
/logs/linneal32k/1_16k_wavs
/logs/linneal32k/2a_f0
/logs/linneal32k/2b-f0nsf
/logs/linneal32k/3_feature768

How long is your voice data set?

**Comment by brcisna** [comment]
Thanks for trying to help @ZeusLT 
All i have is the first two directories you mention in your post and a preprocessor.txt file,,thats all.

Would it have anything to doi with running only on CPU,,, I have tried learning about the fp16 thing,,that keeps coming up in discussions.
I also read many many posts froma year ago,,,whisper,,,had similar errors,,as what spews out here,,in my post,,,and was that would run fine in VScode and on windows but failed in linux,,,was something to the GCC versions...
Am in the process of rigging up a decent GPU machine as we speak,

**Comment by ZeusLT** [comment]
It seems that it fails to extract features. Applio don't support cpu only and I can't help much. Goodluck
