### ISSUE TITLE
[BUG]Assets cannot be deleted for me

### ISSUE THREAD

**Issue by Oktoberfest40** [IAHispano/Applio#345]
I don't know why, but when I click to delete the assets, they are still there. I don't know if it is due to an installation problem or something else. 
Here in the recording sampling in detail what I mean

It should be noted that even loading the page again, the assets are still there.

[recording.webm](https://github.com/IAHispano/Applio/assets/60051660/adaf0e70-0245-4834-8a1d-d60284d6565f)

**Comment by aitronssesin** [comment]
That only deletes _outputs no assets
