### ISSUE TITLE
Does this software contain viruses? I keep having files deleted or corrupted lately.

### ISSUE THREAD

**Issue by userbob2** [IAHispano/Applio#348]
Does this software contain viruses? I keep having files deleted or corrupted lately.

**Comment by blaise-tk** [comment]
No

**Comment by userbob2** [comment]
Thank you for your answer. 
But I also want to feedback a question about version 3.08, which is about text-to-speech. After multiple conversions of the same piece of text, the speed and volume will be inconsistent. 3.07 I didn't find this problem.
