### ISSUE TITLE
[Enhancement] Voice Blender Merge Ratio

### ISSUE THREAD

**Issue by Chilluminati91** [IAHispano/Applio#352]
The description of the merge ratio is very unclear atm. and it sounds more like "pull it to the right to get more of the right model and to the left to get more of the left model".
I tested a bit and found that the merge ratio itself just sets the weight of the first model, so a ratio of 0.8 gives you 80% of the first / left model and 20% of the second / right model.

Should be changed to clear up misunderstandings.

**Comment by blaise-tk** [comment]
feel free to open a pr
