### ISSUE TITLE
"Stop Training & Restart Applio" Button Doesn't Work

### ISSUE THREAD

**Issue by UberStorm** [IAHispano/Applio#357]
Hi,
I use the latest version and "Stop Training & Restart Applio" button creates an error and even when Applio restarts and opens in a new page, the old training keeps going to background.
The only way to stop training is to just shut Applio down after waiting to a weight to be saved.
Please fix it and keep up the awesome work, you give the best RVC experience out there imo ♥

**Comment by aitronssesin** [comment]
I checked the "Stop Training & Restart Applio" button, and it works perfectly. The error that appears in the UI indicates that Applio has been shut down successfully, and if Applio closes, the training cannot continue.

**Comment by UberStorm** [comment]
> I checked the "Stop Training & Restart Applio" button, and it works perfectly. The error that appears in the UI indicates that Applio has been shut down successfully, and if Applio closes, the training cannot continue.

Here's a screenshot that proves what I said:
![image](https://github.com/IAHispano/Applio/assets/147564504/db70ce27-b903-44e5-adcd-e5285c62a062)

**Comment by aitronssesin** [comment]
Indeed, you're correct! I've already addressed it, and in the upcoming release of Applio, this issue will be resolved. Thank you sincerely for your invaluable assistance!
