### ISSUE TITLE
Bug in the code - it doesn't work.

### ISSUE THREAD

**Issue by SpanishHearts** [IAHispano/Applio#361]
For a thousand time, the dreaded "No such file or directory" that cannot be resolved for years.

The issue is pretty simple - the error states " No such file or directory: 'F:\\Downloads\\Chrome Downloads\\NonaPhoneAlexa_output.wav'" 

Here is the bummer - the original file is called NonaPhoneAlexa, the app tries to find NonaPhoneAlexa_output which is wrong. 

The SAME FILE on the SAME LOCATION, works perfectly fine in 3.0.3 version. Obviously you changed something in the newer versions that causes this.

**Comment by blaise-tk** [comment]
Duplicated https://github.com/IAHispano/Applio/issues/344
