### ISSUE TITLE
[BUG] Precompiled versions dont exist

### ISSUE THREAD

**Issue by mwamon** [IAHispano/Applio#363]
**Bug Description**
Trying to download a precompiled version of Applio for Windows, clicking the link takes me to a HuggingFace tab that says it doesn't exist.

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Go to https://huggingface.co/IAHispano/Applio/tree/main/Applio%20V3%20Precompiled
2. Observe the 404 error.

**Expected Behavior**
For the link to load and allow me to download a precompiled Applio release for Windows.

**Assets**
![Screenshot 2024-03-22 145223](https://github.com/IAHispano/Applio/assets/140141716/447a48de-7d36-40f8-82bf-c77d6fccebf4)

**Desktop Details:**
- Operating System: [Windows 11]
- Browser: [Chrome]

**Additional Context**
N/A

**Comment by blaise-tk** [comment]
https://huggingface.co/IAHispano/Applio/tree/main/Compiled
