### ISSUE TITLE
[BUG] Applio doesn't create .pth file

### ISSUE THREAD

**Issue by mwamon** [IAHispano/Applio#364]
**Bug Description**
After training my model, having successfully uploaded all audios for the dataset - I don't see any .pth file in the folder for my model under the logs folder like it's supposed to be. 

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Go to 'Train'
2. Click on 'Start Training'
3. Wait until training is complete.
4. Observe the error.

**Expected Behavior**
For Applio to produce a proper .pth file of my voice model and the corresponding index for it.

**Assets**
Include screenshots or videos if they can illustrate the issue:
![Screenshot 2024-03-23 144630](https://github.com/IAHispano/Applio/assets/140141716/b55e2cb2-3529-4925-aabb-efb7437d1c6d)
![Screenshot 2024-03-23 144643](https://github.com/IAHispano/Applio/assets/140141716/53d147c7-694b-44fe-b839-d93c2ac92998)
![Screenshot 2024-03-23 144653](https://github.com/IAHispano/Applio/assets/140141716/4c465ea9-7dbe-49f5-9553-f97c5b1a213d)
![Screenshot 2024-03-23 144708](https://github.com/IAHispano/Applio/assets/140141716/93404762-50ae-4090-87e0-1b053fb0934d)

**Desktop Details:**
Windows 11 Home Single Language
Google Chrome

**Additional Context**
I have to use Fake GPU as my laptop apparently doesnt have one already.

**Comment by blaise-tk** [comment]
whats your gpu

**Comment by mwamon** [comment]
> whats your gpu
My computer says it doesnt have one/doesn't detect one so I had to use the Fake GPU option.

**Comment by blaise-tk** [comment]
> > whats your gpu
> 
> My computer says it doesnt have one/doesn't detect one so I had to use the Fake GPU option.

oh yeah, you can't train without a gpu, you should try a cloud service for training like google colab

**Comment by mikhail2013ru** [comment]
Is it possible to add GPU support for Intel HD 730, 770, etc.? Many laptops, it would help to train on their device. Let it be slow, but the training can be stopped and then resumed.

**Comment by mwamon** [comment]
> > > whats your gpu
> > 
> > 
> > My computer says it doesnt have one/doesn't detect one so I had to use the Fake GPU option.
> 
> oh yeah, you can't train without a gpu, you should try a cloud service for training like google colab

The Google Colabs constantly disconnect then I have to reconnect, this is why I wanted to try Applio to train. It would be nice if there was a clear indication we can't train without GPUs, otherwise why does the "Fake GPU" option exist to unlock the training tab?

**Comment by blaise-tk** [comment]
here you have info https://docs.applio.org/get-started/training/ - this option exists because you can train the index file, or do the preprocess/extraction, but not the training
