### ISSUE TITLE
Convert RVC failed with TTS 

### ISSUE THREAD

**Issue by Kerorowong** [IAHispano/Applio#366]
Get this error while doing TTS

> To create a public link, set `share=True` in `launch()`.
> TTS with zh-TW-HsiaoChenNeural completed. Output TTS file: 'F:\VA\Applio-3.0.8\assets\audios\tts_output.wav'
> <All keys matched successfully>
> Traceback (most recent call last):
>   File "F:\VA\Applio-3.0.8\rvc\infer\infer.py", line 251, in <module>
>     get_vc(model_path, 0)
>   File "F:\VA\Applio-3.0.8\rvc\infer\infer.py", line 228, in get_vc
>     net_g = net_g.half()
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\torch\nn\modules\module.py", line 1014, in half
>     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
>     module._apply(fn)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
>     module._apply(fn)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
>     param_applied = fn(param)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\torch\nn\modules\module.py", line 1014, in <lambda>
>     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
> RuntimeError: CUDA error: operation not supported
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> Traceback (most recent call last):
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
>     output = await route_utils.call_process_api(
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
>     outputs_cached = processing_utils.move_files_to_cache(
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
>     return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
>     return func(json_obj)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
>     temp_file_path = move_resource_to_block_cache(payload.path, block)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
>     return block.move_resource_to_block_cache(url_or_file_path)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
>     temp_file_path = processing_utils.save_file_to_cache(
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
>     temp_dir = hash_file(file_path)
>   File "F:\VA\Applio-3.0.8\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
>     with open(file_path, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'F:\\VA\\Applio-3.0.8\\assets\\audios\\tts_rvc_output.wav'

![image_2024-03-24_202429001](https://github.com/IAHispano/Applio/assets/164055086/9fe26909-b564-4381-b0c5-4b8cbdb94654)
![image_2024-03-24_202515958](https://github.com/IAHispano/Applio/assets/164055086/b62744c1-e82e-4f3a-99b4-025b1d68c6ee)

**Comment by Kerorowong** [comment]
> whats your hardware?

Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
AMD rx6600 xt

**Comment by blaise-tk** [comment]
ok, try to move applio to your C disk and use the compiled version

**Comment by Kerorowong** [comment]
![image_2024-03-26_015515883](https://github.com/IAHispano/Applio/assets/164055086/d32f7b80-298b-48ff-bbcc-e65fad2e63cb)
![image_2024-03-26_015602728](https://github.com/IAHispano/Applio/assets/164055086/dd34ffb6-124b-4d01-bc45-e34ad350e43e)

> Theme Loaded: Applio
> Running on local URL:  http://127.0.0.1:6969
> 
> To create a public link, set `share=True` in `launch()`.
> DoraemonJap.pth saved in C:\VA\ApplioV3.0.9\logs\DoraemonJap
> added_IVF1499_Flat_nprobe_1_DoraemonJap_v2.index saved in C:\VA\ApplioV3.0.9\logs\DoraemonJap
> TTS with zh-TW-YunJheNeural completed. Output TTS file: 'C:\VA\ApplioV3.0.9\assets\audios\tts_output.wav'
> <All keys matched successfully>
> Traceback (most recent call last):
>   File "C:\VA\ApplioV3.0.9\rvc\infer\infer.py", line 260, in <module>
>     get_vc(model_path, 0)
>   File "C:\VA\ApplioV3.0.9\rvc\infer\infer.py", line 236, in get_vc
>     net_g = net_g.half()
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 1014, in half
>     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
>     module._apply(fn)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
>     module._apply(fn)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
>     param_applied = fn(param)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 1014, in <lambda>
>     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
> RuntimeError: CUDA error: operation not supported
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> Traceback (most recent call last):
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
>     output = await route_utils.call_process_api(
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\route_utils.py", line 230, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\blocks.py", line 1599, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\blocks.py", line 1453, in postprocess_data
>     outputs_cached = processing_utils.move_files_to_cache(
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 267, in move_files_to_cache
>     return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio_client\utils.py", line 981, in traverse
>     return func(json_obj)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 259, in _move_to_cache
>     temp_file_path = move_resource_to_block_cache(payload.path, block)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 236, in move_resource_to_block_cache
>     return block.move_resource_to_block_cache(url_or_file_path)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\blocks.py", line 257, in move_resource_to_block_cache
>     temp_file_path = processing_utils.save_file_to_cache(
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
>     temp_dir = hash_file(file_path)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
>     with open(file_path, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\VA\\ApplioV3.0.9\\assets\\audios\\tts_rvc_output.wav'
> TTS with zh-TW-YunJheNeural completed. Output TTS file: 'C:\VA\ApplioV3.0.9\assets\audios\tts_output.wav'
> <All keys matched successfully>
> Traceback (most recent call last):
>   File "C:\VA\ApplioV3.0.9\rvc\infer\infer.py", line 260, in <module>
>     get_vc(model_path, 0)
>   File "C:\VA\ApplioV3.0.9\rvc\infer\infer.py", line 236, in get_vc
>     net_g = net_g.half()
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 1014, in half
>     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
>     module._apply(fn)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
>     module._apply(fn)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
>     param_applied = fn(param)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\torch\nn\modules\module.py", line 1014, in <lambda>
>     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
> RuntimeError: CUDA error: operation not supported
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> Traceback (most recent call last):
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
>     output = await route_utils.call_process_api(
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\route_utils.py", line 230, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\blocks.py", line 1599, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\blocks.py", line 1453, in postprocess_data
>     outputs_cached = processing_utils.move_files_to_cache(
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 267, in move_files_to_cache
>     return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio_client\utils.py", line 981, in traverse
>     return func(json_obj)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 259, in _move_to_cache
>     temp_file_path = move_resource_to_block_cache(payload.path, block)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 236, in move_resource_to_block_cache
>     return block.move_resource_to_block_cache(url_or_file_path)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\blocks.py", line 257, in move_resource_to_block_cache
>     temp_file_path = processing_utils.save_file_to_cache(
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
>     temp_dir = hash_file(file_path)
>   File "C:\VA\ApplioV3.0.9\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
>     with open(file_path, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\VA\\ApplioV3.0.9\\assets\\audios\\tts_rvc_output.wav'

Use the compiled version in C drive, still having the same error

**Comment by blaise-tk** [comment]
It looks like it might be more of a compatibility bug with your computer, check forums that discuss similar things.

https://discuss.huggingface.co/t/cuda-error-device-side-assert-triggered-after-a-certain-steps/47597/5
