### ISSUE TITLE
Model Won't Show Up[BUG]

### ISSUE THREAD

**Issue by ichhabproblememanno** [IAHispano/Applio#368]
**Hello GitHub-Team,**
I've been trying to use your applio site to make ai covers. My models are verified and come from a community I trust, and I've installed them on my drive correctly. Upon entering the link into the download section for models, even though the application says that the download was successful, unfortunately, after I have refreshed the inference site no models show up. 
What could be the cause of this issue and how can I fix it?
Thank you very much in advance, and I apologize for any grammar or spelling mistakes as English isn't my mothertongue. 
Best Regards!

**Desktop Details:**
- Operating System: Windows 11
- Browser: Opera GX
[recording (1).webm](https://github.com/IAHispano/Applio/assets/164878479/fdb8ccf8-cf84-40d7-9691-b19b03857d52)

**Comment by blaise-tk** [comment]
share me the link of the model

**Comment by ichhabproblememanno** [comment]
> share me the link of the model

https://drive.google.com/file/d/1Te5jS_YSaqZlYYJC9cLVHr-ibt2Fus9i/view?usp=drive_link

**Comment by ichhabproblememanno** [comment]
> share me the link of the model
