### ISSUE TITLE
Overtrain Detection, is it working as it is supposed to?

### ISSUE THREAD

**Issue by norasyeezys** [IAHispano/Applio#370]
So the model I'm training using overtrain detection, the training actually stops when it hits 50 Epochs, instead of waiting until 50 Epochs AFTER there is a sign of no improvement.

The overtrain model slider only goes to 100 epochs, and the way it works right now, it actually undertrains the models! Can you please look into this issue?

**Comment by blaise-tk** [comment]
Training stops after X epoch from your lowest point. What you say would be strange since in the first epochs the models do have a more constant descent. You can start the training with the slider at 100 and when the training stabilizes further lower it.

**Comment by norasyeezys** [comment]
> Training stops after X epoch from your lowest point. What you say would be strange since in the first epochs the models do have a more constant descent. You can start the training with the slider at 100 and when the training stabilizes further lower it.

My model stopped training AT 50 epochs sharp. The lowest point was 38 Epoch.
