### ISSUE TITLE
error when train with pretrained personalized

### ISSUE THREAD

**Issue by ivaxsirc** [IAHispano/Applio#374]
**Before You Report a Bug**
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

**Bug Description**
When you trained a model when you want to retrain with a pretrained personalized on load the model gives an error 

OSError: [WinError 17] El sistema no puede mover el archivo a otra unidad de disco: 'C:\\Users\\xaviercris\\AppData\\Local\\Temp\\gradio\\9d6b73a537a0169a57a5a760c9eea816cf5b0cd2\\xavicanta_70e_350s.pth' -> 'rvc\\pretraineds\\pretraineds_custom\\xavicanta_70e_350s.pth'

**Steps to Reproduce**
look at video 

https://github.com/IAHispano/Applio/assets/48472866/74542491-86d1-416d-86fc-68b301959620

**Expected Behavior**
Describe what you expected to happen.

**Assets**
I show a video

windows 10
Chrome
Version Applio 3.1.0

**Additional Context**
Any additional information that might be relevant to the issue.

**Comment by aitronssesin** [comment]
https://docs.applio.org/get-started/installation/
![image](https://github.com/IAHispano/Applio/assets/74368135/967112c0-a2aa-45c9-a08a-5ac8af960ce3)
