### ISSUE TITLE
[BUG] Recording Sounds High-Pitched

### ISSUE THREAD

**Issue by Virjoinga** [IAHispano/Applio#375]
**Bug Description**
Whenever I record my voice through record feature, the output is high-pitched (chipmunk).

**Steps to Reproduce**
Record your voice with the record button and then listen to the output.

**Expected Behavior**
Recording should sound normal.

**Assets**
https://github.com/IAHispano/Applio/assets/45245475/1d392a7f-751a-4f3f-8f5d-742101b358bc

**Desktop Details:**
- Operating System: Windows 10
- Browser: Firefox

**Additional Context**
I am recording my voice with a Blue Yeti microphone. This bug never happened on the last version I tried (3.0.0)

**Comment by blaise-tk** [comment]
Seems a Gradio problem in your PC. Try in another browser or open an issue in https://github.com/gradio-app/gradio/issues
