### ISSUE TITLE
[BUG] Interface crashing

### ISSUE THREAD

**Issue by MTGMAD** [IAHispano/Applio#376]
**Before You Report a Bug**
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

**Bug Description**
word count was just about 1200 words of the text I was changing to audio.  Gets all the way through the process then I get ERROR in the out put boxes.  I selected the output to be in .mp3 format.  This happens on any generation more then a couple hundred words for me consistently whether I cut and past the text in or upload a text file.  Then I get the ERROR on output, but some times it actually puts the output in the folder.  I included and image this is the error at the bottom of the terminal window.   FileNotFoundError: [Errno 2] No such file or directory: ' C : \ \App1io-3.1. 0\\assets \ \audios \ \tts_rvc_output. wav '

UPDATE - This happens every time I change the file format from .wav all others generate the error.

That directory structure is there not sure why it is \\ though between everything

**Steps to Reproduce**
SEE ABOVE
Outline the steps to replicate the issue:
4. Observe the error.

**Expected Behavior**
Describe what you expected to happen.

**Assets**
Include screenshots or videos if they can illustrate the issue.
![Screenshot 2024-03-31 075601](https://github.com/IAHispano/Applio/assets/14255934/68481ff0-3c8a-42f1-95a9-ce90214fd9c0)

**Desktop Details:**
- Operating System: [e.g., Windows 11]  Windows 11 Microsoft Edge
- Browser: [e.g., Chrome, Safari]

**Additional Context**
Any additional information that might be relevant to the issue.

**Comment by aitronssesin** [comment]
Fixed in Applio 3.1.1
