### ISSUE TITLE
Overtraining Threshold doesn't work properly

### ISSUE THREAD

**Issue by UberStorm** [IAHispano/Applio#381]
Hi again,
I'm reporting to you about this new bug I found.
Overtraining Threshold doesn't work properly. Instad of doing what it supposed to do (stop training if no improvement is detected after you set the epochs number), it stops the training when it reaches to the number you set.
For example, when you set the Overtraining Threshold to 100, it stops training when it reaches to the 100th epoch, even if there's an improvment in epoch #99.
![image](https://github.com/IAHispano/Applio/assets/147564504/a562e65f-dfe9-4cd8-aaf6-467e7952d102)

* I tested it with 4 different model trainings, so I'm sure it stops when it reaches the number of the Overtraining Threshold.

**Comment by blaise-tk** [comment]
right now the feature is still in beta (that's why isn't enabled by default) i never had your problem but we are going to improve the system for the next updates
