### ISSUE TITLE
[BUG] run-applio.sh fails to start

### ISSUE THREAD

**Issue by Dusky-dev** [IAHispano/Applio#385]
**Before You Report a Bug**
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

**Bug Description**
Please provide a clear and concise description of the bug.

Traceback (most recent call last):
File "/home/user/Applio/app.py", line 10, in <module>
from tabs.inference.inference import inference_tab
File "/home/user/Applio/tabs/inference/inference.py", line 8, in <module>
from core import (
File "/home/user/Applio/core.py", line 20, in <module>
from rvc.infer.infer import infer_pipeline
File "/home/user/Applio/rvc/infer/infer.py", line 14, in <module>
from rvc.infer.pipeline import VC
File "/home/user/Applio/rvc/infer/pipeline.py", line 17, in <module>
from rvc.lib.FCPEF0Predictor import FCPEF0Predictor
File "/home/user/Applio/rvc/lib/FCPEF0Predictor.py", line 18, in <module>
from local_attention import LocalAttention
ModuleNotFoundError: No module named 'local_attention' 

**Steps to Reproduce**
Outline the steps to replicate the issue:
1.  ./run-install.sh
2. ./run-applio.sh
3. outputs this

**Expected Behavior**
Describe what you expected to happen.

For the WebUI to start.

**Assets**
Include screenshots or videos if they can illustrate the issue.

![Screenshot_20240407_174825](https://github.com/IAHispano/Applio/assets/76793489/9995daf3-6c05-4616-b274-d43a6331f088)

**Desktop Details:**
Arch Linux

**Comment by blaise-tk** [comment]
arch may not be compatible with the actual installer, you should try to install the dependencies with a python env and then start the app.py file

**Comment by Dusky-dev** [comment]
> arch may not be compatible with the actual installer, you should try to install the dependencies with a python env and then start the app.py file

Thank you, looks like that solved it!
