### ISSUE TITLE
[BUG] UI: Unexpected behavior of "Advanced Settings" wrap

### ISSUE THREAD

**Issue by cjmaxik** [IAHispano/Applio#398]
**Bug Description**
"Clean Audio" and "Pitch extraction algorithm" controls close "Advanced Settings" wrap.

**Steps to Reproduce**
1. Go to 'Inference' tab
2. Click on 'Advanced Settings' to open the wrap
3. Click on 'Clean Audio' and 'Pitch extraction algorithm'
4. Observe the error.

**Expected Behavior**
"Advanced Settings" wrap should not close when clicking on the UI elements inside.

**Assets**
https://github.com/IAHispano/Applio/assets/1501705/1bfb68f5-cc1c-4125-a059-31a562182b90

**Desktop Details:**
- Windows 11
- Chrome v124

**Comment by aitronssesin** [comment]
It's an error from gradio we can't do nothing about it

**Comment by aitronssesin** [comment]
It's an error from gradio we can't do nothing about it
