### ISSUE TITLE
[BUG] "Hop-Length" has been removed since Applio 3.1.0

### ISSUE THREAD

**Issue by ingrid-z** [IAHispano/Applio#401]
**Before You Report a Bug**
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

**Bug Description**
"Hop-Length" has been removed from Extract menu.

**Steps to Reproduce**
Outline the steps to replicate the issue:
Run "run-applio.bat"  Applio 3.1.0 (included) and laters.

**Expected Behavior**
"Hop-Length" gone.

**Assets**
N/A

**Desktop Details:**
- Operating System: Windows 11 latest
- Browser: Firefox

**Additional Context**
I don't see any changes about removing "Hop-Length" from changes log since 3.1.0  .
So it's probably a bug?! I still see "Hop-Length" in offline colab's extract menu.

**Comment by blaise-tk** [comment]
No. just available for crepe and now rmvpe

**Comment by ingrid-z** [comment]
ugh...dear Blaise you sure it's available for rmvpe now?
![Screenshot 2024-04-26 at 01-10-42 Applio](https://github.com/IAHispano/Applio/assets/22465481/cfa534f5-8980-4ef1-8b0b-7db89b1e2523)

**Comment by blaise-tk** [comment]
was added some minutes ago, give us time to make a release 😅

**Comment by Castro15** [comment]
@blaise-tk was this removed?

**Comment by blaise-tk** [comment]
hop only for crepe.

**Comment by Castro15** [comment]
> hop only for crepe.

but why? I used it and it worked great when It was for rmvpe as well...

**Comment by blaise-tk** [comment]
the result is the same
