### ISSUE TITLE
Syncing graphs on tenosorboard

### ISSUE THREAD

**Issue by litsa-the-dancer** [IAHispano/Applio#405]
![graph sync](https://github.com/IAHispano/Applio/assets/140747431/cc527580-706f-4824-9cb2-b13de34005b9)
You can use this as a reference and turn into code for applio to properly have the graphs synced.
### All credits for the img guide go to codename btw.
Also another thing that isnt mentioned in the guide i showed u above is that u also need to change the config file thats also created once training starts for it to work like so:

https://github.com/IAHispano/Applio/assets/140747431/0920d13e-8b4e-402a-ac03-e9ec943a4c16

The config file in the vid should be in the logs folder of the model itself. it should be called config.json
Change it to what the log interval of each step is just like all the other config files as the guide suggests and all should be good.

Lastly, another comment regarding step 2. is that closing rvc or restarting it isnt necessary. I got it to work with just having the model train for an epoch, followed the rest of the steps and without closing it or refreshing the page so dont try to add a script like that since it'll work without restarting or closing applio altogether.
![step 2](https://github.com/IAHispano/Applio/assets/140747431/adf562e8-d38a-4ad4-bf55-99c966ca00df)

It isn't really necessary for casual users to set the saving frequency to 1 so dont force it upon them. It'll still log properly as it should.
Please do add this cuz it's important to have the logs and stuff auto optimized for proper ckpt evaluation and more accurate graphs overall.

**Comment by aitronssesin** [comment]
Added https://github.com/IAHispano/Applio/commit/601b5560f4e3ef0b82bb144eb6baba42cb1e1c64
