### ISSUE TITLE
[BUG][WinError 123] The filename, directory name, or volume label syntax is incorrect: 

### ISSUE THREAD

**Issue by druizadmin** [IAHispano/Applio#407]
**Bug Description**
When trying to train a model, I am getting the following error for the Dataset Path:

This is the error I get:
Starting preprocessing...
[WinError 267] The directory name is invalid: 'C:\\Users\\DARM\\Desktop\\12min.m4a'
Preprocessing completed!

I have changed the file location and the path with no avail.

**Desktop Details:**
I'm on Windows 11.

**Comment by aitronssesin** [comment]
You didn't follow the steps in: https://docs.applio.org/get-started/training (The audio needs to be in .wav format and you need to put the dataset folder path, not the dataset audio path)
