### ISSUE TITLE
[A pile of errors]Bro why am I getting all kinds of errors and I didn't find any solution😭😭😭

### ISSUE THREAD

**Issue by HHHongMou** [IAHispano/Applio#408]
![image](https://github.com/IAHispano/Applio/assets/127123297/4badc851-ce6d-4237-ad55-ee7892f70569)
![image](https://github.com/IAHispano/Applio/assets/127123297/40348baa-caba-44df-a0d2-c58821e98979)
![image](https://github.com/IAHispano/Applio/assets/127123297/915225d9-f1b8-4cff-8fff-bacef632f1f4)
![image](https://github.com/IAHispano/Applio/assets/127123297/887ea361-c641-498d-803b-03013b9bbe84)
![image](https://github.com/IAHispano/Applio/assets/127123297/c4c92902-5c61-4bd7-ad5d-6ae1be3d3f53)
![image](https://github.com/IAHispano/Applio/assets/127123297/68165c69-e827-446f-817b-beca44a7e2bc)
![image](https://github.com/IAHispano/Applio/assets/127123297/7d8ab041-c37c-4486-aa3f-b0888517b76b)
This is my first time using ai and python
I'm stupid, but I really want to try this thing. If it can't be solved, I think I can only give up...

**Comment by aitronssesin** [comment]
Only install applio on the C: drive and also what version of windows are you on (A version lower than 10 is not supported)?
![image](https://github.com/IAHispano/Applio/assets/74368135/9882001c-3aee-45af-9bd5-9cff168ae67a)

**Comment by HHHongMou** [comment]
I downloaded the compiled version directly,I am indeed on win 10

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio/assets/74368135/7c457a1c-61cc-4516-ba8d-7b075cb257d8)
This is on D: drive not on C: drive
