### ISSUE TITLE
Can't Applio run with Python3 3.11 ?

### ISSUE THREAD

**Issue by Duddy67** [IAHispano/Applio#412]
Hi,
I'm trying to install Applio on Debian 12 
```
chmod +x run-install.sh
./run-install.sh
```

But it says 

> Please install Python3 or 3.10 manually.

The thing is Python3 3.11 is already installed. 

Can't Applio run with Python3 3.11 ?
Should I have to downgrade to Python 3.10 ?

Thanks for your help.

**Comment by blaise-tk** [comment]
you can have both installed and do a manual installation with a python env
