### ISSUE TITLE
please explain how to run it command line with an example 

### ISSUE THREAD

**Issue by mishav78** [IAHispano/Applio#415]
?

**Comment by aitronssesin** [comment]
What do you mean exactly?

**Comment by aitronssesin** [comment]
If you want to run applio in the comand line we recommedn you ro use RVC_CLI the core of applio: https://github.com/blaise-tk/RVC_CLI all is explained in the README page

**Comment by juangea** [comment]
Hi there.

But in that case, the license is CC-attribution-non-commercial, so it cannot be used in any commercial project, am I right?

Unless there is a change in the license I mean.

**Comment by blaisewf** [comment]
should be updated to use MIT

**Comment by juangea** [comment]
It seems to be CC-By-NonCommercial yet, but if you tell me it's going to change I feel more comfortable using it :)
