### ISSUE TITLE
RuntimeError: main thread is not in main loop [BUG]

### ISSUE THREAD

**Issue by alvar036** [IAHispano/Applio#420]
Exception ignored in: <function Variable.del at 0x0000023F3B084430>
Traceback (most recent call last):
  File "C:\Users\J\Downloads\APPLIO\ApplioV3.1.1\env\lib\tkinter_init.py", line 363, in del_
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop

Not sure what to do about it, also training does continue after it.

Windows 11

**Comment by blaise-tk** [comment]
ignore it.
