### ISSUE TITLE
[BUG] Compiled 3.1.1 version missing JSON files and [log] when trying to create model

### ISSUE THREAD

**Issue by newtonsgroove** [IAHispano/Applio#422]
**Bug Description**
Compiled version missing JSON files when trying to create model.

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Open Applio
2. Select "Train"
3. Create a model name and select a dataset path
4. Select Preprocess dataset
5. Select Start Training
6. View results

**Expected Behavior**
Model is rendered and available in Applio

**Actual Results**
Messages  - "Failed to train model..."

Error Message:
Failed to train index: [WinError 3] The system cannot find the path specified: 'C:\\Applio310\\ApplioV3.1.0\\logs\\test\\3_feature768'
Traceback (most recent call last):
  File "C:\Applio310\ApplioV3.1.0\rvc\train\train.py", line 51, in <module>
    hps = get_hparams()
  File "C:\Applio310\ApplioV3.1.0\rvc\train\utils.py", line 198, in get_hparams
    with open(config_save_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Applio310\\ApplioV3.1.0\\logs\\test\\config.json'
Failed to train index: [WinError 3] The system cannot find the path specified: 'C:\\Applio310\\ApplioV3.1.0\\logs\\test\\3_feature768'
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Applio310\ApplioV3.1.0\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Applio310\ApplioV3.1.0\env\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Assets**
Include screenshots or videos if they can illustrate the issue.

**Desktop Details:**
- Operating System:  Windows 11
- Browser: Edge, Chrome

**Additional Context**
![Applio-311-compiled-error](https://github.com/IAHispano/Applio/assets/5579431/c1cfd932-8529-4ca9-bcb1-e218ec117684)
![Applio-311-compiled-error-3](https://github.com/IAHispano/Applio/assets/5579431/39a551b7-a073-4ad8-9f45-0880e3a582d9)
![Applio-311-compiled-error-2](https://github.com/IAHispano/Applio/assets/5579431/6b81f3c8-4061-4adf-b1da-8b7f87c5be35)

**Comment by aitronssesin** [comment]
You need to follow all the steps: https://docs.applio.org/get-started/training/

**Comment by newtonsgroove** [comment]
I followed all the steps: https://docs.applio.org/get-started/training/.  I am still getting the same error.  In Applio it says training is completed in about 5 seconds but the error still occurs and no model appears.  Any thoughts?
![image](https://github.com/IAHispano/Applio/assets/5579431/ac51310a-22f9-4a49-99b5-935e840ef871)
