### ISSUE TITLE
[BUG] Cannot apply model from download tab

### ISSUE THREAD

**Issue by rtap** [IAHispano/Applio#425]
[recording.webm](https://github.com/IAHispano/Applio/assets/169115651/dbb58a7f-4d92-4713-89b4-2b9f01bd9202)

**Comment by aitronssesin** [comment]
Some models have some issues because they haven't the right structure for the index or the pth file so the downloader breaks. Did you try with another model?

**Comment by rigeltap** [comment]
> Some models have some issues because they haven't the right structure for the index or the pth file so the downloader breaks. Did you try with another model?

I chose to download it and put it in the folder manually and it worked.

**Comment by rtap** [comment]
> Some models have some issues because they haven't the right structure for the index or the pth file so the downloader breaks. Did you try with another model?

I chose to download it and put it in the folder manually and it worked.

**Comment by aitronssesin** [comment]
I said that "the downloader breaks" if you put them manually it should work as you said, but did you try with another model in the downloader?
