### ISSUE TITLE
Connection Timeout Error  

### ISSUE THREAD

**Issue by Natzkulz** [IAHispano/Applio#426]
When I try to set certain settings or train a model, even recording the screen in the "report a bug" page, the "connection timeout" error pops up.

https://github.com/IAHispano/Applio/assets/169548913/d853cb1f-981e-4d3d-9b64-512b9c37693a

- Operating System: [Windows 11]
- Browser: [Chrome]

**Comment by blaise-tk** [comment]
tienes que mantener el cmd abierto, no solo la web
