### ISSUE TITLE
My microphone is bugged

### ISSUE THREAD

**Issue by SekaizaEarthza** [IAHispano/Applio#429]
**Bug Description**
When I start to record and sing, my microphone's volume automatically decrease

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Click microphone icon
2. Click Record
3. The microphone's volume automatically start to decrease

**Expected Behavior**
Recording's audio should sounds consistently loud, not start to get more quiet (If you look to waveform)

**Assets**
[Include screenshots or videos if they can illustrate the issue.](https://streamable.com/w5ri4o)

**Desktop Details:**
- Operating System: Windows 10
- Browser: Chrome

**Comment by aitronssesin** [comment]
We can't help you with gradio(the ui) errors but in the next applio release try again to see if it's fixed (we updated to the latest gradio version).
