### ISSUE TITLE
Importing others Microsoft Server Speech Text to Speech Voices

### ISSUE THREAD

**Issue by mrscatlover** [IAHispano/Applio#430]
Hello!
I am trying to add the new Microsoft pt-BR voices that are available on Microsoft since 01/02/2024 (this is the link for the voice list https://learn.microsoft.com/pt-br/azure/ai-services/speech-service/language-support?tabs=tts) but i am also showing the print of the voice list.
![Thevoices](https://github.com/IAHispano/Applio/assets/169812043/a5bf69d3-2bb1-4d84-b417-d53869f142a3)

I tried to add the voices on the file "tts_voices.json" 
Applio its working perfectly, no other file was edited besides "tts_voices.json"  and the only edition i made was the one circled in red as shown up in the picture
![Thefile](https://github.com/IAHispano/Applio/assets/169812043/c9299eab-a31a-4ce2-9e1a-cb558f03750e)

The voices do show up in Applio as in the picture  down bellow, i tried adding the "pt-BR-BrendaNeural"
![Theprogram](https://github.com/IAHispano/Applio/assets/169812043/305cbed1-0365-4a60-9d3e-81a8da787468)
But when generating the text to speech with the "pt-BR-BrendaNeural" it used the last voice i used (that is not a new voice, but a base voice that already comes with applio)

this is the entire log while doing so
![The error](https://github.com/IAHispano/Applio/assets/169812043/3c1645ef-f025-4240-ae3d-5e01512bfa71)

Can anyone help me on adding these new voices?

**Comment by mcpdigital** [comment]
Tried exactly the same steps, but it does not workl. I does nothing in fact when the new voices are chosen.

**Comment by mrscatlover** [comment]
**Please, someone help**

**Comment by blaise-tk** [comment]
Please refer to https://github.com/rany2/edge-tts
