### ISSUE TITLE
[BUG]  Compiled 3.1.1 version STILL missing JSON files and [log] when trying to create model

### ISSUE THREAD

**Issue by newtonsgroove** [IAHispano/Applio#435]
Bug Description
Compiled version missing JSON files when trying to create model.

Steps to Reproduce
Outline the steps to replicate the issue:

Open Applio - follow steps at https://docs.applio.org/get-started/training/

Actual Results
Messages - "Failed to train model..."

![image](https://github.com/IAHispano/Applio/assets/5579431/c9c570a4-8bd9-401b-b8ed-817f7f82bd4a)

**Comment by blaise-tk** [comment]
Move Applio to a non-privileged repository (downloads, desktop...) and verify your dataset

**Comment by newtonsgroove** [comment]
I've moved to desktop and Downloads trying the compiled version.  I have the exact same issue.  Tried with .2.0 and 3.1.1

**Comment by newtonsgroove** [comment]
FIXED (sort of).  Running from Downloads folder (not ideal but functional), Extracted all features before starting training.

Any chance to get this installed as a regular program that runs on the C drive?

**Comment by aitronssesin** [comment]
I see you misunderstood a few things:
1. You need to complete all the steps (Preprocess and Extract) before starting the training process.
2. Applio is written in Python and cannot be compiled into a standalone program.
