### ISSUE TITLE
IT's running on Chrome and not able toopen needed apps and also not using proper GPU [BUG]

### ISSUE THREAD

**Issue by Ashwin-raj21** [IAHispano/Applio#437]
**Before You Report a Bug**
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

**Bug Description**
Please provide a clear and concise description of the bug.

**Steps to Reproduce**
Outline the steps to replicate the issue:
4. Observe the error.

**Expected Behavior**
Describe what you expected to happen.

**Assets**
Include screenshots or videos if they can illustrate the issue.

**Desktop Details:**
- Operating System: [e.g., Windows 11]
- Browser: [e.g., Chrome, Safari]

**Additional Context**
Any additional information that might be relevant to the issue.

**Comment by aitronssesin** [comment]
Please open a new issue and fill the bug report properly

```
Before You Report a Bug
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

Bug Description
Please provide a clear and concise description of the bug.

Steps to Reproduce
Outline the steps to replicate the issue:

Go to '...'
Click on '....'
Scroll down to '....'
Observe the error.
Expected Behavior
Describe what you expected to happen.

Assets
Include screenshots or videos if they can illustrate the issue.

Desktop Details:

Operating System: [e.g., Windows 11]
Browser: [e.g., Chrome, Safari]
Additional Context
Any additional information that might be relevant to the issue.
```
