### ISSUE TITLE
[BUG] Slow RMVPE pitch extraction on Linux vs Windows

### ISSUE THREAD

**Issue by tomakorea** [IAHispano/Applio#446]
I'm using Applio 3.2.0 but this behavior was there on previous versions too. I tested on both Windows 11 and Ubuntu with the same hardware, for pitch extraction, Windows is much faster for doing the RMVPE pitch extraction process before starting the training. For example, on a large dataset, I gave up after 4 hours of pitch extraction on Linux on an i7 8700k, while windows did it in about 6 to 10 minutes. However, usually training is a bit faster on Linux, maybe because of the windows overhead.

**Steps to Reproduce**
1. Go to Train tab
2. Do the pre-process
3. Let RMVPE / Hubert selected
4. Click on Extract Features

**Expected Behavior**
I expected to take the same amount of time as on Windows. Also, it's not really convenient to switch OS to do only this job since the filelist.txt has all the audio files path, so it means it's necessary to edit this file and replace all the path if switching OS are necessary to save time.

**Desktop Details:**
- CPU i7 8700k
- Windows 11
- Ubuntu latest version
- Python 3.10.12 (on Linux)
- RTX 3090
- 32Gb DDR4 ram
- NVME drive

**Comment by Mojobones** [comment]
I was seeing this same issue whenever I tried to run Applio on Paperspace machines which use Linux. The feature extraction is slow to the point of being unusable.

**Comment by tomakorea** [comment]
So I was considering using the main RVC branch for that pre-process which is super fast using RMVPE GPU but I'm not 100% sure it's compatible with Applio...

**Comment by aitronssesin** [comment]
We added the feature to set the custom cores you want to use  in pitch extraction try a higher value.
Commit: https://github.com/IAHispano/Applio/commit/5e302727f2b844e33503afb6cdba3a1945c76527

**Comment by Mojobones** [comment]
> But the normal rmvpe(not rmvpe gpu) it's also slow in the main branch?

Would it be possible to add RMVPE GPU for Applio in that case?
