### ISSUE TITLE
Suggestion : Cache Dataset in VRAM suggestion (for high end GPUs)

### ISSUE THREAD

**Issue by tomakorea** [IAHispano/Applio#447]
Because the batch size should be kept low at 4 or 8, the high end consumer GPUs with 16 or 24gb of VRAM are under-utilized. It could be great to find a usage for the large amount of Vram that is left-over, like main RVC branch using it for caching dataset.
From what I understand, pushing the batch size at 16 or 24 (even for large datasets of 1 hour) isn't recommended, so it could be nice to find usage of this Vram.

**Desktop Details:**
- CPU i7 8700k
- Windows 11 (pre-compiled Applio 3.2.0)
- Ubuntu latest version
- Python 3.10.12 (on Linux)
- RTX 3090
- 32Gb DDR4 ram
- NVME drive

**Comment by aitronssesin** [comment]
Added https://github.com/IAHispano/Applio/commit/5e302727f2b844e33503afb6cdba3a1945c76527
