### ISSUE TITLE
[BUG] Audio upscaler causing the audio to be buggy

### ISSUE THREAD

**Issue by ShiromiyaG** [IAHispano/Applio#455]
**Bug Description**
Audio Upscaler causes the audio to have muted parts where it was supposed to have audio and parts where it was supposed to have audio, muted (Sorry, I don't know how to explain it properly)

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Select the audio upscale option

**Expected Behavior**
Audio inference will be made without messing up the audio timing

**Assets**
Photo of the audio, before and after inference with upscale
![Applio-Upscaler](https://github.com/IAHispano/Applio/assets/86894155/bc7bbb3b-21ce-4fc3-9b81-8fec1316988e)

**Desktop Details:**
- Operating System: Windows 11
- Browser: Microsoft Edge

**Comment by blaise-tk** [comment]
That's because we slice your audio to upscale it, and then we reconstruct, may not be super precise. If your audio is a singing audio, don't use it
