### ISSUE TITLE
[BUG]: TTS speed can't be a float, but interface enables to

### ISSUE THREAD

**Issue by jramosss** [IAHispano/Applio#460]
**Before You Report a Bug**
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

**Bug Description**
TTS speed slider enables speed to be an integer, but the white box at the top enables the user to write any number, even 0.8, then it crashes

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Go to TTS
2: Write any float number in the white box regarding tts speed
3: See the error in the console 
Applio/rvc/lib/tools/tts.py", line 9, in main
    rate = int(sys.argv[3])
ValueError: invalid literal for int() with base 10: '0.8'

**Expected Behavior**
To not be enabled to insert any float

**Assets**
Include screenshots or videos if they can illustrate the issue.

**Desktop Details:**
- Operating System: macos 14.5
- Browser: Chrome

**Additional Context**
Any additional information that might be relevant to the issue.

**Comment by blaise-tk** [comment]
put an int number
