### ISSUE TITLE
Pth created but error. Cannot create index

### ISSUE THREAD

**Issue by Maitresinh** [IAHispano/Applio#461]
**Bug Description**
I'm traning a voice with 500 epoch. Everything seems fine, but then the webpage show "error" message.
And i cannot create the index.

**Expected Behavior**
No error message. Index can be created

**Assets**

Here is the final message log.
![Capture d’écran 2024-06-06 142015](https://github.com/IAHispano/Applio/assets/37817197/ffadb410-1817-4bce-a924-4434421ca91a)

**Desktop Details:**
- Operating System: Windows 11 VM on unraid
- Browser: default (explorer)

**Additional Context**
I would need to know how i can create the index with the pth file, without starting all over.

**Comment by Maitresinh** [comment]
More information 
![Capture d’écran 2024-06-06 164329](https://github.com/IAHispano/Applio/assets/37817197/7fe19937-12bb-4593-8e0b-6a77fe567998)

The pth file is present. but the last one (epoch 500) is only 1k

So do y have to start over, or can i create the index with the pth file ?
And how to avoid this error ?

**Comment by Maitresinh** [comment]
I could reboot my unraid server and the pth file appeared in the frontpage as a possible choice in the "export" area. I did a click on "create index", and it seems to work.

But i've tried and inference with this pth and index, and there is no change in the voice. So it seems my index is bad....

**Comment by blaise-tk** [comment]
With the same name of the model, (set the name on the first step) and clicking the Index gen button, you can generate another index file
