### ISSUE TITLE
[BUG] can't invoke "event" command: application has been destroyed   

### ISSUE THREAD

**Issue by Maitresinh** [IAHispano/Applio#464]
**Bug Description**
Training a model. Everything was final until "train model"

```
can't invoke "event" command: application has been destroyed
    while executing
"event generate $w <<ThemeChanged>>"
    (procedure "ttk::ThemeChanged" line 6)
    invoked from within
"ttk::ThemeChanged"
```

**Steps to Reproduce**
Outline the steps to replicate the issue:
 
Using a 29 minutes wav clean file.
Preprocessing ok. 
Launching traning. It starts but then stop with an error.

**Desktop Details:**
- Operating System:, Windows 11 on unraid

**Additional Context**

Last version of Applio, precompiled

**Comment by Maitresinh** [comment]
I did not have the problem since then. But if it shows on, i will let you know.

**Comment by j0708** [comment]
i have this problem to, it's realy annoying!
