### ISSUE TITLE
Question: What kinda vits model does Applio use

### ISSUE THREAD

**Issue by mantrakp04** [IAHispano/Applio#471]
I was curious bout the architecture n the pipeline, if someone could summarize it for me id be grateful. I couldn't find what kinda vits model was being used

**Comment by blaise-tk** [comment]
we don't use pretrained models from vits

**Comment by mantrakp04** [comment]
hmm then which models does the ui use for base tts

**Comment by blaise-tk** [comment]
Edge TTS makes the audio and then we convert with Applio
