### ISSUE TITLE
[Feature request] Please provide XTTS V2 as an option for TTS.

### ISSUE THREAD

**Issue by StellarBeing25** [IAHispano/Applio#472]
I just tried the upcoming beta version of AllTalk TTS V2, which uses XTTS V2 as the TTS model to generate voice before passing it through RVC, and it sounded way more natural as compared to Edge TTS. It would be great if XTTS V2 was also an option in Applio, along with Edge TTS, allowing users to choose between the two TTS options depending upon the use case and system resources available.

**Comment by mikhail2013ru** [comment]
I join the request! We ask Blaise, Aitron to implement synthesis with a third-party tts.

**Comment by supertacomx** [comment]
Agree!

**Comment by blaisewf** [comment]
If you want a specific TTS, just use the TTS, Applio is not designed for TTS purposes, the current integration is more like a demo

**Comment by cryptotester** [comment]
> If you want a specific TTS, just use the TTS, Applio is not designed for TTS purposes, the current integration is more like a demo

I just discovered this project and... what do you mean it's more like a demo? I was specifically trying to find a program where I could use models downloaded from voice-models.com, and to generate text to speech using such already trained models. The only one I've found that is close to what I need is Applio.

Are there alternatives to applio, to run locally?

Applio looks promising and I would definitely use to generate audio for youtube videos, or simply to narrate a story or an e-book with my favorite narrator voice, should I not use applio for this? I mean I can code, I can imagine that for a long text I'd need to write my own script/logic to split long text in smaller chuncks, then combine all in a long audio?

**Comment by supertacomx** [comment]
> > If you want a specific TTS, just use the TTS, Applio is not designed for TTS purposes, the current integration is more like a demo
> 
> I just discovered this project and... what do you mean it's more like a demo? I was specifically trying to find a program where I could use RVC models downloaded from voice-models.com, and to easily generate text to speech using such already trained models. The only one I've found that is close to what I need is Applio.
> 
> Are there alternatives to applio, to run locally?
> 
> Applio looks promising and I would definitely use to generate audio for youtube videos, or simply to narrate a story or an e-book with my favorite narrator voice, should I not use applio for this? I mean I can code, I can imagine that for a long text I'd need to write my own script/logic to split long text in smaller chuncks, then combine all in a long audio?

Hi friend. That's exactly what i was saying. This proyect its very good and amazing, and it has very good TTS. Except for the 3200 character limit. But i don't know how to code. Can you make a branch with your idea? I'm sorry if i'm asking too much. Thats only that there's not another good "FREE" option for working locally. Just paid. 

Thank yo so much Cryptotester!

**Comment by blaisewf** [comment]
> > If you want a specific TTS, just use the TTS, Applio is not designed for TTS purposes, the current integration is more like a demo
> 
> I just discovered this project and... what do you mean it's more like a demo? I was specifically trying to find a program where I could use RVC models downloaded from voice-models.com, and to easily generate text to speech using such already trained models. The only one I've found that is close to what I need is Applio.
> 
> Are there alternatives to applio, to run locally?
> 
> Applio looks promising and I would definitely use to generate audio for youtube videos, or simply to narrate a story or an e-book with my favorite narrator voice, should I not use applio for this? I mean I can code, I can imagine that for a long text I'd need to write my own script/logic to split long text in smaller chuncks, then combine all in a long audio?

The TTS is a simple integration, just to do an easy and fast showcase of the potential of the technology. For a deeper solution, just use a TTS

**Comment by supertacomx** [comment]
> > > If you want a specific TTS, just use the TTS, Applio is not designed for TTS purposes, the current integration is more like a demo
> > 
> > 
> > I just discovered this project and... what do you mean it's more like a demo? I was specifically trying to find a program where I could use RVC models downloaded from voice-models.com, and to easily generate text to speech using such already trained models. The only one I've found that is close to what I need is Applio.
> > Are there alternatives to applio, to run locally?
> > Applio looks promising and I would definitely use to generate audio for youtube videos, or simply to narrate a story or an e-book with my favorite narrator voice, should I not use applio for this? I mean I can code, I can imagine that for a long text I'd need to write my own script/logic to split long text in smaller chuncks, then combine all in a long audio?
> 
> The TTS is a simple integration, just to do an easy and fast showcase of the potential of the technology. For a deeper solution, just use a TTS

Which one? A free one?

**Comment by blaisewf** [comment]
https://github.com/topics/tts
