### ISSUE TITLE
[BUG] Problem with ApplioV3.2.1

### ISSUE THREAD

**Issue by testermax90** [IAHispano/Applio#474]
Problem with ApplioV3.2.1
When you output the sound, it sounds just awful, as if I have a broken model, but with ApplioV3.1.1 or ApplioV3.1.0. I don’t remember exactly, there were no such problems and the sound quality seemed to be better than the original RVC.

**Comment by blaise-tk** [comment]
Train the model again and ensure that your logs folder contains files

**Comment by testermax90** [comment]
Returning to ApplioV3.1.1 my model works again, therefore the problem is in ApplioV3.2.1
