### ISSUE TITLE
[Feature Request] Save lowest value epoch when training

### ISSUE THREAD

**Issue by YTadF** [IAHispano/Applio#476]
Applio already states the lowest value epoch when training so why not save that epoch. It would save time on finding a good epoch to use while also saving space so you don't need to have a wildly low "Save Every Epoch" number to catch these low value epochs.

To prevent saving unwanted epochs in the beginning of training, it could start saving the lowest value epoch after passing a predetermined epoch.

**Comment by todd-ao** [comment]
I second this request. I noticed that the lowest value that Applio shows in the Terminal prompt, is not the same as the total_loss in Tensorboard. I wonder which of both should be the most accurate lowest value?
