### ISSUE TITLE
Use TTS with no RVC

### ISSUE THREAD

**Issue by ddcorazon** [IAHispano/Applio#481]
Hi everyone, I hope you're doing well and thank you for your excellent work.
Sorry for any possible mistakes, I'm using Google Translate since English is not my native language.

I was wondering if it was possible to use the default TTS without generating an RVC audio. To explain a bit more, in some cases (in French), I prefer the default fr-FR-HenriNeural voice over using a custom model. I was wondering if it was possible to just use the neural voice and keep things simple. What I currently do is set a custom voice, run the conversion, then go to the folder to retrieve the basic TTS audio, but this takes a bit more time, and the conversion process is long (assuming it first converts to the default TTS voice and then to the custom input model). However, I only need the basic voice and don't need to use a custom model.

**Comment by blaisewf** [comment]
You can use any Edge TTS implementation
