### ISSUE TITLE
[BUG] Very Short characters limit

### ISSUE THREAD

**Issue by supertacomx** [IAHispano/Applio#486]
When i try to use TTS to convert a ebook in a audiobook i've got this error

FileNotFoundError: [WinError 206] El nombre del archivo o la extensión es demasiado largo

says that the filename is too long. I've checked on regedit the filenames long enabled and its true. So, i think that the problem is the character limit on the windows console (cmd). Its too short. Can this be sorted on any way? Can i use powershell? its better? I think the limit its around 30k characters, which its too small. It's not even 1 chapter.

**Comment by blaisewf** [comment]
https://stackoverflow.com/questions/72352528/how-to-fix-winerror-206-the-filename-or-extension-is-too-long-error

**Comment by supertacomx** [comment]
Thanks, but that's not even close to solve the problem. I've already done the steps on the link. It wasn't necessary, i had it enabled already. This software its great, but i'm going to need to split the project on 64 files and then join them together because i can only process 32k characters every time.
