### ISSUE TITLE
[Feature Request] RMVPE GPU

### ISSUE THREAD

**Issue by shirounanashi** [IAHispano/Applio#487]
It really takes a long time to train on Applio, not the training part, but the Extract Features part, precisely because of the lack of RMVPE GPU. Training pretrain models then, only after hours of waiting for the extract feature. I really hope it's added before or along with Applio's RVC v3

**Comment by Mixomo** [comment]
+1 

Almost cause a BSOD because cannot change the numbers of threads of the CPU anymore lol

**Comment by blaisewf** [comment]
you can change it

**Comment by shirounanashi** [comment]
@blaisewf I'd love to help, but I'm not good at programming lol

**Comment by AznamirWoW** [comment]
Extract F0 is done on CPU by some reason.

    def get_rmvpe(self, x):
        model_rmvpe = RMVPE0Predictor(
            os.path.join("rvc", "models", "predictors", "rmvpe.pt"),
            is_half=False,
            **device="cpu",**
        )
        return model_rmvpe.infer_from_audio(x, thred=0.03)

Extract Feaure runs mostly on GPU.

**Comment by blaisewf** [comment]
Done
