### ISSUE TITLE
[BUG] Applio v3.2.1 keeps re-download chinese-hubert-large and training is bugged

### ISSUE THREAD

**Issue by ingrid-z** [IAHispano/Applio#489]
**Before You Report a Bug**
Reporting a bug is essential for us to improve our service, but we need detailed information to address the issue effectively. Since every computer setup is unique, there can be various reasons behind a bug. Before reporting, consider potential causes and provide as much detail as possible to help us understand the problem.

**Bug Description**
1. Applio keeps re-download chinese-hubert-large when extracting even already downloaded in embedders folder.
   Devs should also check japanese-hubert-base.
2. use Embedder Model chinese-hubert-large to train is bugged, training time is blazing fast 1epoch/1sec, it's abnormal.

**Steps to Reproduce**
Outline the steps to replicate the issue:
N/A

**Expected Behavior**
1. Applio should detect chinese-hubert-large.pt in folder and skip executing download the same file again.
2. Training normally should be slow, like 1epoch/1min on my machine.

**Assets**
N/A

**Desktop Details:**
- Operating System: Windows 11
- Browser: Firefox

**Additional Context**
N/A

**Comment by imyellow** [comment]
At the same time, the index file cannot be saved. Considering the training speed, the training should not be completed.

**Comment by hpx502766238** [comment]
for 
https://github.com/hpx502766238/Applio/blob/da705bec26e966d66de25f40a719c0a2babea554/rvc/lib/utils.py
#####################
        if embedder_model in online_embedders:
            model_path = embedding_list[embedder_model]
            url = online_embedders[embedder_model]
            print(f"\nDownloading {url} to {model_path}...")
            wget.download(url, out=model_path)
#####################
change to ：
        if embedder_model in online_embedders:  # 如果 embedder_model 在在线模型列表
            if not os.path.exists(model_path):  # 检查模型文件是否已经存在于指定路径
                url = online_embedders[embedder_model]
                print(f"\nDownloading {url} to {model_path}...")
                wget.download(url, out=model_path)  # 开始下载
        else:
            model_path = embedding_list["contentvec"]

**Comment by hpx502766238** [comment]
I also met a training problem with  chinese-hubert-large in v3.2.2,But the error message is "An error occurred processing xxx.wav: "LayerNormKernelImpl" not implemented for 'Half'"
