### ISSUE TITLE
[BUG] Pip update in Makefile causes installation to fail on Linux (24.0 downgrade fixes) 

### ISSUE THREAD

**Issue by Mojobones** [IAHispano/Applio#501]
In the makefile there's a line of  "pip install --upgrade pip"

This causes "make run-install" to fail as Pip will update itself further than is compatible with Fairseq and omegaconf.

Replacing this line with "pip install pip==24.0" ensures that the installation works, as it reverts pip to a compatible version.

Not necessarily proposing using that specific version, but more reporting there's an issue installing with the makefile, and downgrading the pip version seems to fix it.

**Comment by blaisewf** [comment]
feel free to open a pr

**Comment by Mojobones** [comment]
> feel free to open a pr

https://github.com/IAHispano/Applio/pull/502
