### ISSUE TITLE
Noise problems with default settings

### ISSUE THREAD

**Issue by shirounanashi** [IAHispano/Applio#530]
**Problem Description**
It may seem like a silly thing, but Applio's default settings generate more noise than WebUI's default settings. I thought the problem was with my models until I realized this. And I have a suggestion to solve this problem, create presets for the inference settings, so that people who don't know what each configuration does don't get lost, or just change the default settings, I don't know why you guys chose these settings as default, but at least for music, they're not that good

**Assets**
[audios.zip](https://github.com/user-attachments/files/16457347/audios.zip)

**Comment by blaisewf** [comment]
each case is different, settings are there to be adjusted, for you maybe are not optimal, for other maybe are
