### ISSUE TITLE
[DOUBT] What is the difference between models G & D?

### ISSUE THREAD

**Issue by ZeroCool22** [IAHispano/Applio#536]
What is the difference between models **G** & **D**?

![Screenshot_8](https://github.com/user-attachments/assets/bd364eca-b0e8-4f07-9518-04df14a5ef4e)

**Comment by blaisewf** [comment]
on inference only use the non G and D. G means generator and D discriminator, are used to resume your training

**Comment by ZeroCool22** [comment]
> on inference only use the non G and D. G means generator and D discriminator, are used to resume your training

Thx.
