### ISSUE TITLE
[BUG] Trainin data gets randomly corrupted after 8+ hours of training

### ISSUE THREAD

**Issue by AznamirWoW** [IAHispano/Applio#538]
Most visible symptom is NaN values in tendorboard chart

![image](https://github.com/user-attachments/assets/cea288d2-610c-47ff-9394-9ed749ed87b8)

If you use 'Save only Latest' option for weighs, they get irrecoverable corrupted as latest saved D/G .pth files contain mostly NaN values. This has happened 2 out of 3 attemps to train large enough data sets and different custom pretrained models.

Attempt 1: 300 epochs x 110s/epoch, successfully completed after 5h:30m
Attempt 2: 300 epochs x 129s/epoch, failed somewhere between 140e-150e after ~9+ hours
Attempt 3: 300 epochs x 216s/epoch, failed somewhere between 120e-130e after ~11+ hours

Using 3.2.1/3.2.2 with Zluda patch and pyTorch 2.1.1-cu118

Training settings:
![image](https://github.com/user-attachments/assets/ad89a991-5c85-47a9-b6ca-181cdd56b39a)

**Comment by blaisewf** [comment]
Unable to replicate the error
