### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by flavioroberio** [IAHispano/Applio#540]
Não foi possível encontrar o Discord instalado e em execução nesta máquina.
Iniciando o servidor Flask

Starting Flask server
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.

Python
C:\Applio\ApplioV3.2.2\env\lib\site-packages\torch\cuda\__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 6050). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
 * Serving Flask app 'routes'
 * Debug mode: off
2024-08-04 12:13:30 | INFO | werkzeug | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:8000
2024-08-04 12:13:30 | INFO | werkzeug | Press CTRL+C to quit

**Comment by blaisewf** [comment]
read the message, you literally have the solution there
