### ISSUE TITLE
[BUG]problems with pitch in rvc recordings

### ISSUE THREAD

**Issue by mikhail2013ru** [IAHispano/Applio#541]
I have problems with pitch in rvc recordings. The speech on the recording sometimes sounds too high, which leads to sound distortion.. Is it possible to fix this?

**Comment by blaisewf** [comment]
open an issue on gradio if it persists, but check your microphone configs in the browser

**Comment by mikhail2013ru** [comment]
I use the tts tool, what does the microphone have to do with it? On recordings, the pitch changes, and it can be excessively high. Do I need an example? Where should I send the recording?
