### ISSUE TITLE
two tracks to the tts 

### ISSUE THREAD

**Issue by mikhail2013ru** [IAHispano/Applio#542]
Can you add two tracks to the tts recording of tts and rvc? And also suggest choosing the path to download the file?

**Comment by blaisewf** [comment]
two tracks?

**Comment by mikhail2013ru** [comment]
Yes, when I select the tts model and rvc for processing, I click the envelope and get only the rvc track. I would like to download the second track and tts too. Can this be added to the web interface?

**Comment by blaisewf** [comment]
not planned

**Comment by mikhail2013ru** [comment]
Is it possible to add a new track when generating rvc in tts synthesis, rather than overwriting the old one every time?

**Comment by blaisewf** [comment]
in the advanced settings you can change the path
