### ISSUE TITLE
An error occurred processing xxx.wav: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by hpx502766238** [IAHispano/Applio#546]
**Applio->train->preprocess->extract(choose model "chinese-hubert-large"),click "extract features"**
**Error occured while doing Feature extraction using "chinese-hubert-large" embedding model.**
......
An error occurred processing 6_8.wav: "LayerNormKernelImpl" not implemented for 'Half'
An error occurred processing 6_9.wav: "LayerNormKernelImpl" not implemented for 'Half'
100%|███████████████████████████████████████████████████████████████████████████████| 363/363 [00:00<00:00, 406.72it/s]
Feature extraction completed in 7.30 seconds.

**Comment by blaisewf** [comment]
try with contentvec

**Comment by hpx502766238** [comment]
> try with contentvec

Contentvec worked fine,but I want to use chinese-hubert-large to get better result.

**Comment by blaisewf** [comment]
changed to hubert base instead of large, should be fine now
