### ISSUE TITLE
There was a problem with model training.

### ISSUE THREAD

**Issue by kbuwel** [IAHispano/Applio#549]
My system is using rtx3060oc 12gb gpu and cpu is using 5600x 32gb ram.
There was no problem until preprocessing and feature extraction.
I selected custom pretrained model in advanced settings.
I selected Save Only Latest.
I unchecked all weight saving.
I entered Total Epoch as 600.
I started training.
The following error message was output.
f"Stopping training due to possible overtraining. Lowest generator loss: {lowest_value["value"]} at epoch {lowest_value["epoch"]}, step {lowest_value["step"]}"
SyntaxError: f-string: unmatched '['
Saved index file 'C:\Users\Administrator\Applio\logs\abc\added_abc_v2.index'
How to solve the problem?

**Comment by blaisewf** [comment]
run the release version, please
