### ISSUE TITLE
I have error when i using hybrid.

### ISSUE THREAD

**Issue by kasrahacker** [IAHispano/Applio#557]
When I use hybrid I have this error:

Calculating f0 pitch estimations for methods ["rmvpe', fcpe'] An error occurred during audio conversion: _init_() got an unexpected keyword argument 'sample_rate Traceback (most recent call :last) File "C:\Voice_AI\Applio_Rvc\rvc\i nfer\infer.py", line 256, in convert_audio audio_opt = )self.vc.pipeline File "C:\Voice_Al\Applio_Rvc\rvc\i nfer\pipeline.py", line 585, in pipeline )pitch, pitchf = self.get_f0 File "C:\Voice_Al\Applio_Rvc\ryc\i nfer\pipeline.py", line 351, in get_f0 )f0 = self.get_f0_hybrid File C:|Voice_Al\Applio_Rvc\rvc\i nfer\pipeline.py", line 274, in get_f0_hybrid self.model_fcpe = )FCPEFOPredictor TypeError: __init_() got an unexpected keyword argument 'sample_rate###

**Comment by blaisewf** [comment]
duplicated, fixed in next update
