### ISSUE TITLE
[BUG]Unable to open Gradio on PaperSpace

### ISSUE THREAD

**Issue by BibouOnAir** [IAHispano/Applio#561]
Unable to open Gradio on PaperSpace

After installing Applio, the URL does not respond

I have tried the installation several times on different machines, still the same problem

I am stuck, what should I do?

`An error occurred connecting to Discord: Could not find Discord installed and running on this machine.
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969
Running on public URL: https://a45a4b1d0bd96d2947.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
`

**Comment by blaisewf** [comment]
make sure paperspace is not restricted from using gradio
