### ISSUE TITLE
[BUG] ELEVENLAB

### ISSUE THREAD

**Issue by Aled40** [IAHispano/Applio#573]
**Before You Report a Bug**
When trying to convert, a repetitive error occurs

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Go to 'plugins.'
2. Click on 'elevenlabs' 3. Scroll down to 'convert.'
4. Observe the error.
**Expected Behavior**

[recording (1).webm](https://github.com/user-attachments/assets/47a91c20-c2d8-4e06-85b7-cae02b1fe393)

**Desktop Details:**
- Operating System: Windows 11]
- Browser:Chrome,

**Comment by Aled40** [comment]
[Uploading recording (1).webm…]()

**Comment by blaisewf** [comment]
fixed
