### ISSUE TITLE
Refresh in Inference is not working

### ISSUE THREAD

**Issue by blartw** [IAHispano/Applio#575]
Hello, 
My models have not been showing up in the "Inference" tab, but have been downloading successfully in the "Download" tab.

I have not had this issue until recently and I was wondering if there was anything I could do to fix this. I do not know how to code this efficiently by the way. Thank you. 

I am using Microsoft Edge within a Windows 11 operating system (PC).
[recording.webm](https://github.com/user-attachments/assets/f7c97fb1-da1d-4a09-8208-0edb7e26cbb2)

**Comment by blaisewf** [comment]
unable to reproduce, and no more reports, please try to upload the models manually and check if the model that you are downloading is correct
