### ISSUE TITLE
[BUG][WinError 267]Wrong folder path when training

### ISSUE THREAD

**Issue by 1manfactory** [IAHispano/Applio#577]
![image](https://github.com/user-attachments/assets/2912438f-683c-4a0d-adc1-db2ccae1fd95)

![image](https://github.com/user-attachments/assets/ac7b0e52-536e-46a6-af28-cfa7b6a96e19)

![image](https://github.com/user-attachments/assets/a1b990f3-469b-442f-8667-6b0c8e2a935b)

Windows 11 Pro, 64 BIT

Applio 3.2.2

**Comment by blaisewf** [comment]
you have to put the dataset path, not the audio path

**Comment by 1manfactory** [comment]
Damn. Stupid me.
Thanks, will check it out.

**Comment by 1manfactory** [comment]
Now I got this error
![image](https://github.com/user-attachments/assets/79d9c9ed-4824-4579-91f0-2d7411590cec)

**Comment by blaisewf** [comment]
use wav files

**Comment by 1manfactory** [comment]
Ok.
Now something has been (succesfully?) generated.

Bute when I use interference I got new errors on the command line

> To create a public link, set `share=True` in `launch()`.
> c:\Applio\env\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
>   warnings.warn(
> 2024-08-18 16:25:02 | INFO | faiss.loader | Loading faiss with AVX2 support.
> 2024-08-18 16:25:02 | INFO | faiss.loader | Could not load library with AVX2 support due to:
> ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
> 2024-08-18 16:25:02 | INFO | faiss.loader | Loading faiss.
> 2024-08-18 16:25:02 | INFO | faiss.loader | Successfully loaded faiss.
> Converting audio 'assets\audios\merged_generated_20240818_160229_92af6a0a-42f6-4caf-8195-234a4ce5560e.wav'...
> Conversion completed at 'assets\audios\merged_generated_20240818_160229_92af6a0a-42f6-4caf-8195-234a4ce5560e_output.wav' in 5.16 seconds.

Is this an error or not?

**Comment by blaisewf** [comment]
i don’t see any error

**Comment by 1manfactory** [comment]
2024-08-18 16:25:02 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")

**Comment by blaisewf** [comment]
thats not an error

**Comment by 1manfactory** [comment]
If it's not an error why is it called one?

**Comment by blaisewf** [comment]
just a warning, ignore it
