### ISSUE TITLE
[FEATURE REQUEST] Let me decide if I want RVC to automatically cut the audios of the dataset in the preprocessing stage

### ISSUE THREAD

**Issue by Mixomo** [IAHispano/Applio#578]
Hello!

It would be very useful if the automatic trimming of the audios could be omitted in the preprocessing stage of the dataset, since there are many cases in which one has several audios cut perfectly in spoken or sung phrases and RVC trims in a bad way those audios, causing zero-second audios with noises or parts of the phrases cut, causing errors in the f0 extraction stage (bc no f0 to extract from zero seconds audios lol) and leading to a bad training.

Thanks!

**Comment by blaisewf** [comment]
done

**Comment by Mixomo** [comment]
Thank you for implementing my suggestion. It works but not 100%, it looks like RVC wants to keep cutting the audios anyway. The numbers of audio segments remain the same as the original directory, but it looks like they were cut anyway at the beginning and/or end abruptly, (making audios with near zero seconds duration) plus the audios are out of order and there are audios that differ from their original length as state above. 

Thank you for your effort.

**Comment by blaisewf** [comment]
@ShiromiyaG maybe can help you

**Comment by ShiromiyaG** [comment]
@Mixomo Can you join the AIHispano discord server and call me to help me test this function? I'm @ShirouG there
