### ISSUE TITLE
[BUG] Epoch Only Saved at the End of Training in Google Colab (UI) (v3.2.3)

### ISSUE THREAD

**Issue by Ooooool** [IAHispano/Applio#587]
**Bug Description**
In the Google Colab (UI), the epoch is only saved when the training is complete. While G and D are saved at each step, the epoch is only saved at the end of the training. (version 3.2.3)

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Settings → fp32
2. Download Model → KLM4.1 48k
3. Train → Advanced Setings → 'Save Every Weights', 'Pretrained', 'Custom Pretrained', 'Cache Dataset in GPU'
4. Batch Size 16, Save Every Epoch 100, KLM4.1 G&D
5. Start Training

**Additional Context**
Issue occurrence: 12 hours ago

**Comment by Ido108** [comment]
same here (Windows last ver.)

**Comment by blaisewf** [comment]
i’ll check it

**Comment by blaisewf** [comment]
fixed on the new update
