### ISSUE TITLE
How to make stress in words in TTS

### ISSUE THREAD

**Issue by DUNAguy** [IAHispano/Applio#599]
How to make stress in words in TTS?

Applio cannot recognize  ' + and other special symbols

**Comment by AznamirWoW** [comment]
> How to make stress in words in TTS?
> Applio cannot recognize ' + and other special symbols

Applio uses TTS provided by edge_tts module, which relies on Microsoft's speech services intended to read web-page content in Edge browser aloud using a neutral voice. It is not supposed to use emotional markup or anything else.

**Comment by DUNAguy** [comment]
Elevenlab on same platform uses stresses

**Comment by AznamirWoW** [comment]
> Elevenlab on same platform uses stresses

11Labs does not use Edge TTS. They use tortoise or something like that.

**Comment by DUNAguy** [comment]
Ok
