### ISSUE TITLE
[BUG] Error while downloading TTS output

### ISSUE THREAD

**Issue by WiryBarley119** [IAHispano/Applio#609]
I have an error when I try to download the output of my TTS audio files in Applio. I tried downloading using the installed and compressed version but it still happens. I don't know why this is happening to me. What I did wrong? Can anyone help me please?

![RVC Error 3](https://github.com/user-attachments/assets/e59c36e7-7977-4c04-964b-692290edf6eb)
![RVC Error 4](https://github.com/user-attachments/assets/15be4ca7-a58c-42c4-a806-90271dd9eb9d)

I use Windows 10 and Google Chrome as browser.

**Comment by blaisewf** [comment]
restart your pc and try again, if not, check permissions
