### ISSUE TITLE
[DOCUMENT] This project is not compatible with python > 3.10

### ISSUE THREAD

**Issue by melMass** [IAHispano/Applio#612]
**Bug Description**
I couldn't find mention about this constraint, looking at the install scripts they fallback to whatever python3 is installed.

**Steps to Reproduce**
Run the install scripts or use a custom venv with python > 3.10 and you will end up with issues from #229 or #176 or #142 

**Expected Behavior**
Either update dependency constraints to make it work on > 3.10+ or state in the readme about the incompatibility

**Desktop Details:**
- Operating System:  Windows 11
- Browser: Chrome

**Comment by blaisewf** [comment]
running the install script you shouldn't have any problem, we will consider adding some extra info to our docs
