### ISSUE TITLE
[BUG] Not using all the GPU.

### ISSUE THREAD

**Issue by ZeroCool22** [IAHispano/Applio#613]
**Bug Description**
![Screenshot_5](https://github.com/user-attachments/assets/6584600b-e4bb-437b-bc00-bcedae602af3)

![Screenshot_6](https://github.com/user-attachments/assets/38336e16-6138-459e-a1bf-7de0cee409e5)

Are there some arguments or something to make it use more % of the GPU, so training could be more fast?

**Desktop Details:**
- Operating System: [e.g., Windows 10]
- Browser: [e.g., FireFox]

**Additional Context**
Any additional information that might be relevant to the issue.

**Comment by blaisewf** [comment]
try increasing the batch size, but you are having a perfect training speed, so just keep it like that in my opinion
