### ISSUE TITLE
RuntimeError: use_libuv was requested but PyTorch was build without libuv support

### ISSUE THREAD

**Issue by babymonie** [IAHispano/Applio#616]
**Bug Description**
When i try to train a model i get RuntimeError: use_libuv was requested but PyTorch was build without libuv support

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Go to 'Train'
2. Enter any parameters
3. Click train 
4. Observe the error.

**Expected Behavior**
It should train correctly

**Desktop Details:**
- Operating System: [e.g., Windows 10]
- Browser: [e.g.,Opera]

![image](https://github.com/user-attachments/assets/cb5a3894-efb3-4a2d-9343-f1375731617f)

here's a log:
Theme Loaded: Applio
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
E:\ApplioV3.0.9\rvc\infer\infer.py:303: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(weight_root, map_location="cpu")
Starting preprocess with 12 cores...
Preprocess completed in 31.11 seconds.
Starting extraction with 12 cores and rmvpe...
F0 Extraction: 100%|█████████████████████████████████████████████████████████████████| 615/615 [00:12<00:00, 47.80it/s]
F0 extraction completed in 12.89 seconds.
Starting feature extraction...
E:\ApplioV3.0.9\env\lib\site-packages\fairseq\checkpoint_utils.py:315: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(f, map_location=torch.device("cpu"))
E:\ApplioV3.0.9\env\lib\site-packages\torch\nn\utils\weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
  0%|                                                                                          | 0/615 [00:00<?, ?it/s]
Feature extraction completed in 2.26 seconds.
Downloading Pretrained Model...
100% [......................................................................] 438156650 / 438156650Process Process-1:
Traceback (most recent call last):
  File "E:\ApplioV3.0.9\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "E:\ApplioV3.0.9\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\ApplioV3.0.9\rvc\train\train.py", line 242, in run
    dist.init_process_group(
  File "E:\ApplioV3.0.9\env\lib\site-packages\torch\distributed\c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "E:\ApplioV3.0.9\env\lib\site-packages\torch\distributed\c10d_logger.py", line 93, in wrapper
    func_return = func(*args, **kwargs)
  File "E:\ApplioV3.0.9\env\lib\site-packages\torch\distributed\distributed_c10d.py", line 1361, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "E:\ApplioV3.0.9\env\lib\site-packages\torch\distributed\rendezvous.py", line 258, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "E:\ApplioV3.0.9\env\lib\site-packages\torch\distributed\rendezvous.py", line 185, in _create_c10d_store
    return TCPStore(
RuntimeError: use_libuv was requested but PyTorch was build without libuv support
Saved index file 'E:\ApplioV3.0.9\logs\Sir Bloody Daryl\added_Sir Bloody Daryl_v2.index'

cuda version 12.1
torch version:121

**Comment by blaisewf** [comment]
use the latest compiled

**Comment by blaisewf** [comment]
https://huggingface.co/IAHispano/Applio/resolve/main/Compiled/ApplioV3.2.4.zip?download=true
