### ISSUE TITLE
[Question/Bug] Python 3.12 Support

### ISSUE THREAD

**Issue by MalcolmReed-ent** [IAHispano/Applio#622]
## Bug Description

Unable to install Applio on Debian Sid with Python 3.12 Venv

## Issue Summary

When attempting to set up Applio using Python 3.12 on Debian Sid, the installation process fails. The same process works fine with older Python versions. We're seeking information on when full compatibility for Python 3.12 can be expected.

## Steps to Reproduce

1. Clone the repository:

git clone https://github.com/IAHispano/Applio/ && cd Applio/

text

2. Create and activate a virtual environment:

python3 -m venv .venv && source .venv/bin/activate

3. Install Applio dependencies:

python -m pip install "pip<24.1" && python -m pip install -r requirements.txt && python -m pip uninstall torch torchvision torchaudio -y && python -m pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu121

## Error Output

The installation fails with two main errors:

1. Build dependency installation failure:

  Cloning https://github.com/IAHispano/fairseq to /tmp/pip-req-build-i5f8f81b
  Running command git clone --filter=blob:none --quiet https://github.com/IAHispano/fairseq /tmp/pip-req-build-i5f8f81b
  Resolved https://github.com/IAHispano/fairseq to commit dc3a876f41d154c061ab91f8cace2b9775d32c34
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      Collecting setuptools>=18.0

2. Disk space error:

      Installing collected packages: mpmath, wheel, typing-extensions, sympy, setuptools, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, MarkupSafe, fsspec, filelock, cython, triton, nvidia-cusparse-cu12, nvidia-cudnn-cu12, jinja2, nvidia-cusolver-cu12, torch
      ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

      [notice] A new release of pip is available: 24.0 -> 24.2
      [notice] To update, run: pip install --upgrade pip
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

## Expected Behavior

Successfully install Applio and be able to run `./run-applio.sh`.

## Desktop Details

- Operating System: Debian GNU/Linux trixie trixie/sid x86_64
- Browser: Chromium 127.0.6533.119-1 amd64, Firefox-esr 115.14.0esr-1 amd64

**Comment by blaisewf** [comment]
we dont have any plans to support others versions, but pr are accepted. py3.9 works fine

**Comment by MalcolmReed-ent** [comment]
Oh, ok, that's cool, ill find a way to use 3.9
