### ISSUE TITLE
Support for AMD and Intel Graphics Cards

### ISSUE THREAD

**Issue by Bebra777228** [IAHispano/Applio#627]
I would like to know if **AMD and Intel** graphics cards are supported. Will I be able to run this program on such devices?
If there is no support, will it be added in the future? _(As I understand, **AMD and Intel** work with **DirectML**)_

**Comment by AznamirWoW** [comment]
> I would like to know if **AMD and Intel** graphics cards are supported. Will I be able to run this program on such devices? If there is no support, will it be added in the future? _(As I understand, **AMD and Intel** work with **DirectML**)_

AMD is supported with Zluda, should be available in the next release (or in current with some manual patching).

As for DirectML or Intel OpenVino, those are a bit tricky to implement as a drop-in.
