### ISSUE TITLE
run-install.bat - cannot install the program

### ISSUE THREAD

**Issue by AmoArt** [IAHispano/Applio#650]
**Bug Description**
Cannot install the program

**Steps to Reproduce**
download the zip from Rlease page
run run-install.bat 

**Expected Behavior**
Describe what you expected to happen.

**Assets**
Include screenshots or videos if they can illustrate the issue.

**Desktop Details:**
Windows 7

**Additional Context**
Console error after running the run-install.bat 

Could Not Find C:\aiApplio_3_2_4\Applio\Makefile
Could Not Find C:\aiApplio_3_2_4\Applio\Dockerfile
Could Not Find C:\aiApplio_3_2_4\Applio\docker-compose.yaml
Could Not Find C:\aiApplio_3_2_4\Applio\*.sh
Downloading the fairseq build...
Download failed, trying with the powershell method
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure
channel.
At line:1 char:4
+ & {Invoke-WebRequest -Uri 'https://huggingface.co/IAHispano/applio/re ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand

Extracting the file...
Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find
file 'C:\aiApplio_3_2_4\Applio\env.zip'."
At line:1 char:63
+ ... ileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

Extracting failed trying with the tar method...
'tar' is not recognized as an internal or external command,
operable program or batch file.
Theres a problem extracting the file please download the file and extract it man
ually.
https://huggingface.co/IAHispano/applio/resolve/main/env.zip
Press any key to continue . . .

**Comment by blaisewf** [comment]
use the compiled version
