### ISSUE TITLE
Failed to resolve 'cdn-lfs.huggingface.co' while running run_appolio.bat

### ISSUE THREAD

**Issue by Izolovi4** [IAHispano/Applio#651]
tried running appolio for the first time and immediately stumbled on an error:

> (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016F04E1E700>: Failed to resolve 'cdn-lfs.huggingface.co' ([Errno 11001] getaddrinfo failed)"))

how do I fix this?

**Comment by blaisewf** [comment]
> tried running appolio for the first time and immediately stumbled on an error:
> 
> > (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016F04E1E700>: Failed to resolve 'cdn-lfs.huggingface.co' ([Errno 11001] getaddrinfo failed)"))
> 
> how do I fix this?

ensure your internet connection, will be fixed in the new release
