### ISSUE TITLE
Python 3.12 suppot

### ISSUE THREAD

**Issue by themassivecollection** [IAHispano/Applio#667]
Hi can you make next version support python 3.12. Thank you

**Comment by blaisewf** [comment]
@themassivecollection could you try to run applio in your environment and upgrade to version 3.12? we would appreciate some pr from you, as for the moment we don't feel the need to upgrade, 3.9, 3.10 work fine

**Comment by AznamirWoW** [comment]
required package changes to be able to install the requirements

numpy==1.23.5 -> 1.26.4 # conflict with audio_upscaler
scipy==1.11.1 -> 1.14.1
numba==0.57  -> 0.60.0
torch==2.1.1 -> 2.2.2
faiss-cpu==1.7.4 -> 1.8.0 

but not much luck running it in a VM

**Comment by blaisewf** [comment]
we will move to 3.10 soon, but no eta for 3.12
