### ISSUE TITLE
Batch output does not create folder location if it doesn't exist error

### ISSUE THREAD

**Issue by KillauraHacks** [IAHispano/Applio#682]
**Bug Description**
Not sure if this is a bug or a feature request considering its something that is in the original RVC but when you are doing batch inference and your output folder location doesn't exist it'll error out. This feature is something I love using in normal RVC to separate my batch outputs very much need it in Applio as it gets tedious having to create each folder manually.

**Steps to Reproduce**
Outline the steps to replicate the issue:
1. run-applio.bat
2. go to batch tab
3. put in your input folder location
4. put in desired output folder location
5. edit settings if needed
6. convert

**Expected Behavior**
In normal RVC it'll create the folder output location if it doesn't exist but in Applio it just errors out instead of making that folder.

**Assets**
![image](https://github.com/user-attachments/assets/b96071df-9ca4-4602-a8c0-5d5c293ad53d)

**Desktop Details:**
Windows 10, Chrome using the web ui (run-applio.bat)

**Comment by KillauraHacks** [comment]
> Thank you for reporting this issue. I understand that you're expecting the output folder to be created automatically if it doesn't exist, similar to the behavior in the original RVC. This is a reasonable expectation, and I'll investigate further.
> 
> In the meantime, I'd like to confirm that you've checked the `create_output_folder` setting in the `applio_config.json` file. According to the documentation (https://docs.applio.org), this setting should be set to `true` to enable automatic creation of the output folder. Could you please verify if this setting is enabled in your configuration file? If not, please try setting it to `true` and see if it resolves the issue.

there is no create_output_folder setting in the config.json for applio

**Comment by blaisewf** [comment]
hey, we can add that feature

**Comment by blaisewf** [comment]
done https://github.com/IAHispano/Applio/commit/f40b82178d5f37f4d02a364c86e47cbd3b3e7d6d
