### ISSUE TITLE
Error connection

### ISSUE THREAD

**Issue by cally786** [IAHispano/Applio#683]
Bug Description :When I try to download some model, or even screen record after compiling applio it tells me conection error, 

and it tells me this in the terminal  line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

Steps to Reproduce
Desktop Details

**Comment by blaisewf** [comment]
can you try with the latest compiled version uploaded on hugging? should be fixed

**Comment by gilushon** [comment]
**Thank you blaisewf**

I had the same problem and the software said there was a connection problem.
The version in hugging face works wonderfully!

1. In the download tab - it is important to read the instructions and **drag one after the other** (and not together) - the index file and then the model.

2. In the Inference tab - it is important to work according to the steps and **first load the model and index and only then load the sound file.**

**Thanks again!**
