### ISSUE TITLE
[Feature Request] Single binary support

### ISSUE THREAD

**Issue by dreamwhite** [IAHispano/Applio#684]
First of all thank you so much for this amazing project. I actually succeeded creating a "fork" version which runs in a PyQT5 (WebEngine) desktop application.

However there are a few things I don't like much about this project such as the inability of changing the path of the assets (which in terms of distributing the package is not the best approach) and most importantly the fact that without the proper Python virtual environment, it cannot be run.

I'd kindly like to know, if there's in the developers plans, if a single binary (which bundles all the necessary dependencies) will be ever released.
I tried using Nuitka as well as pyinstaller and cxfreeze without any success. Have you ever succeeded doing it?
Thank you so much
dreamwhite

**Comment by blaisewf** [comment]
> First of all thank you so much for this amazing project. I actually succeeded creating a "fork" version which runs in a PyQT5 (WebEngine) desktop application.
> 
> However there are a few things I don't like much about this project such as the inability of changing the path of the assets (which in terms of distributing the package is not the best approach) and most importantly the fact that without the proper Python virtual environment, it cannot be run.
> 
> I'd kindly like to know, if there's in the developers plans, if a single binary (which bundles all the necessary dependencies) will be ever released. I tried using Nuitka as well as pyinstaller and cxfreeze without any success. Have you ever succeeded doing it? Thank you so much dreamwhite

changing a few lines of code you can move the paths of the .pt, .pth, .bin… files, we have our version with the dependencies compiled, we don’t plan to do more than that

**Comment by blaisewf** [comment]
btw join to discord and feel free to share your project
