### ISSUE TITLE
run-applio.bat opens a command prompt but nothing happens

### ISSUE THREAD

**Issue by cbnsingram** [IAHispano/Applio#687]
Bug Description This is after downloading and extracting the compiled version 3.2.5
Steps to reproduce turn off anti-virus and firewall. download and extract the files and run the bat file.
Desktop details: I am on Windows 11 pro Version	10.0.22631 Build 22631
This computer ran 3.2.4 just fine and I'll go back to that for now.

**Comment by cbnsingram** [comment]
There are no errors in the command window or elsewhere. Blank window. I did not try running it as an admin.  I thought that was not recommended.  I'm going back to 3.2.4

**Comment by blaisewf** [comment]
open the cmd and write the command manually `env\python.exe app.py --open`
