### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by makhlwf** [IAHispano/Applio#688]
Hello, I need to launch the WebUI to be in a way that accessible to anyone in my local area network. How can I do that?

**Comment by blaisewf** [comment]
will be accessible within your network to anyone who sets your iplocal:6969

**Comment by makhlwf** [comment]
- [No, it didn't work. In my computer, it shows  127.0.0.1:6969. Which means this is a specific IP address to my computer only. No one can open it, instead it's this particular computer. Though I tried on my phone opening 192.168.1.13:6969 and local:6969, but it didn't help either.

**Comment by blaisewf** [comment]
add a —share param in the launch script and you will get a shareable link
