### ISSUE TITLE
[Bug]: Inference adding in silence spots into the song, making it sound skippy

### ISSUE THREAD

**Issue by nonstopjoker** [IAHispano/Applio#689]
### Project Version

3.2.5

### Platform and OS Version

Windows 11 Pro 64 bit

### Affected Devices

PC

### What happened?

The audio is cutting out or skipping for a split second many times through out a song, it's very noticable. It doesn't really skip a piece of the song, it adds little silence spots into the track that adds length to the song, the song is like 10% longer. I've tried different songs, voice models, and I've tried Applio versions 3.2.2, 3.2.4, and 3.2.5. I've also tried changing all the inference menu settings in the webui. GPU I'm using is an RTX 3080.

Edit: I found an old version of Applio on my PC (3.0.8) and it seems to be working normally, but I'd still like to use the updated version if I can fix this issue.

### Steps to reproduce

1. Select voice model with index
2. Uploaded voice-isolated audio file
3. Set the advanced settings (used default, with rmvpe, contentvec embedder model, no fo curve
4. Click convert, wait a few minutes
5. Listen to the audio file, and I hear an audio file with a bunch of silence spots
...

### Expected behavior

I expect it to not insert a bunch of random silences into the converted song

### Additional Information

I can't upload audio files here. If needed, I can go on Discord and show what's happening.

**Comment by AznamirWoW** [comment]
@nonstopjoker send examples

**Comment by blaisewf** [comment]
fixed on the new version
