### ISSUE TITLE
[Bug]: Export Format bugs

### ISSUE THREAD

**Issue by KillauraHacks** [IAHispano/Applio#693]
### Project Version

3.2.5 but lower versions are also affected

### Platform and OS Version

Windows 10

### Affected Devices

PC

### What happened?

I believe audio is being degraded in batch when you select mp3 export format.

### Steps to reproduce

1. Go to batch inference
2. Set your input and output 
3. Select MP3 Export Format
4. Change any other settings you want doesn't matter
5. Convert
6. The mp3s come out in very low kbps 
...

### Expected behavior

Since wavs are over 320kbps I would expect mp3s to export as 320 kbps.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/8351f729-c86b-4add-9325-39dadfce0eb2)

### Additional Information

While I was making this also noticed the .ogg format doesnt work and sometimes crashes Applio after you click convert and the m4a format gives an error in console saying "An error occurred converting the audio format: Unknown format: 'm4a'" but m4a actually works and properly converted.

**Comment by blaisewf** [comment]
well, if you want quality just use flac or wav. but we will see what we can do, but isn't a priority

**Comment by AznamirWoW** [comment]
MP3s are saved with 192k bitrate by default.
