### ISSUE TITLE
[Feature]: it didn't use my gpu.

### ISSUE THREAD

**Issue by margo2130** [IAHispano/Applio#701]
### Description

hi, i want to use this for text to voice.
i could train a voice, give this software a pth and index file.
now i generate a voice by giving text.
but i want to create faster voice. i want this software use my gpu.
it only use ram and hdd (based i see in task manager). 
i a tutorial video, [link](https://www.youtube.com/watch?v=jh83ViDUvJs) i saw that it ask me which gpu you have when you run "go-appilio.bat". (look at 2:53 in video.)
but i haven't this file, i have "run-applio.bat" file. when i run it, it didn't ask me about gpu.

----------
how can i use gpu for generate faster.
thank you.
![image](https://github.com/user-attachments/assets/60c2b5c5-6ad1-40d5-a254-75a89e624319)
![image](https://github.com/user-attachments/assets/875a1cad-1e44-4eed-8102-e9d25c543378)

### Problem

use gpu for generate faster not only ram and hdd.

### Proposed Solution

adding gpu to generate voice process so it generate faster.

### Alternatives Considered

adding gpu and cpu for generate faster.

**Comment by margo2130** [comment]
hello again.
i found sth, when i convect voice to voice, it use gpu and since my gpu is powerfull pretty (4070 super), it take only seconds.
but why it didn't use gpu in t2v? how can i solve it? thanks.

**Comment by blaisewf** [comment]
the amount of potential usage is proportional to the power requirement of the task, in that case, with your gpu it is not a very demanding or time consuming task so the usage does not always have to be 100%.

as long as it recognizes your gpu in the training section, everything is fine.
