### ISSUE TITLE
[Feature]: Bigger model selection box?

### ISSUE THREAD

**Issue by embis0126** [IAHispano/Applio#707]
### Description

Bigger model selection box

### Problem

![image](https://github.com/user-attachments/assets/16e4eaf7-a26d-4c58-bc45-96ac2b8b1929)

The buttons "Refresh" and "Unload Voice" take up an abnormally large amount of space. This makes the selection box for the model and feature index very small and it makes it very hard (at least for my disorder-riddled brain) to easily locate models at an exact step/epoch. 

### Proposed Solution

Is it possible to shrink the buttons and extend the selection boxes? This would save so much headache.

### Alternatives Considered

Dropping the file path from the name in the selection box could also work to free up space.

**Comment by blaisewf** [comment]
that’s true, i’ll see what i can do

**Comment by blaisewf** [comment]
done, will be ready in next update

**Comment by embis0126** [comment]
awesome thanks!
