### ISSUE TITLE
[Feature]: Stop training without restarting (or add templates)?

### ISSUE THREAD

**Issue by embis0126** [IAHispano/Applio#708]
### Description

Implement a fix for the stop training system for ease of use

### Problem

It is a big pain to constantly have to restart Applio just to stop training because you have to reset all the values each time (I like to test my models during training so I stop them a lot, and inference during training more often that not crahses Applio).

And sometimes, it dosen't even actually stop training and it keeps iterating even after you click the buton. In old versions of Applio, this wasn't required. Is there a reason Applio must restart now?

### Proposed Solution

Add back the functionality to stop training without restarting Applio.

### Alternatives Considered

If there is a technical reason that requires Applio to be restarted after stopping training, perhaps introduce a templates feature for training that allows you to quickly add back the data values to match.

**Comment by blaisewf** [comment]
what values you need to modify? only select the same name, and 3 sliders. but we will see how we can improve it
