### ISSUE TITLE
[Bug]: Clean audio option dissapears when unchecking post-process

### ISSUE THREAD

**Issue by embis0126** [IAHispano/Applio#709]
### Project Version

3.2.5

### Platform and OS Version

Windows 11 64-bit

### Affected Devices

All

### What happened?

The clean audio option dissapears when unchecking post-process. Seems parrented or tied to it in some way.

### Steps to reproduce

1. Open Applio
2. Prepare Inference
3. Check post-process
4. Uncheck post-process
5. The clean audio option will now be gone

### Expected behavior

Clean audio to be independent from post-process and not dissapear

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/d27c4fe9-3ae9-44d1-8f92-6b09bb4ceb71)

**Comment by blaisewf** [comment]
is not a bug, it’s a post process option
