### ISSUE TITLE
[Bug]: Connection Errored Out

### ISSUE THREAD

**Issue by kafloogy** [IAHispano/Applio#715]
### Project Version

3.2.5

### Platform and OS Version

windows 11 64 bit

### Affected Devices

N/A

### Existing Issues

N/A

### What happened?

any action I try to do gives me "connection erroed out" message

### Steps to reproduce

1. it happens immediately when I start the program
2. 
3. 
...

### Expected behavior

to respond

### Attachments

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Applio\Applio-3.2.5\env\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "C:\Applio\Applio-3.2.5\env\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

### Screenshots or Videos

![Screenshot 2024-09-18 064141](https://github.com/user-attachments/assets/ff2bcb0c-67a7-4cfc-8f50-70b9cd52cabc)

### Additional Information

_unresponsive_

**Comment by blaisewf** [comment]
duplicated issue, check on discord the script to fix it
