### ISSUE TITLE
[Bug]: bug on overtraining

### ISSUE THREAD

**Issue by kro-ai** [IAHispano/Applio#719]
### Project Version

3.2.5

### Platform and OS Version

Windows 11, Firefox 130

### Affected Devices

PC

### What happened?

Instead of showing the actual number of epochs remaining for overtraining, it just says "g/total: 100 d/total: 200". It doesn't change.

### Steps to reproduce

1. Preprocess
2. Extract
3. Start training and look in the terminal
...

### Expected behavior

I expect it to show the number of epochs remaining for overtraining.

### Screenshots or Videos

![bug](https://github.com/user-attachments/assets/ede2a702-6cfb-485a-9125-f00b5c1d2890)

**Comment by blaisewf** [comment]
@ShiromiyaG

**Comment by kro-ai** [comment]
@blaisewf with all due respect, what do you mean "not planned"? In my opinion, this is an incredibly important feature, and right now It's pointless as It's not giving the user any useful information whatsoever.

**Comment by AznamirWoW** [comment]
@kro-ai  did you actually reach the point of overtraining? 
you've configured overtraining threshold at 100 epochs, so it means the generator loss has to go up consecutively for 100 epochs before the trainig stops

**Comment by kro-ai** [comment]
> @kro-ai did you actually reach the point of overtraining? you've configured overtraining threshold at 100 epochs, so it means the generator loss has to go up consecutively for 100 epochs before the trainig stops

I was under the impression that "number of epochs remaining for overtraining" would show the number of epochs? for example "number of epochs remaining for overtraining: 98" and then it keeps going down, but when it finds a new best epoch It resets to the set number of epochs, in this case 100. Maybe I've completely misunderstood it and If so I apologize. This is a feature Applio used to have. I was under the impression this was that feature?

**Comment by AznamirWoW** [comment]
> > @kro-ai did you actually reach the point of overtraining? you've configured overtraining threshold at 100 epochs, so it means the generator loss has to go up consecutively for 100 epochs before the trainig stops
> 
> I was under the impression that "number of epochs remaining for overtraining" would show the number of epochs? for example "number of epochs remaining for overtraining: 98" and then it keeps going down, until it reaches 0 and then training stops because it hasnt found a better epoch. Then when it finds a new best epoch It resets to the set number of epochs, in this case 100. Maybe I've completely misunderstood it and If so I apologize. This is a feature Applio used to have. I was under the impression this was that feature?

you set a threshold - 50 epochs.
At the end of the epoch the detector checks whether the loss is going down or up. If it goes up for 50 epochs it stops. The output shows the progress to this stop as  'selected threshold - number of epochs that consistently increased the loss'

**Comment by kro-ai** [comment]
> > > @kro-ai did you actually reach the point of overtraining? you've configured overtraining threshold at 100 epochs, so it means the generator loss has to go up consecutively for 100 epochs before the trainig stops
> > 
> > 
> > I was under the impression that "number of epochs remaining for overtraining" would show the number of epochs? for example "number of epochs remaining for overtraining: 98" and then it keeps going down, until it reaches 0 and then training stops because it hasnt found a better epoch. Then when it finds a new best epoch It resets to the set number of epochs, in this case 100. Maybe I've completely misunderstood it and If so I apologize. This is a feature Applio used to have. I was under the impression this was that feature?
> 
> you set a threshold - 50 epochs. At the end of the epoch the detector checks whether the loss is going down or up. If it goes up for 50 epochs it stops. The output shows the progress to this stop as 'selected threshold - number of epochs that consistently increased the loss'

I get that. I guess I just don't see how having g/total and d/total shown is more useful than having it the way it was before. I guess It's a preference thing.
