### ISSUE TITLE
[Feature]: Do not use TTS

### ISSUE THREAD

**Issue by phudx** [IAHispano/Applio#721]
### Description

In the TTS tab, is it possible to export an audio file using only RVC without using TTS?

### Problem

In the TTS tab, is it possible to export an audio file using only RVC without using TTS?

### Proposed Solution

In the TTS tab, is it possible to export an audio file using only RVC without using TTS?

### Alternatives Considered

In the TTS tab, is it possible to export an audio file using only RVC without using TTS?

**Comment by blaisewf** [comment]
https://docs.applio.org/getting-started/tts#disclaimer
