### ISSUE TITLE
[Bug]: css don't set properly

### ISSUE THREAD

**Issue by DUNAguy** [IAHispano/Applio#723]
### Project Version

3.2 3

### Platform and OS Version

Win 11, Chrome 

### Affected Devices

All

### What happened?

Looks weird, css don't apply

### Steps to reproduce

1. 
2. 
3. 
...
Reproduce what?

### Expected behavior

No clue

### Screenshots or Videos

![20240920_174923](https://github.com/user-attachments/assets/cd1aebb7-7d7c-40b0-a545-5b44d5f10f10)

**Comment by blaisewf** [comment]
try opening the localhost:6969 url, usually just by refreshing the page or changing the browser works, but that’s a local problem on your pc by the way websites are loaded
