### ISSUE TITLE
[Feature]: Please give me version 2.0.0

### ISSUE THREAD

**Issue by phudx** [IAHispano/Applio#730]
### Description

Thank you, the program is very good.
Can you send me your version 2.0.0?

### Problem

Thank you, the program is very good.
Can you send me your version 2.0.0?

### Proposed Solution

Thank you, the program is very good.
Can you send me your version 2.0.0?

### Alternatives Considered

Thank you, the program is very good.
Can you send me your version 2.0.0?

**Comment by blaisewf** [comment]
search on the github tags, but why
