### ISSUE TITLE
[Bug]: training no longer works

### ISSUE THREAD

**Issue by testter21** [IAHispano/Applio#732]
### Project Version

latest

### Platform and OS Version

macos

### Affected Devices

macbok pro m3

### What happened?

Pinokio version. Few days ago (prior to your hack), training on mbp worked, I could generate new voices. Now I just get an error. Data set prep and feature extraction seem to work, trainign is dead.

///
Starting training...
Loaded pretrained (G) 'rvc/models/pretraineds/pretrained_v2/f0G40k.pth'
Loaded pretrained (D) 'rvc/models/pretraineds/pretrained_v2/f0D40k.pth'
  0%|                                                                                                                                                | 0/29 [00:00<?, ?it/s]/Users/tester/pinokio/api/applio.git/applio/rvc/lib/algorithm/attentions.py:180: UserWarning: MPS: The constant padding of more than 3 dimensions is not currently supported natively. It uses View Ops default implementation to run. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Pad.mm:474.)
  x = torch.nn.functional.pad(
/Users/tester/pinokio/api/applio.git/applio/env/lib/python3.10/site-packages/torch/nn/utils/parametrizations.py:299: UserWarning: The operator 'aten::_weight_norm_interface' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
  return torch._weight_norm(weight_v, weight_g, self.dim)
Process Process-1:                                                                                                                                                          
Traceback (most recent call last):
  File "/Users/tester/pinokio/bin/miniconda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/tester/pinokio/bin/miniconda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tester/pinokio/api/applio.git/applio/rvc/train/train.py", line 497, in run
    train_and_evaluate(
  File "/Users/tester/pinokio/api/applio.git/applio/rvc/train/train.py", line 738, in train_and_evaluate
    scaler.scale(loss_gen_all).backward()
  File "/Users/tester/pinokio/api/applio.git/applio/env/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/Users/tester/pinokio/api/applio.git/applio/env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
TypeError: Complex types are unsupported on MPS
Saved index file '/Users/tester/pinokio/api/applio.git/applio/logs/rm10/added_rm10_v2.index'
///

### Steps to reproduce

test
SR: 40000
model arch.: v2

datasetname: test
audio: 10min long file
adv.settings: untouched
after preprocess: sliced_audios, sliced_audios_16k, model_info.json // only wav files in both folders

pitch extract algo: crepe, hop 128
embedder model: contentvec
pitch guidance: on
cpu/gpu section: untouched
after extraction: f0, f0_voiced, v2_extracted, filelist.txt // folders have corresponding qty of npy files
crepe works definitely slower than rmvpe (which worked) - tested this after some suggestion on pinokio discord

train:
batch size: 8 (default)
save every epoch: 50
total epoch: 600

advanced settings:
Save Only Latest: on
Save Every Weights: on (default)
Pretrained: on (default)
Sync Graph: off (default)
Cache Dataset in GPU: off (default)
Pitch Guidance: on (default)
Custom Pretrained: off (default)
GPU Settings: off (default)
Overtraining Detector: on, 50
Index Algorithm: auto

### Expected behavior

Expected behavior is to get a trained model, that can be used in TTS section. This worked.

**Comment by AznamirWoW** [comment]
PYTORCH_ENABLE_MPS_FALLBACK should be set to 1, try that

**Comment by testter21** [comment]
In which file put this line? (it was 1-click installer for pinokio browser)

**Comment by testter21** [comment]
in start.js there is already such line:

        env: {
          PYTORCH_ENABLE_MPS_FALLBACK: 1
        },

**Comment by AznamirWoW** [comment]
just create a system or user environment variable

**Comment by testter21** [comment]
such line already exists here by default
[start.js.txt](https://github.com/user-attachments/files/17098233/start.js.txt)

(changed extension)
