### ISSUE TITLE
DiffGrad Optimizer

### ISSUE THREAD

**Issue by Bebra777228** [IAHispano/Applio#737]
What do you think about the DiffGrad optimizer?
Do you think it is better than AdamW?

I heard that it can be a couple of percent more efficient, but I couldn't find it in popular forks.

**Comment by AznamirWoW** [comment]
> What do you think about the DiffGrad optimizer? Do you think it is better than AdamW?
> 
> I heard that it can be a couple of percent more efficient, but I couldn't find it in popular forks.

while it works as a drop-in replacement, it does not seem to provide much benefit. Granted I only tried it with 100 epochs and 4 min audio.

Perhaps with some tweaking it may, but good luck with that.
