### ISSUE TITLE
[Feature]: Add support for 44.1khz audio

### ISSUE THREAD

**Issue by sharkeylaser** [IAHispano/Applio#741]
### Description

I was wondering if it would be possible to add support for 44.1khz audio files without having to resample. It's also a common sample rate, so it might be good to have as an option. Thanks for your efforts!

### Problem

Currently, 44.1khz audio options are not present in Applio. Given that it's a common sample rate for CDs, I would think it should be an option.

I have a ton of audiobooks on CDs that I would like to work with, hence the request to support 44.1khz audio. I would like to take the narrator of one audiobook and use their voice to replace the narrator's voice of another audiobook.

### Proposed Solution

44.1khz audio should be supported without having to resample.

### Alternatives Considered

n/a

**Comment by blaisewf** [comment]
we don’t plan to do that, 40khz and 44.1khz are mostly the same, if you want more quality you can go with 48khz

**Comment by AznamirWoW** [comment]
additionally there are no 44.1KHz pretrains

**Comment by sharkeylaser** [comment]
It seems that using 48khz causes the voice to become robotic, distorted, and choppy. 40khz sounds better, but sacrifices quality. It would be a real shame if there's truly no plans for such a common sample rate.
What would it take to make a 44.1khz pretrain?

**Comment by ShiromiyaG** [comment]
> It seems that using 48khz causes the voice to become robotic, distorted, and choppy. 40khz sounds better, but sacrifices quality. It would be a real shame if there's truly no plans for such a common sample rate. What would it take to make a 44.1khz pretrain?

Well, this sample rate isn't that common, the most common is 32k because of YouTube. As for making a pretrain, it would cost about 40 dollars, BUT the code for making pretrains is currently broken, so even if you had the money, it wouldn't work.

**Comment by sharkeylaser** [comment]
> > It seems that using 48khz causes the voice to become robotic, distorted, and choppy. 40khz sounds better, but sacrifices quality. It would be a real shame if there's truly no plans for such a common sample rate. What would it take to make a 44.1khz pretrain?
> 
> Well, this sample rate isn't that common, the most common is 32k because of YouTube. As for making a pretrain, it would cost about 40 dollars, BUT the code for making pretrains is currently broken, so even if you had the money, it wouldn't work.

It's a very common sample rate; every single CD that has ever been released has been 44.1khz, and CDs have existed decades before YouTube. There are billions of hours more of CDs than there are YouTube videos.
Okay, why would it cost 40 dollars? And what code is it?

**Comment by AznamirWoW** [comment]
>Okay, why would it cost 40 dollars? And what code is it?

He meant the cost of training a pretrained model from scratch at 44.1KHz on 4090 x 100-200 hours. The training from scratch unfortunately produces garbage results right now due to a noise introduced by the model.

**Comment by sharkeylaser** [comment]
> > Okay, why would it cost 40 dollars? And what code is it?
> 
> He meant the cost of training a pretrained model from scratch at 44.1KHz on 4090 x 100-200 hours. The training from scratch unfortunately produces garbage results right now due to a noise introduced by the model.

I have a 4080S; I'll do the work. Aside from the working code, what is needed to be done?

**Comment by AznamirWoW** [comment]
> > > Okay, why would it cost 40 dollars? And what code is it?
> > 
> > 
> > He meant the cost of training a pretrained model from scratch at 44.1KHz on 4090 x 100-200 hours. The training from scratch unfortunately produces garbage results right now due to a noise introduced by the model.
> 
> I have a 4080S; I'll do the work. Aside from the working code, what is needed to be done?

you need a new config for v2/44100.json with appropriate settings
you need to change config.py to include this file
you need to change tabs/train/train.py to include the new option for sampling rate

then you need to figure out a big data set to train the pretrain on. It is unknow which data set was used for original RVC training or how it was actually made. Safe to say, multiple hours of varying audio.

train a new model without using pretrained (from scratch) until the model reaches an optimal state and no longer produces horizontal lines on the spectrogram.

**Comment by blaisewf** [comment]
> > > > Okay, why would it cost 40 dollars? And what code is it?
> 
> > > 
> 
> > > 
> 
> > > He meant the cost of training a pretrained model from scratch at 44.1KHz on 4090 x 100-200 hours. The training from scratch unfortunately produces garbage results right now due to a noise introduced by the model.
> 
> > 
> 
> > I have a 4080S; I'll do the work. Aside from the working code, what is needed to be done?
> 
> 
> 
> you need a new config for v2/44100.json with appropriate settings
> 
> you need to change config.py to include this file
> 
> you need to change tabs/train/train.py to include the new option for sampling rate
> 
> 
> 
> then you need to figure out a big data set to train the pretrain on. It is unknow which data set was used for original RVC training or how it was actually made. Safe to say, multiple hours of varying audio.
> 
> 
> 
> train a new model without using pretrained (from scratch) until the model reaches an optimal state and no longer produces horizontal lines on the spectrogram.

the base pretrained is vctk

**Comment by sharkeylaser** [comment]
Awesome, thanks for the info, @AznamirWoW and @blaisewf ! Once the issue with the code is resolved, I will get it done. Is there an issue open to track that problem, or an ETA for when/if the code will be fixed?

**Comment by ShiromiyaG** [comment]
> Awesome, thanks for the info, @AznamirWoW and @blaisewf ! Once the issue with the code is resolved, I will get it done. Is there an issue open to track that problem, or an ETA for when/if the code will be fixed?

There's no ETA, since we don't know what's causing the problem, about open an issue, there are already two open
https://github.com/fumiama/Retrieval-based-Voice-Conversion-WebUI/issues/87
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2319

**Comment by sharkeylaser** [comment]
Alright, I will keep checking in on those issues to see when it's resolved and proceed after. Thanks for the links, @ShiromiyaG !

**Comment by Margen67** [comment]
@blaisewf Why close? It seems odd to not support the most common sample rate.

> > It seems that using 48khz causes the voice to become robotic, distorted, and choppy. 40khz sounds better, but sacrifices quality. It would be a real shame if there's truly no plans for such a common sample rate. What would it take to make a 44.1khz pretrain?
> 
> Well, this sample rate isn't that common, the most common is 32k because of YouTube. As for making a pretrain, it would cost about 40 dollars, BUT the code for making pretrains is currently broken, so even if you had the money, it wouldn't work.

@ShiromiyaG YouTube's sample rate is either 44.1khz or 48khz, not 32.

**Comment by ShiromiyaG** [comment]
> @blaisewf Why close? It seems odd to not support the most common sample rate.
> 
> > > It seems that using 48khz causes the voice to become robotic, distorted, and choppy. 40khz sounds better, but sacrifices quality. It would be a real shame if there's truly no plans for such a common sample rate. What would it take to make a 44.1khz pretrain?
> > 
> > 
> > Well, this sample rate isn't that common, the most common is 32k because of YouTube. As for making a pretrain, it would cost about 40 dollars, BUT the code for making pretrains is currently broken, so even if you had the money, it wouldn't work.
> 
> @ShiromiyaG YouTube's sample rate is either 44.1khz or 48khz, not 32.

It doesn't mean that the audio is 44.1k because the audio has that sample rate. If you want to see for yourself, download the “Spek” application and see with him an audio from YouTube.

**Comment by Margen67** [comment]
> > blaisewf Why close? It seems odd to not support the most common sample rate.
> > > > It seems that using 48khz causes the voice to become robotic, distorted, and choppy. 40khz sounds better, but sacrifices quality. It would be a real shame if there's truly no plans for such a common sample rate. What would it take to make a 44.1khz pretrain?
> > > 
> > > 
> > > Well, this sample rate isn't that common, the most common is 32k because of YouTube. As for making a pretrain, it would cost about 40 dollars, BUT the code for making pretrains is currently broken, so even if you had the money, it wouldn't work.
> > 
> > 
> > @ShiromiyaG YouTube's sample rate is either 44.1khz or 48khz, not 32.
> 
> It doesn't mean that the audio is 44.1k because the audio has that sample rate. If you want to see for yourself, download the “Spek” application and see with him an audio from YouTube.

YouTube typically resamples audio to 48kHz, but this is the first time I've heard of YouTube using 32kHz, and can't find anything on Google. Their documentation recommends 48kHz: https://support.google.com/youtube/answer/6039860

I opened a YouTube video in spek like you said, and the max frequency is higher than 32kHz.
  * [Get Lucky (YouTube)](https://youtu.be/5NV6Rdv1a3I)
  ![GetLucky_YouTube](https://github.com/user-attachments/assets/b4d2e8c8-633d-43da-8547-8a49db5d3419)
  * CD downsampled to 32kHz:
  ![GetLucky_32khz](https://github.com/user-attachments/assets/2c365d65-278b-4ea8-8888-ccd7a3fe01ed)
  * Original CD:
  ![GetLucky_CD](https://github.com/user-attachments/assets/2573f1f9-b4c4-4827-8531-792a43037435)

I also tried listening to the YouTube video downsampled to 32kHz, and it sounds noticeably worse.

I'm not sure why the YouTube audio doesn't cover the entire spectrum. It could be that the audio was originally a lower sample rate, a low pass filter was used, or a side effect of lossy compression/encoding. I'm too lazy to upload a video to test this.

44.1kHz is the most common audio sampling rate: https://en.wikipedia.org/wiki/44,100_Hz

40kHz outside of voice AI isn't common.

**Comment by dogtopus** [comment]
> the most common is 32k because of YouTube

32k is not transparent at all and any music would sound horrible. Only the low bit rate mode of YouTube use 32k and I doubt people download that to train models.

My guess on why 32k was in RVC is that 32k is "mostly enough" for speech. And of course 40k is at the borderline of human hearing, and where most non-audiofoolery lossy codec would cut off, so it makes sense to include it. As to why there wasn't 44100 despite being used in **almost all** lossless consumer digital music files is beyond me.

**Comment by blaisewf** [comment]
already added

**Comment by sharkeylaser** [comment]
> already added

@blaisewf I'm not seeing the option to choose 44100 sampling rate on the training tab in the latest release. Do I need to compile from scratch?

**Comment by AznamirWoW** [comment]
> > already added
> 
> [@blaisewf](https://github.com/blaisewf) Thank you very much for adding it, but I'm not seeing the option to choose 44100 sampling rate on the training tab in the latest release. Do I need to compile from scratch?

it is in the main branch, not released yet

**Comment by AznamirWoW** [comment]
> Just compiled main branch, same thing. Line 2001 of core.py reads "choices=[32000, 40000, 48000],"; should it be added there?

![Image](https://github.com/user-attachments/assets/c17dcd99-9d96-46e3-a184-e3b557463bbf)

**Comment by sharkeylaser** [comment]
Strange. This is what's showing for me:

![Image](https://github.com/user-attachments/assets/c24b1506-bf0f-4ff5-b4d4-a08fd4ce13fa)

To be clear, just download the zip file for the master branch, unpack, run "run-install.bat" to install and "run-applio.bat", right?
