### ISSUE TITLE
[Bug]: Cannot convert text to speech from tts tab

### ISSUE THREAD

**Issue by haibui2000** [IAHispano/Applio#744]
### Project Version

Latest version of the project

### Platform and OS Version

Window 10

### Affected Devices

Window 10

### What happened?

I can't do conversion from the model I trained. They are not showing error on screen. However, in CMD they are showing error without "voice". I think this is because they are not being taken from the model I trained when I left blank "Select the TTS voice to use for the conversion." Maybe I did something wrong, I tried to make modification to take from model but I don't have enough knowledge to do that. Please give me feedback. Best regards!

### Steps to reproduce

Attached with video. Model is taken directly from the link you provided.

### Expected behavior

An error occurred connecting to Discord: Could not find Discord installed and running on this machine.
Theme Applio successfully loaded.
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\mywork\Applio\rvc\lib\tools\tts.py", line 20, in <module>
    asyncio.run(main())
  File "E:\mywork\Applio\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\mywork\Applio\env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\mywork\Applio\rvc\lib\tools\tts.py", line 15, in main
    await edge_tts.Communicate(text, voice, rate=rates).save(output_file)
  File "E:\mywork\Applio\env\lib\site-packages\edge_tts\communicate.py", line 279, in __init__
    raise ValueError(f"Invalid voice '{voice}'.")
ValueError: Invalid voice 'None'.
Converting audio 'E:\mywork\Applio\assets\audios\tts_output.wav'...
An error occurred during audio conversion: An error occurred loading the audio: File not found: E:\mywork\Applio\assets\audios\tts_output.wav
Traceback (most recent call last):
  File "E:\mywork\Applio\rvc\lib\utils.py", line 61, in load_audio_infer
    raise FileNotFoundError(f"File not found: {file}")
FileNotFoundError: File not found: E:\mywork\Applio\assets\audios\tts_output.wav

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\mywork\Applio\rvc\infer\infer.py", line 261, in convert_audio
    audio = load_audio_infer(
  File "E:\mywork\Applio\rvc\lib\utils.py", line 81, in load_audio_infer
    raise RuntimeError(f"An error occurred loading the audio: {error}")
RuntimeError: An error occurred loading the audio: File not found: E:\mywork\Applio\assets\audios\tts_output.wav

Temporary MP4 file saved as: C:\Users\admin\AppData\Local\Temp\tmpu5cogwpl.mp4
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\mywork\Applio\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\mywork\Applio\env\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### Screenshots or Videos

[recording.webm](https://github.com/user-attachments/assets/971f27a9-5963-453c-ba1b-cbe5b927a98e)
![image](https://github.com/user-attachments/assets/1e064490-b5c8-49cd-944b-1580f6b35072)

**Comment by AznamirWoW** [comment]
how can you have your pudding if you don't eat your meat?

It tells you what the problem is. You can not do TTS without selecting a TTS voice. You can not use a voice in a language that does not match the language of the text you provide.
