### ISSUE TITLE
[Bug]: Autotune not working

### ISSUE THREAD

**Issue by Chilluminati91** [IAHispano/Applio#754]
### Project Version

c67d0a3

### Platform and OS Version

Windows 11 64Bit

### Affected Devices

/

### What happened?

When enabling autotune the resulting audio does not show any hints of autotuning. I've tested this with multiple recordings and a simple sine sweep.

I wanted to implement a complete array of ref_freqs instead of using interpolation and a slider for autotune strength but couldnt notice any difference in the output. After a hard reset I can say that the initial autotune implementation simply doesnt do anything in the latest commit.

### Steps to reproduce

1. Start Applio
2. Load Audio File
3. Generate once with autotune enabled and once without it
4. Compare results

### Expected behavior

Autotune should snap the f0 curve to the grid.

**Comment by Chilluminati91** [comment]
Found the problem in pipeline.py line 389, should check for boolean instead of "True".

```
        if f0_autotune:
            f0 = Autotune.autotune_f0(self, f0)
```

**Comment by blaisewf** [comment]
would you like to open a pr about this?

**Comment by Chilluminati91** [comment]
I see you already fixed it, added a pr for the autotune strength slider now!
