### ISSUE TITLE
[Bug]: RVC-CLI "An error occurred during execution: run_infer_script() missing 36 required positional arguments"

### ISSUE THREAD

**Issue by tomakorea** [IAHispano/Applio#765]
### Project Version

3.2.6

### Platform and OS Version

Ubuntu

### Affected Devices

PC

### What happened?

When using a simple command line like in the example listed in the github doc page, there is an error : 

An error occurred during execution: run_infer_script() missing 36 required positional arguments: 'post_process', 'reverb', 'pitch_shift', 'limiter', 'gain', 'distortion', 'chorus', 'bitcrush', 'clipping', 'compressor', 'delay', 'reverb_room_size', 'reverb_damping', 'reverb_wet_gain', 'reverb_dry_gain', 'reverb_width', 'reverb_freeze_mode', 'pitch_shift_semitones', 'limiter_threshold', 'limiter_release_time', 'gain_db', 'distortion_gain', 'chorus_rate', 'chorus_depth', 'chorus_center_delay', 'chorus_feedback', 'chorus_mix', 'bitcrush_bit_depth', 'clipping_threshold', 'compressor_threshold', 'compressor_ratio', 'compressor_attack', 'compressor_release', 'delay_seconds', 'delay_feedback', and 'delay_mix'
Traceback (most recent call last):
  File "/home/johndoe/rvc-cli/rvc_cli.py", line 1679, in main
    run_infer_script(
TypeError: run_infer_script() missing 36 required positional arguments: 'post_process', 'reverb', 'pitch_shift', 'limiter', 'gain', 'distortion', 'chorus', 'bitcrush', 'clipping', 'compressor', 'delay', 'reverb_room_size', 'reverb_damping', 'reverb_wet_gain', 'reverb_dry_gain', 'reverb_width', 'reverb_freeze_mode', 'pitch_shift_semitones', 'limiter_threshold', 'limiter_release_time', 'gain_db', 'distortion_gain', 'chorus_rate', 'chorus_depth', 'chorus_center_delay', 'chorus_feedback', 'chorus_mix', 'bitcrush_bit_depth', 'clipping_threshold', 'compressor_threshold', 'compressor_ratio', 'compressor_attack', 'compressor_release', 'delay_seconds', 'delay_feedback', and 'delay_mix'

### Steps to reproduce

1. write a simple CLI command : python rvc_cli.py infer --pitch 0 --input_path "/media/temp/rec_0.wav" --output_path "/media/output/rec_0.wav" --pth_path "/media/Models_Vox/logs/voice1.pth" --index_path "/media/Models_Vox/logs/voice1.index"
2. Press Enter
3. Fail

### Expected behavior

It should continue and ignore the missing arguments because they aren't mandatory to infer.

**Comment by blaisewf** [comment]
@ShiromiyaG

**Comment by x4080** [comment]
I got the same error, is there any changes in rvc-cli code recently ?

**Comment by blaisewf** [comment]
try with applio core.py, is the same as rvc cli but updated, i have to sync applio changes

**Comment by tomakorea** [comment]
> try with applio core.py, is the same as rvc cli but updated, i have to sync applio changes

@blaisewf  Unfortunately I tried with Applio core.py and I got the same error :

Here is my CLI command for core.py :

`python core.py infer --pitch 2 --input_path "/media/john/PC_AI/1_Models_Vox/rec_0.wav" --output_path "/media/john/PC_AI/1_Models_Vox/output/rec_0.wav" --pth_path "/media/john/PC_AI/1_Models_Vox/logs/Ad_085.pth" --index_path "/media/john/PC_AI/1_Models_Vox/logs/Ad_085.index"`

Here is the result :

```
/home/john/Applio/core.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool

An error occurred during execution: run_infer_script() missing 36 required positional arguments: 'post_process', 'reverb', 'pitch_shift', 'limiter', 'gain', 'distortion', 'chorus', 'bitcrush', 'clipping', 'compressor', 'delay', 'reverb_room_size', 'reverb_damping', 'reverb_wet_gain', 'reverb_dry_gain', 'reverb_width', 'reverb_freeze_mode', 'pitch_shift_semitones', 'limiter_threshold', 'limiter_release_time', 'gain_db', 'distortion_gain', 'chorus_rate', 'chorus_depth', 'chorus_center_delay', 'chorus_feedback', 'chorus_mix', 'bitcrush_bit_depth', 'clipping_threshold', 'compressor_threshold', 'compressor_ratio', 'compressor_attack', 'compressor_release', 'delay_seconds', 'delay_feedback', and 'delay_mix'
Traceback (most recent call last):
  File "/home/john/Applio/core.py", line 1679, in main
    run_infer_script(
    
TypeError: run_infer_script() missing 36 required positional arguments: 'post_process', 'reverb', 'pitch_shift', 'limiter', 'gain', 'distortion', 'chorus', 'bitcrush', 'clipping', 'compressor', 'delay', 'reverb_room_size', 'reverb_damping', 'reverb_wet_gain', 'reverb_dry_gain', 'reverb_width', 'reverb_freeze_mode', 'pitch_shift_semitones', 'limiter_threshold', 'limiter_release_time', 'gain_db', 'distortion_gain', 'chorus_rate', 'chorus_depth', 'chorus_center_delay', 'chorus_feedback', 'chorus_mix', 'bitcrush_bit_depth', 'clipping_threshold', 'compressor_threshold', 'compressor_ratio', 'compressor_attack', 'compressor_release', 'delay_seconds', 'delay_feedback', and 'delay_mix'
```

**Comment by uberscientist** [comment]
I'm also getting the same error
