### ISSUE TITLE
[Feature]: Possibility of uploading one or various audios for validation before start training and displaying them on the tensorboard (during training)

### ISSUE THREAD

**Issue by Mixomo** [IAHispano/Applio#773]
### Description

Possibility to upload one or several audios for validation before start the training from the applio GUI and have them displayed in the tensorboard during the progress of the training, specifically in the audio data tab.
In this way, the user will be able to monitor how his model sounds through the progress of the steps and decide whether or not to finish the training.

### Problem

Not being able to easily and reliably check how the model sounds, because if one wants to make an inference during training, it often does not let you do it, or slows down the whole training, depending on the user's GPU.

![image](https://github.com/user-attachments/assets/7f468855-d260-409f-b125-42f1b985cfb1)

### Proposed Solution

I don't know if RVC in its code reserves some audios of the dataset for validation. If that is the case, to be able to show those audios of validation in tensorboard.
(although also the possibility of uploading custom audios would not be bad).

### Alternatives Considered

n/a

**Comment by blaisewf** [comment]
we are looking at something similar to that, ill update

**Comment by AznamirWoW** [comment]
@Mixomo you can grab the updated rvc/train/train.py from the repository and give it a try

**Comment by Mixomo** [comment]
@AznamirWoW It works like a charm! Thank you!

@blaisewf I don't know if you want to discuss anything else regarding this, or if not, you can close the issue. Thank you very much.

**Comment by blaisewf** [comment]
we will see ways to customize more the experience, but i think it's a good starting point

**Comment by kro-ai** [comment]
@AznamirWoW I would recommend having all audio in one place and having a slider to go to different steps, that's the way SVC used to do It If I remember correctly. Also, would it be possible to have the same audio inferenced? that way you can more easily compare between versions, and you could even have the "ground truth" below, which is just the raw file from the dataset, makes for easy comparison. Either way, great work! Makes training a lot easier when you can hear the progression as you are training!

**Comment by AznamirWoW** [comment]
It does not looks like slider is possible for audios.

if I use f"gen/audio_{global_step:07d}" it creates a new entry, if I use f"gen/audio" it overwrites the previous.

as for using a constant sample, yes thats possible.
