### ISSUE TITLE
[Bug]: Install UVR (MDX23)

### ISSUE THREAD

**Issue by NoRRt** [IAHispano/Applio#783]
### Project Version

3.2.6

### Platform and OS Version

Windows 64

### Affected Devices

all

### What happened?

After selecting the MDX model :

![Untitled](https://github.com/user-attachments/assets/29e3655d-fe7d-4f8d-a767-ed8a409ca49c)

### Steps to reproduce

1. Run Applio
2.Install Plugin UVR
3. After selecting the MDX model 
...

### Expected behavior

.

**Comment by blaisewf** [comment]
![{EA17C175-510D-4A03-B331-6A5CAE7BABAF}](https://github.com/user-attachments/assets/ce425d72-35be-4ec1-9c7d-a9dffa7282cf)

please... re open an issue following the template
