### ISSUE TITLE
[Bug]: UnboundLocalError: local variable 'loss_gen_all' referenced before assignment

### ISSUE THREAD

**Issue by ZeroCool22** [IAHispano/Applio#785]
### Project Version

3.2.6

### Platform and OS Version

Windows 10 64 bits.

### Affected Devices

PC Desktop

### What happened?

```
Theme Applio successfully loaded.
Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
Starting preprocess with 24 processes...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:24<00:00, 24.83s/it]
Preprocess completed in 24.83 seconds on 00:14:57 seconds of audio.
Starting pitch extraction with 24 cores on cuda:0 using rmvpe...
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]An error occurred extracting file C:\Applio\logs\Milei\sliced_audios_16k\0_0_0.wav on cuda:0: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.04s/it]
Pitch extraction completed in 5.98 seconds.
Starting embedding extraction with 24 cores on cuda:0...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it]
Embedding extraction completed in 7.00 seconds.
Starting training...
Loaded pretrained (G) 'rvc/models/pretraineds/pretrained_v2/f0G40k.pth'
Loaded pretrained (D) 'rvc/models/pretraineds/pretrained_v2/f0D40k.pth'
Milei | epoch=1 | step=0 | time=09:17:56 | training_speed=0:00:00
Process Process-1:
Traceback (most recent call last):
  File "C:\Applio\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Applio\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Applio\rvc\train\train.py", line 494, in run
    train_and_evaluate(
  File "C:\Applio\rvc\train\train.py", line 968, in train_and_evaluate
    last_loss_gen_all = loss_gen_all
UnboundLocalError: local variable 'loss_gen_all' referenced before assignment
Saved index file 'C:\Applio\logs\Milei\added_Milei_v2.index'
```

### Steps to reproduce

1. 
2. 
3. 
...

### Expected behavior

Start training.

### Screenshots or Videos

![Screenshot_9](https://github.com/user-attachments/assets/426f5b31-2f2d-452d-9e4d-97b8a02fdf90)

### Additional Information

```
C:\Applio>git log -n 1
commit 2062949e570c97ef1319bdd991afeebed60e5f17 (HEAD -> main, origin/main, origin/HEAD)
Merge: 393cf0d ce5864c
Author: 帕斯卡 <blaise@applio.org>
Date:   Fri Oct 4 18:53:49 2024 +0200

    Merge pull request #782 from AznamirWoW/audio_tensorboard

C:\Applio>
```

**Comment by ZeroCool22** [comment]
I did a:

**git checkout 1b935bd9764f5b6e80d6344907f02291581b1a35**

![Screenshot_10](https://github.com/user-attachments/assets/c60e53c6-cd84-49f1-a451-1f1b5ff50945)

And now the training start correctly, so **something is wrong with the last commit**?

**Comment by AznamirWoW** [comment]
Slice that 15 min audio in prepare dataset, make sure pitch and feature extraction produce something and you actually train on a valid set of samples.

**Comment by AznamirWoW** [comment]
> And now the training start correctly, so **something is wrong with the last commit**?🤔

There's nothing wrong with your commit. You did not slice the audio and the 15 minute wav was just too big to be used for training. It did not fit into any buckets and was tossed out, so you had nothing in the training set.

**Comment by ZeroCool22** [comment]
> > And now the training start correctly, so **something is wrong with the last commit**?🤔
> 
> There's nothing wrong with that commit. You did not slice the audio and the 15 minute wav was just too big to be used for training. It did not fit into any buckets and was tossed out, so you had nothing in the training set.

But, why with the old commit, it start just fine?

**Comment by AznamirWoW** [comment]
> > > And now the training start correctly, so **something is wrong with the last commit**?🤔
> > 
> > 
> > There's nothing wrong with that commit. You did not slice the audio and the 15 minute wav was just too big to be used for training. It did not fit into any buckets and was tossed out, so you had nothing in the training set.
> 
> But, why with the old commit, it start just fine?

With the old commit you did something differently - you sliced the file, I can see it by outputs from feature extraction showing 366/366 processed files instead of 1/1.

**Comment by ZeroCool22** [comment]
> > > > And now the training start correctly, so **something is wrong with the last commit**?🤔
> > > 
> > > 
> > > There's nothing wrong with that commit. You did not slice the audio and the 15 minute wav was just too big to be used for training. It did not fit into any buckets and was tossed out, so you had nothing in the training set.
> > 
> > 
> > But, why with the old commit, it start just fine?
> 
> With the old commit you did something differently - you sliced the file, I can see it by outputs from feature extraction showing 366/366 processed files instead of 1/1.

I see, the problem was i unchecked this options:

![Screenshot_11](https://github.com/user-attachments/assets/06ae3c6b-4b0c-4895-8dd7-44f34b527a2d)

When this can be unchecked, when we resume a training?

**Comment by AznamirWoW** [comment]
> When this can be unchecked, when we resume a training?

When you resume training you skip preprocess and feature extraction steps. Just pick the same options at the top and same options for training, but uncheck Sync Graph.

**Comment by ZeroCool22** [comment]
> > When this can be unchecked, when we resume a training?
> 
> When you resume training you skip preprocess and feature extraction steps. Just pick the same options at the top and same options for training, but uncheck Sync Graph.

Thx.

**Comment by ZeroCool22** [comment]
> > When this can be unchecked, when we resume a training?
> 
> When you resume training you skip preprocess and feature extraction steps. Just pick the same options at the top and same options for training, but uncheck Sync Graph.

Question, i just resume a training (choose same options), but it shows:

![Screenshot_13](https://github.com/user-attachments/assets/48dbf4d2-91b1-4584-9176-d87bd2ff2ef9)

Shouldn't it continue from the **last epoch and step** when it was interrupted?

**Comment by AznamirWoW** [comment]
> Shouldn't it continue from the **last epoch and step** when it was interrupted?

It resumes from the last _saved_ epoch. If you choose 'Save every 50 epochs' and stop training at epoch 30 before it saves the results, you restart from 0.

**Comment by ZeroCool22** [comment]
> > Shouldn't it continue from the **last epoch and step** when it was interrupted?
> 
> It resumes from the last _saved_ epoch. If you choose 'Save every 50 epochs' and stop training at epoch 30 before it saves the results, you restart from 0.

Got it, thx again.
