### ISSUE TITLE
[Bug]: Long texts cant be used for TTS

### ISSUE THREAD

**Issue by Illaren** [IAHispano/Applio#807]
### Project Version

3.2.6

### Platform and OS Version

Windows 11 Pro; Firefox 

### Affected Devices

Windows 11 Pro; Firefox 131.0.2

### What happened?

Traceback (most recent call last):
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\babu2\Downloads\Applio-3.2.6\core.py", line 383, in run_tts_script
    subprocess.run(command_tts)
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 206] The filename or extension is too long

### Steps to reproduce

Use a big text for TTS.

Even though i have 

"Split the audio into chunks for inference to obtain better results in some cases.
Split Audio"   
enabled it does not split the long text into handable text chunks.

If i try to covert the audiobook chapter by chapter it is woprking but if i put in the complete audiobook it does hand out the error in the "What happend" part.

Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem and edit LongPathsEnabled
is already set to 1

### Expected behavior

Suggested solution:

If a long text is used as an input split it up into handable chunks fist before the augment is given to the converter since it seems the the file system in windows can not handle more than  ~~32.000 characters

**Comment by AznamirWoW** [comment]
Please explain how are you running TTS?

**Comment by Illaren** [comment]
Starting run-applio.bat => clicking on TTS in the webbrowser window => "File to Speech" => uploading my textfile => Advanced Settings => activate "Split Audio" => Convert

Works like a charm if i only have one Chapter of the book in the txt file; if i have the complete book in the txt file it gives the error.

--------

Same problem if i copy and paste the text into the "Text to Speech"

**Comment by AznamirWoW** [comment]
Yeah, since the text is passed as a parameter in the command line, it can not be that long.
I can only suggest using a standalone script like this

```import time
import asyncio
import edge_tts
import rvc.lib.zluda
from rvc.infer.infer import VoiceConverter

#tts settings
input_text = "test_edge_tts.txt"
text = ""
speaker = "en-GB-RyanNeural"
rate = 0
#infer settings
pth_path = r"G:\ApplioV3.2.6\logs\model\model.pth"
index_path = r"G:\ApplioV3.2.6\logs\model\model.index"
input_path = r"F:\TTS_OUT\tts_out.wav"
output_path = r"F:\TTS_OUT\infer_out.wav"

async def main():
    rates = f"+{rate}%" if rate >= 0 else f"{rate}%"
    start_time1 = time.time()
    await edge_tts.Communicate(text,speaker,rate=rates,).save(input_path)
    elapsed_time = time.time() - start_time1
    print(f"TTS gen time in {elapsed_time:.2f} seconds.")

if __name__ == "__main__":

    with open(input_text, 'r') as file:
        text = file.read()

    asyncio.run(main())

    start_time1 = time.time()
    infer_pipeline = VoiceConverter()
    infer_pipeline.convert_audio(audio_input_path=input_path,audio_output_path=output_path,model_path=pth_path,index_path=index_path,split_audio=True)
    elapsed_time = time.time() - start_time1
    print(f"Inference time in {elapsed_time:.2f} seconds.")
```

**Comment by Illaren** [comment]
Sorry i am a bit to stupid to work with this as it seems. 

I can understand that 
"    with open(input_text, 'r') as file:
        text = file.read()    "

means that the txt file itself is given over to the converter  but i am not sure how to implement this  (not a programmer but at least i can read at bit english; just a dumb user here)

**Comment by AznamirWoW** [comment]
you save this script as run_tts.py and run it from applio folder using `env\python run_tts.py'

The script reads "test_edge_tts.txt" file with the text content to convert using "en-GB-RyanNeural" speaker (you can change it to some other you can find on Applio TTS screen.

`pth_path = r"G:\ApplioV3.2.6\logs\model\model.pth"
index_path = r"G:\ApplioV3.2.6\logs\model\model.index"
input_path = r"F:\TTS_OUT\tts_out.wav"
output_path = r"F:\TTS_OUT\infer_out.wav"

you need to change these and they are
1) path to the model.ptl
2) path to the model's index file
3) temporary file to save the tts output
4) final file after conversion

**Comment by Illaren** [comment]
Thank you very mutch for helping out. Still not working. I think i got the variables right. (See screenshot)


PS C:\Users\babu2\Downloads\Applio-3.2.6> env\python run_tts.py

C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\babu2\Downloads\Applio-3.2.6\run_tts.py", line 29, in <module>
    asyncio.run(main())
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\babu2\Downloads\Applio-3.2.6\env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\babu2\Downloads\Applio-3.2.6\run_tts.py", line 19, in main
    start_time1 = time.time()
NameError: name 'time' is not defined


![grafik](https://github.com/user-attachments/assets/9cf37a1e-f754-4d62-8bb7-89663162bba4)

**Comment by AznamirWoW** [comment]
> Thank you very mutch for helping out. Still not working. I think i got the variables right. (See screenshot)

sorry, copy-pasted without one line
add `import time` at the top

**Comment by Illaren** [comment]
Works perfectly now! Thank you!

So now how do we import the solution into the main project so that users like me (woh want to convert their own audiobooks for hearing in public transport) can use it out of the web interface without problems :)

**Comment by AznamirWoW** [comment]
> Works perfectly now! Thank you!
> 
> So now how do we import the solution into the main project so that users like me (woh want to convert their own audiobooks for hearing in public transport) can use it out of the web interface without problems :)

Consider TTS in Applio as a demo of what can be done. Edge TTS is not the best option out there, but it allows you to run local inference with a local model, unlike 11Labs.

**Comment by Illaren** [comment]
Can we somehow integrate this solution into the main GUI (Website) to make it a bit more userfriendly? I mean it works perfectly.

**Comment by AznamirWoW** [comment]
made the change #814, hopefully will be in the next build
