### ISSUE TITLE
[Bug]: Pre-Process - CPU Cores

### ISSUE THREAD

**Issue by Jarbrain** [IAHispano/Applio#811]
### Project Version

3.2.6

### Platform and OS Version

Windows 10 64-bits

### Affected Devices

PC

### What happened?

I was starting to train a new voiceover model. I set up the Model name and selected the sampling rate. Give the Dataset Path to the source audio files to train the software and try to start the Pre-Process Dataset button. From the front-end interface, it says the first stage of training was completed, but the back end of the terminal informed that the training has failed or error.

After messing around, I found out that the CPU cores (In Advanced Settings) were set at 64, which was causing the issue. So I set it down to 50 CPU and it seems to fix the issue in the back end of the terminal. Then I could move on to the next stage of the training with no problems beyond this point.

### Steps to reproduce

1. Setup the Model name,
2. Select sampling rate,
3. Give the Dataset Path to source audio files
4. Start the Pre-Process Dataset button
...

### Expected behavior

On default, the CPU cores set at 64 should work but the back-end terminal highlights an error.

**Comment by blaisewf** [comment]
> but the back-end terminal highlights an error

if you don't provide the error...

**Comment by Jarbrain** [comment]
I'll provide the error message when I've finished model training. Not going to stop it for one image. ;)
I'll send it as soon as possible, once it's completed.

**Comment by Jarbrain** [comment]
> > but the back-end terminal highlights an error
> 
> if you don't provide the error...

![image](https://github.com/user-attachments/assets/b3bbb2ee-ba4c-4db6-8a63-75e3e3691132)

Here's a screen grab of it

**Comment by AznamirWoW** [comment]
> Here's a screen grab of it

if you think having 64 processes would somehow improve the performance on a PC that has no 64 cpu cores....

use 8 or 16.. it does not make much difference

**Comment by Jarbrain** [comment]
@AznamirWoW 
I think you missed the point... Your average user may not understand that or be able to read the terminal information window. They may not understand how to adjust the advanced settings to fix the problem. 

Wouldn't it make more sense to have the software automatically check on the availability of the CPU on the computer make the adjustments, and/or reduce the settings to 30 CPU instead of the default 64? If the CPU power isn't needed at the Pre-Process stage of training voiceover content?

I would consider this as a bug as it's not working on a default setup of the software; hence getting in touch and reporting it to you.

**Comment by AznamirWoW** [comment]
This is very strange. I've tested this number just to see how high can it go and I was able to run it with 64 cores at some points. But this is not a number that should be popping as a default, so I wonder how do you run it? What CPU?

Certainly the default limit should be lowered to some reasonable value. Most people never need so many processes as they just run one or two files as a source.

**Comment by AznamirWoW** [comment]
should be fixed in the next build

**Comment by Jarbrain** [comment]
> This is very strange. I've tested this number just to see how high can it go and I was able to run it with 64 cores at some points. But this is not a number that should be popping as a default, so I wonder how do you run it? What CPU?
> 
> Certainly the default limit should be lowered to some reasonable value. Most people never need so many processes as they just run one or two files as a source.

I simply upload the files that I want the software to train on and select the first button in the training segment of the tool. I don't change any of the settings, apart from the CPU cores to overcome the issue as mentioned.

The odd thing about the CPU; it works in the other segments of the training page... Where the default is set at 64, it's just odd how it doesn't work in the first stage of training. 

Either way, lets hope this report will solve and help with development. Thank you for your time!
