### ISSUE TITLE
[Feature]: Colour buttons

### ISSUE THREAD

**Issue by Jarbrain** [IAHispano/Applio#812]
### Description

Use different colours for the different buttons to stand out from the rest of the interface.
The buttons are coloured Yellow to stand out from the black interface. Once the task is completed for example the Pro-Process Dataset... The button will change to green with a tick icon to help inform the users, the task is completed.

Also, make the interface into two columns, instead of one long column for desktop users for PC and MAC.

### Problem

This will help find the buttons for each segment of the software, either training at different stages. 

### Proposed Solution

Introduce different colour systems on all buttons.
Yellow = Waiting on data from the user,
Green = Task is completed or moves onto the next stage.
Red = Error has been detached.

### Alternatives Considered

***

**Comment by aris-py** [comment]
make a theme: https://www.gradio.app/guides/theming-guide

**Comment by blaisewf** [comment]
yes, you can do a theme, we support all gradio themes for own customization
