### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Cyl0nius** [IAHispano/Applio#815]
### Project Version

3.2.6

### Platform and OS Version

Windows 10/64bit, Chrome 129.0.6668.100

### Affected Devices

Desktop

### What happened?

In TTS any generated output is not available on Web-UI ...
BUT in C:\ApplioV3.2.6\assets\audios

### Steps to reproduce

TTS
Enter any text you want to convert to speech
After conversion is finished, in Export-Audio-Box is nothing to see/play

The generated audio-file is available in C:\ApplioV3.2.6\assets\audios as tts_output.wav

### Expected behavior

The generated audio-file should be playable from Export-Audio-Box in Web-UI

### Attachments

TTS with en-US-EmmaNeural completed. Output TTS file: 'C:\ApplioV3.2.6\assets\audios\tts_output.wav'
Converting audio 'C:\ApplioV3.2.6\assets\audios\tts_output.wav'...
An error occurred during audio conversion: 'NoneType' object has no attribute 'pipeline'
Traceback (most recent call last):
  File "C:\ApplioV3.2.6\rvc\infer\infer.py", line 296, in convert_audio
    audio_opt = self.vc.pipeline(
AttributeError: 'NoneType' object has no attribute 'pipeline'

**Comment by AznamirWoW** [comment]
You forgot to select a voice model at the top

**Comment by Cyl0nius** [comment]
> You forgot to select a voice model at the top

You are right, problem solved.

I didn't think anything would be missing because an audio file was generated.
