### ISSUE TITLE
won't install on manjaro, this is feedback not tech support request

### ISSUE THREAD

**Issue by Innomen** [IAHispano/Applio#819]
I don't care enough to spend an hour filling this out and fighting it. Manjaro linux. Bottom line of a screen full of errors:   File "/tmp/pip-build-env-9owqs_4_/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

Also super annoying that the install sh makes changes such that I can't rerun it, I have to delete the folder, git clone it again and chmod/run it each time. I give up. Good luck with your project.

**Comment by Innomen** [comment]
Could the install SH be handled to offer that option? Thanks though but really don't put yourself out, I'm in extreme low effort mode, you should be in zero effort mode :)

**Comment by blaisewf** [comment]
why not just installing python 3.10?

**Comment by aris-py** [comment]
Use Python 3.10.12, install it with pyenv :)
