### ISSUE TITLE
[Feature]: Where is the "Use via API" button? Why was it deleted?...

### ISSUE THREAD

**Issue by Juranik** [IAHispano/Applio#826]
### Description

Please add it so that you can use the API again

### Problem

There is no "Use via API" button

### Proposed Solution

Just bring the API back

### Alternatives Considered

No

**Comment by blaisewf** [comment]
no, we don't support gradio api if you want to use via api you can build one using the core.py CLI

**Comment by Juranik** [comment]
> no, we don't support gradio api if you want to use via api you can build one using the core.py CLI

What does it mean that you don't support the Gradio API if the Gradio Interface opens there? I will use the API locally, not yours.
