### ISSUE TITLE
[Bug]: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by WiryBarley119** [IAHispano/Applio#829]
### Project Version

3.2.6

### Platform and OS Version

Windows 10

### Affected Devices

All

### What happened?

I tried to convert my previously trained RVC models to an audio file. But when I try to convert it, I get an error and I don't know why. I tried restarting my computer but it doesn't help. And I tried everything to fix this error

### Steps to reproduce

1. Restarted my computer
2. Clicked on convert
3. Tried to move Applio folder to local disc (C:)

### Expected behavior

The conversion should worked correctly

### Screenshots or Videos

![Error Applio](https://github.com/user-attachments/assets/8a54de55-ff75-4149-93e6-d96f44d3292a)
![Error Applio 2](https://github.com/user-attachments/assets/b69819e3-8ba3-412c-93a5-91729c8bef9d)

### Additional Information

Can someone help me how to fix this please?

**Comment by blaisewf** [comment]
make sure that you've selected a model, upload again your audio etc. it's likely a gradio bug
