### ISSUE TITLE
[Bug]: During training, the console displays incorrect values for the epoch and step count in brackets.

### ISSUE THREAD

**Issue by StellarBeing25** [IAHispano/Applio#830]
### Project Version

3.2.6

### Platform and OS Version

Windows 11

### Affected Devices

All

### What happened?

During training, the console displays incorrect values for the epoch and step count in brackets.

### Steps to reproduce

Train a voice model.

### Expected behavior

Console should either show correct values for the epoch and step count in brackets or should not show the brackets part at all.

### Screenshots or Videos

![SS1](https://github.com/user-attachments/assets/aa4d2dc7-4be3-4fc5-8fca-cae94f2e771f)

**Comment by AznamirWoW** [comment]
you've highlighted the epoch and step with the lowest loss value, not the current epoch

**Comment by StellarBeing25** [comment]
OK, I didn't realize that the values in brackets are not the current epoch and step count, but rather the epoch and step with the lowest loss value. Thank you for the clarification.
