### ISSUE TITLE
[Bug]: Connection error

### ISSUE THREAD

**Issue by JERBCO78** [IAHispano/Applio#832]
### Project Version

3.2.3

### Platform and OS Version

windows 11

### Affected Devices

pc

### What happened?

dosent work

### Steps to reproduce

1. click anything
2. 
3. 
...

### Expected behavior

work

### Screenshots or Videos

[recording.webm](https://github.com/user-attachments/assets/e00c38d6-937c-46f5-986d-99b7c8e0ec0a)

**Comment by AznamirWoW** [comment]
why you're trying to use 3.2.3 version, I assume installing it from scratch, instead of downloading a prebuilt latest version?

**Comment by blaisewf** [comment]
use last compiled version
