### ISSUE TITLE
[Bug]: I get an error all of a sudden when trying to convert.

### ISSUE THREAD

**Issue by hiiggghhh** [IAHispano/Applio#834]
### Project Version

 3.2.5

### Platform and OS Version

Mac 

### Affected Devices

MacBook Pro 

### What happened?

any idea why in Appalio now i get a error when i go to convert?  it loads my model right, uploads the vocal sample fine, all that but for some reason now when i hit covert it runs for a coupel seconds and then error, tried a few different things. I am running it as a clone google colab plus, i did run out of money (compute units) but i toppped up, still not working.

### Steps to reproduce

1. hit convert
2. 
3. 
...

### Expected behavior

no 

### Attachments

<img width="1210" alt="Screenshot 2024-10-25 at 1 41 20 PM" src="https://github.com/user-attachments/assets/5456fd13-7a0a-4a56-8a08-ecd8a0b0b17b">

**Comment by blaisewf** [comment]
follow the report template, provide cmd logs
