### ISSUE TITLE
 [Bug]:  MacOS slow infererence

### ISSUE THREAD

**Issue by Anthonyxd22** [IAHispano/Applio#841]
### Project Version

3.2.6

### Platform and OS Version

MacOS

### Affected Devices

M1 M2

### What happened?

dura mucho para hacer una inferencia de un audio de 5 o 10 segundos y no utilizar mps backend para acelerar cpu

### Steps to reproduce

<img width="1312" alt="Screenshot 2024-10-26 at 11 29 44 AM" src="https://github.com/user-attachments/assets/e8aa323f-d730-4eaa-8999-28ca3c6fee09">

### Expected behavior

idk

### Attachments

nothing
<img width="567" alt="Screenshot 2024-10-26 at 11 31 19 AM" src="https://github.com/user-attachments/assets/adfe4492-8022-4c6c-93ef-29c7c9a00e14">

**Comment by Anthonyxd22** [comment]
<img width="1317" alt="Screenshot 2024-10-26 at 1 05 24 PM" src="https://github.com/user-attachments/assets/63364259-24fc-4b2a-b865-83ef3d69c3ad">

**Comment by BornSaint** [comment]
#836 on Windows too

**Comment by blaisewf** [comment]
answered on the other issue
