### ISSUE TITLE
Can you open the "rvc-cli" repo (issues or discussions) please?

### ISSUE THREAD

**Issue by GPU-server** [IAHispano/Applio#843]
### Description

I would like to comment there. It would be good to have people being able to share info and discuss there.
Thanks

### Problem

.

### Proposed Solution

.

### Alternatives Considered

.

**Comment by blaisewf** [comment]
no, i don't have time to check both repos, here you can comment the same things because applio uses the same cli system

**Comment by GPU-server** [comment]
I had a question about RVC to be honest. I want to ask in any RVC place I find, In HOPE i get an asnwer.

**Comment by blaisewf** [comment]
then you have our discord community AI Hispano

**Comment by GPU-server** [comment]
> then you have our discord community AI Hispano

Do you have a link please? (invite)

**Comment by bygimenez** [comment]
> > then you have our discord community AI Hispano
> 
> Do you have a link please? (invite)

https://discord.gg/iahispano
