### ISSUE TITLE
[Bug]: Training ultra slow

### ISSUE THREAD

**Issue by BornSaint** [IAHispano/Applio#852]
### Project Version

3.2.6

### Platform and OS Version

Linux x64

### Affected Devices

PC

### What happened?

From some updates to now the train script changed a bit, and now it is saving every epoch with "best" in the name, which is annoying. 
--save_only_latest
and
--save_every_weights 
and
--save_every_epoch 20
doesn't make any change

### Steps to reproduce

1. 
2. 
3. 
...

### Expected behavior

save_every_epoch 20

**Comment by AznamirWoW** [comment]
you're running it with overtraining detector, that's the only thing that saves _best epoch.
there's minimal peformance loss from that

**Comment by BornSaint** [comment]
> you're running it with overtraining detector, that's the only thing that saves _best epoch. there's minimal peformance loss from that

I tried it, but after disabling it continues doing this savings

**Comment by BornSaint** [comment]
downloaded the project updated and it's okay now
