### ISSUE TITLE
[Bug]: An error appears during learning.

### ISSUE THREAD

**Issue by jooa01010101** [IAHispano/Applio#863]
### Project Version

3.2.6

### Platform and OS Version

window 11

### Affected Devices

window 11

### What happened?

An error appears during learning.

log:
Starting training...
Loaded pretrained (G) 'rvc\models\pretraineds\pretraineds_custom\G_KLM42_T4_40k.pth'
Loaded pretrained (D) 'rvc\models\pretraineds\pretraineds_custom\D_KLM42_T4_40k.pth'
oooo | epoch=1 | step=0 | time=13:36:29 | training_speed=0:00:00
Process Process-1:
Traceback (most recent call last):
  File "E:\AI\Applio-3.2.6\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "E:\AI\Applio-3.2.6\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\AI\Applio-3.2.6\rvc\train\train.py", line 494, in run
    train_and_evaluate(
  File "E:\AI\Applio-3.2.6\rvc\train\train.py", line 961, in train_and_evaluate
    last_loss_gen_all = loss_gen_all
UnboundLocalError: local variable 'loss_gen_all' referenced before assignment
An error occurred extracting the index: need at least one array to concatenate
If you are running this code in a virtual environment, make sure you have enough GPU available to generate the Index file.

Graphics card GeForce 4090.

### Steps to reproduce

1. Starting training...
2. Process Process-1:
3. UnboundLocalError:
...

### Expected behavior

There must be training

**Comment by AznamirWoW** [comment]
Look like you skipped steps on the training screen.
