### ISSUE TITLE
Question about the `torch` version

### ISSUE THREAD

**Issue by Bebra777228** [IAHispano/Applio#864]
Could you please explain why Applio uses `torch==2.3.1` instead of `torch==2.5.0` or `2.4.*`? What are the advantages of version `2.3.1`?

**Comment by AznamirWoW** [comment]
> Could you please explain why Applio uses `torch==2.3.1` instead of `torch==2.5.0` or `2.4.*`? What are the advantages of version `2.3.1`?

what's the advantages of a bugged 2.5.0?

We've updated to 2.3.1 because 1) its performance in training was better than 2.1.1 and 2) it is the version compatible with Zluda emulator for AMD

**Comment by Bebra777228** [comment]
Okay, thanks for the answer!

**Comment by AznamirWoW** [comment]
You can update the respective modules to 2.5.0 or 2.5.1, I'd expect a lot of warnings about deprecated stuff and loading unsafe .pth.
