### ISSUE TITLE
[Feature]: Change path of log folder?

### ISSUE THREAD

**Issue by IndustrialOne** [IAHispano/Applio#865]
### Description

Is it possible to change the path of the log folder where the epochs will be saved? I already ran out of disk space on the VM I have Applio running in. I'd like to have the log file on a disk I have substantial free space on.

### Problem

Disk space.

### Proposed Solution

Allow us to change the path in settings.

### Alternatives Considered

I tried making a junction point but I failed.

**Comment by blaisewf** [comment]
why not just moving applio to that disk?

**Comment by AznamirWoW** [comment]
You can make a symlink for either a single model or the entire log folder
![image](https://github.com/user-attachments/assets/5d81648a-276f-42e8-82ea-33dbcc28180d)

**Comment by IndustrialOne** [comment]
> You can make a symlink for either a single model or the entire log folder ![image](https://private-user-images.githubusercontent.com/101997116/383324336-5d81648a-276f-42e8-82ea-33dbcc28180d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDUxNTcsIm5iZiI6MTczMDkwNDg1NywicGF0aCI6Ii8xMDE5OTcxMTYvMzgzMzI0MzM2LTVkODE2NDhhLTI3NmYtNDJlOC04MmVhLTMzZGJjYzI4MTgwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQxNDU0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWUxYWI0NmI4ODBlOWFjOGNmNGY4ODM0MDljM2VlMmYzMzY3M2VmYjA4ZTZjYTdkNmE3ZjFiZjhmOThkNjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zn4T6a-m0UNk063kdZPaLkyJyj-l6-uAepqNt9CyYrI)

Applio will write the real files to C:\Applio\Logs, not to symlinked D:\Logs, so that solves nothing.

I could just move Applio but the drive in question is intended for quick access to big files, not 20,000 tiny files. Most applications allow you to customize your temp/output folders so I expected as much from Applio. If there's no solution, I'm just gonna expand the VHD.

**Comment by AznamirWoW** [comment]
> > You can make a symlink for either a single model or the entire log folder ![image](https://private-user-
> Applio will write the real files to C:\Applio\Logs, not to symlinked D:\Logs, so that solves nothing.

Works fine.

![image](https://github.com/user-attachments/assets/295b7845-a1e7-403a-a297-2866365821e6)

![image](https://github.com/user-attachments/assets/84ffa8b0-c482-47b1-9530-9e89c45f2c10)

**Comment by AznamirWoW** [comment]
from Applio folder open command prompt as administrator and use
`mklink /D logs D:\logs`
