### ISSUE TITLE
[Feature]: save only small model

### ISSUE THREAD

**Issue by BornSaint** [IAHispano/Applio#873]
### Description

Instead of saving large models and small models or only large models

### Problem

When trying to save space, there's an option to not save all models, but this option saves only large models, which is not the best approach to save space, since D model is bit more than 800MB and G around 500MB, but small model is around 60MB

### Proposed Solution

Replace saving large models only to small models only

### Alternatives Considered

.

**Comment by AznamirWoW** [comment]
You can not resume training from a saved small model.

**Comment by BornSaint** [comment]
> You can not resume training from a saved small model.

Save last and when saving the next, delete previous

**Comment by BornSaint** [comment]
just used --save-last-only
