### ISSUE TITLE
[Question]: How to set up AMD GPU usage on linux

### ISSUE THREAD

**Issue by MalcolmReed-ent** [IAHispano/Applio#881]
Right now i'm using Applio 3.2.7 under a python 3.9 conda environment, and using the CPU is fine but I have just acquired an RX 550x and I would like to offload some of the tasks towards it. I noticed that there is setup documentation for AMD GPU on windows but how do I go about doing that on Linux, more specifically on Debian, Gentoo, or even Fedora?

**Comment by blaisewf** [comment]
zluda method is for windows, maybe you can try alternatives like rocm. @AznamirWoW is the amd expert

**Comment by AznamirWoW** [comment]
Linux install requires ROCm 5.2(?), but it is not something I've ever tried. Besides RX550 will be mostly useless.

**Comment by aris-py** [comment]
ZLUDA is compatible with Linux, in fact it tells you how to use it in the official repo.
