### ISSUE TITLE
[Bug]: UnboundLocalError: local variable 'reference' referenced before assignment

### ISSUE THREAD

**Issue by AirJCovers34** [IAHispano/Applio#882]
### Project Version

3.2.7

### Platform and OS Version

Windows 10 64bits

### Affected Devices

PC

### What happened?

Since my update to 3.2.7, during training execution, I receive the error:
UnboundLocalError: local variable 'reference' referenced before assignment

### Steps to reproduce

1. Run training
2. 
3. 
...

### Expected behavior

Launching training without errors.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/b6ad53fa-fd62-488f-8428-ed718c39c611)

**Comment by blaisewf** [comment]
![{E5B4BDC5-0B3D-4E33-91D0-D4754E209F6C}](https://github.com/user-attachments/assets/6ab7fbba-76cf-4da6-9d8c-01cdb328c2f6)

works fine here
