### ISSUE TITLE
[Bug]: Applio not running after setup on macOS

### ISSUE THREAD

**Issue by fdezwonders** [IAHispano/Applio#886]
### Project Version

3.2.7

### Platform and OS Version

macOS Sequoia 15.1.1 (24B91)

### Affected Devices

MacBook Pro 14-inch, 2021 (M1 Pro)

### What happened?

Video is below for context, but whenever I run the install.sh file, and then I run the run-applio.sh file, I get an error saying Gradio is not installed:
`Traceback (most recent call last):
  File "/Users/**_my name_**/gitclones/Applio-3.2.7/app.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'`

### Steps to reproduce

1. Get the 3.2.7 .sh file from the [GitHub releases](https://github.com/IAHispano/Applio/releases).
2. Extract the zip file.
3. `cd` into the directory into which the Applio folder is
4. Run `chmod +x run-install.sh ./run-install.sh`
5. Run `chmod +x run-applio.sh ./run-applio.sh`
6. Get the error.

### Expected behavior

Run Applio.

### Screenshots or Videos

Video of installtion:
https://mega.nz/file/4iUj0C4Q#EdxqCHx70f4pyg6cNI899hLD3ZZIIIaTm6HC92_X-L8
(blurred my name out for privacy)

**Comment by fdezwonders** [comment]
@Anthonyxd22 I have Python 3.10.10.
![Screenshot 2024-11-27 at 7 18 59 AM](https://github.com/user-attachments/assets/d5267fd3-46d7-41a1-a0e2-f667cd2d3d5e)
(name blurred out for privacy)

**Comment by AznamirWoW** [comment]
So the requirement failed to install (with a reason you cut off the screenshot), but you try to run the application anyway, get an error about the missing requirement and now it is somehow applio's bug?

**Comment by Anthonyxd22** [comment]
It's better to reinstall Applio because it works perfectly for me. I'll try to fix this error anyway.

**Comment by Anthonyxd22** [comment]
You can also download the modules manually https://docs.google.com/document/d/10ZyhkaJGdoa_M7QVUmlNSe94brAYG1BusKS4EHTrtwc/edit?tab=t.0

**Comment by fdezwonders** [comment]
Now it works! Turns out: **I didn't have Xcode installed**, which was the most likely issue. Applio works fine now.
![Screenshot 2024-11-29 at 8 51 19 AM](https://github.com/user-attachments/assets/a52da306-71db-46a5-8705-d7a308ea550b)
