### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by julianpoelmann** [IAHispano/Applio#887]
### Project Version

3.2.7

### Platform and OS Version

Windows 11 64Bit Pro for Workstations. Firefox 135.0a1 (2024-11-27) (64-bits)

### Affected Devices

Windows Machine x86

### What happened?

Launching run-applio-amd results in:

```
Traceback (most recent call last):
  File "H:\RVC\Applio\ApplioV3.2.7\app.py", line 19, in <module>
    import rvc.lib.zluda
  File "H:\RVC\Applio\ApplioV3.2.7\rvc\lib\zluda.py", line 1, in <module>
    import torch
  File "H:\RVC\Applio\ApplioV3.2.7\env\lib\site-packages\torch\__init__.py", line 143, in <module>
    raise err
OSError: [WinError 126] Kan opgegeven module niet vinden. Error loading "H:\RVC\Applio\ApplioV3.2.7\env\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
```

I have installed the full Rocm sdk. I've ran the toch uninstall and install command. I've ran zluda its bat file has been ran from applio's main folder (patch-zluda-hip61.bat)

`C:\Program Files\AMD\ROCm\6.1\bin` is added to system path under the name applio as i didnt see that i had to provide any specific name. 

i have an rx 6900xt Toxic LE non overclocked. idk what i did wrong here. the caffe2_nvrtc.dll is in the folder it looked for so i find that strange altough the lib folder is with a capital L?

### Steps to reproduce

1. install amd support according to instructions
2. patch using the files
3. error?
...

### Expected behavior

i expected applio to run. i followed the instructions and saw no errors when installing it

### Attachments

(ignore the selection in the explorer window, i didnt open that to get the window on the right)
![afbeelding](https://github.com/user-attachments/assets/2ee25fef-cc9b-446e-a5b2-102aa9658c7d)

**Comment by julianpoelmann** [comment]
normal applio also does not run now but before the amd support it did ran on my cpu which was slow but functional

**Comment by AznamirWoW** [comment]
> C:\Program Files\AMD\ROCm\6.1\bin is added to system path under the name applio as i didnt see that i had to provide any specific name.

system path is a system path. Not a standalone variable.

**Comment by julianpoelmann** [comment]
I think I'm misunderstanding. How would I add it?. Do I call it path?.. I went to advanced computer setting/environment variables and then added it to system, not user.

I'm not well traversed with python or path things so I'm sorry that I don't understand 🥲

**Comment by AznamirWoW** [comment]
Environment Variables:
![image](https://github.com/user-attachments/assets/6898d3b2-7b05-4962-b136-d8bc12b6d07e)

Edit path variable
![image](https://github.com/user-attachments/assets/1df64f17-dc46-4d45-b71e-958070d7f149)

**Comment by julianpoelmann** [comment]
that did it, it boots now. thank you!

ill try it out and see if it works on my card. currently its compiling. ill close the comment so it wont clog up the issues list

happy holidays
