### ISSUE TITLE
[Bug]: Cannot select pretrained models

### ISSUE THREAD

**Issue by genjonakasone** [IAHispano/Applio#890]
### Project Version

3.2.7

### Platform and OS Version

Windows 11 64bit, Pinokio

### Affected Devices

ALL

### What happened?

The application allows downloading pretrained models like Titan or KLM and they get downloaded (I see reduced disk space), however I am unable to select them in any of the tabs, be it Interference or TTS. Only voices added manually (through dropping the .pth and .index files) are shown in the selection dropdown. I looked into the files and it seems that only pth files are downloaded, with no indexes. If it matters, I installed Apollio through Pinokio.

### Steps to reproduce

1. Start Apollio through Pinokio (both most recent versions)
2. Go to Download tab, Download Pretrained Models, select any model in any sampling rate
3. Go to Interference or TTS tabs and try selecting any of the downloaded pretrained models.

### Expected behavior

Downloaded pretrained models should be shown in the dropdown to convert text or audio files.

**Comment by AznamirWoW** [comment]
pretrained models are used for training

**Comment by genjonakasone** [comment]
Alright, that would make sense. Closing the issue then, thanks for explanation.
