### ISSUE TITLE
[Bug]: Error de salida

### ISSUE THREAD

**Issue by Guardavida** [IAHispano/Applio#901]
### Project Version

3.2.7

### Platform and OS Version

mac

### Affected Devices

macbook pro

### What happened?

Cuando pongo convertir me indica el siguiente error "Valor: 0 no está en la lista de opciones:

### Steps to reproduce

1. cargo el modelo
2. adjunto la voz a modificar
3. convierto
...

### Expected behavior

desconozco

### Screenshots or Videos

<img width="1437" alt="Captura de pantalla 2024-12-04 a la(s) 3 42 54 p  m" src="https://github.com/user-attachments/assets/28bb1244-e177-44e6-aeaa-25a830647934">

### Additional Information

Puede ser que me este faltando agregar un paso y no es un error del programa..

**Comment by blaisewf** [comment]
estás usando otra versión de gradio, descarga de nuevo el repositorio con los nuevos cambios
