### ISSUE TITLE
[Feature]: Hello dear devs...I would suggest the feature...new...alg method...

### ISSUE THREAD

**Issue by Juranik** [IAHispano/Applio#909]
### Description

Pls add Mangio-Crepe, why crepe exists here..but non-exist Mangio-Crepe method?... becuz...mangio crepe its improved version of crepe, right?..

### Problem

nonenonenonenonenonenone

### Proposed Solution

pls add mangio-crepe in the future

### Alternatives Considered

nonenonenonenonenone

AND PLS RETURN USE VIA API, i hope u WILL!!...

**Comment by blaisewf** [comment]
mangio crepe is crepe, already implemented.

**Comment by Juranik** [comment]
> mangio crepe is crepe, already implemented.

oh okay. will u add then rmvpe_gpu?

**Comment by blaisewf** [comment]
rmvpe and crepe can already be used on gpu

**Comment by Juranik** [comment]
> rmvpe and crepe can already be used on gpu

oh k, I got it, sry for anxiery!
