### ISSUE TITLE
[Bug]:  i cant download my ai cover

### ISSUE THREAD

**Issue by yasieb** [IAHispano/Applio#913]
### Project Version

Applio 3.2.8 

### Platform and OS Version

windows 10 11

### Affected Devices

asus

### Existing Issues

error

### What happened?

i see a  error

### Steps to reproduce

1. i can import
2. i cant convert 
3.  i cant download 
... only train

### Expected behavior

i cant update by checking for updates

### Attachments

![Schermopname (1)](https://github.com/user-attachments/assets/064b73ff-bb21-4163-b949-c8dffe51f55e)

### Screenshots or Videos

[recording.webm](https://github.com/user-attachments/assets/8a2fd081-5930-4bda-91dd-651f7ad90a1e)

### Additional Information

i want to make ai vocal covers with the applio exe github file

**Comment by Vidalnt** [comment]
shows the console error, not just the gradio error, and also mentions the following:
- What link did you use to download the model, as most of the time they are out of date. 
- For the above, you do not have a model selected, so it leads to give error.

**Comment by yasieb** [comment]
ezmp3 and a  wav file

**Comment by Vidalnt** [comment]
> ezmp3 and a wav file

![image](https://github.com/user-attachments/assets/6a753906-f8b7-4af1-a3da-703e4bb4ab65)
"No model"
