### ISSUE TITLE
[Bug]: Miniconda installation failed.

### ISSUE THREAD

**Issue by Terraguy996** [IAHispano/Applio#917]
### Project Version

3.2.8

### Platform and OS Version

Windows 10, 64-bit

### Affected Devices

My Windows 10 PC

### Existing Issues

#1

### What happened?

I was not able to install the Applio because of missing miniconda error, installing miniconda manually didn't help the case either.

### Steps to reproduce

1. Run "run-install.bat"
2. "Miniconda not found"
...

### Expected behavior

I expected the app to be installed on my PC

### Attachments

& : Имя "C:\Users\user\anaconda3\Scripts\conda.exe" не распознано как имя командлета, функции, файла сценария или выпол
няемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите поп
ытку.
C:\Users\Администратор\Documents\WindowsPowerShell\profile.ps1:4 знак:4
+ (& "C:\Users\user\anaconda3\Scripts\conda.exe" "shell.powershell" "ho ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\user\a...ripts\conda.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### Screenshots or Videos

https://github.com/user-attachments/assets/75dc7f54-84e7-4a1f-89a5-4c18f0a7af38

**Comment by AznamirWoW** [comment]
1) Don't use admin account
2) use a compiled version unzipped to C:\Applio

**Comment by Terraguy996** [comment]
It worked, thank you!
