### ISSUE TITLE
[Bug]: Inference is unresponsive

### ISSUE THREAD

**Issue by wdkflag** [IAHispano/Applio#920]
### Project Version

The latest version

### Platform and OS Version

macos

### Affected Devices

14.0.1

### What happened?

When converting audio, the time keeps increasing but the conversion is not successful, and it does not work, and the command line prompts that the audio is being converted, but the conversion is not successful.  
![微信图片_20241222032845](https://github.com/user-attachments/assets/d34f628f-d3f8-47ee-a4d9-e32afcceca4b)

### Steps to reproduce

1. 
2. 
3. 
...

### Expected behavior

Appleo is a very powerful tool, and I hope the developers will be able to solve this problem, sorry, but I hope you can understand these translations

**Comment by wdkflag** [comment]
![Uploading 微信截图_20241222033055.png…]()

**Comment by blaisewf** [comment]
https://github.com/IAHispano/Applio/issues/869
