### ISSUE TITLE
[Bug]: Random (?) "TypeError: can't multiply sequence by non-int of type 'float'" when using Split Audio

### ISSUE THREAD

**Issue by IvanFromGardarike** [IAHispano/Applio#925]
### Project Version

3.2.8

### Platform and OS Version

Windows 11 x64, Brave, Firefox

### Affected Devices

PC

### What happened?

Sometime when i use Split Audio everything is fine.
But over time it's returns errors like:
`An error occurred during audio conversion: can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "F:\Applio\rvc\infer\infer.py", line 296, in convert_audio
    audio_opt = self.vc.pipeline(
  File "F:\Applio\rvc\infer\pipeline.py", line 601, in pipeline
    pitch, pitchf = self.get_f0(
  File "F:\Applio\rvc\infer\pipeline.py", line 387, in get_f0
    f0 *= pow(2, pitch / 12)
TypeError: can't multiply sequence by non-int of type 'float'`

Is where any fix of this? 

Additional info input is .wav and .flac files

### Steps to reproduce

1.Drop in file
2.Turn on Split Audio
3.Wait
4. ...
5. PROFIT (or not)

### Expected behavior

Somethin like this:

Audio split into 5 chunks for processing.
Converted audio chunk 1
Converted audio chunk 2
Converted audio chunk 3
Converted audio chunk 4
An error occurred during audio conversion: can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "F:\Applio\rvc\infer\infer.py", line 296, in convert_audio
    audio_opt = self.vc.pipeline(
  File "F:\Applio\rvc\infer\pipeline.py", line 601, in pipeline
    pitch, pitchf = self.get_f0(
  File "F:\Applio\rvc\infer\pipeline.py", line 387, in get_f0
    f0 *= pow(2, pitch / 12)
TypeError: can't multiply sequence by non-int of type 'float'

### Additional Information

Input is .wav and .flac files

**Comment by AznamirWoW** [comment]
can you share a file that fails?

**Comment by IvanFromGardarike** [comment]
> can you share a file that fails?

Okay, I'll zip up some problem files and send them over.

P.S. I'm using a translator. I apologize if it does not accurately convey the meaning.

**Comment by IvanFromGardarike** [comment]
And I forgot to mention that it happens on all algorithms.

**Comment by IvanFromGardarike** [comment]
[File with TypeError.zip](https://github.com/user-attachments/files/18240570/File.with.TypeError.zip)
File + Log from CMD

Converting audio 'assets\audios\1_4_Civil_War_-_Colours_on_My_Shield_Bonus_Track_Vocals_lead_only_No_Reverb.wav'...
Audio split into 16 chunks for processing.
Converted audio chunk 1
Converted audio chunk 2
Converted audio chunk 3
Converted audio chunk 4
Converted audio chunk 5
Converted audio chunk 6
Converted audio chunk 7
Converted audio chunk 8
Converted audio chunk 9
Converted audio chunk 10
Converted audio chunk 11
Converted audio chunk 12
An error occurred during audio conversion: can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "F:\Applio\rvc\infer\infer.py", line 296, in convert_audio
    audio_opt = self.vc.pipeline(
  File "F:\Applio\rvc\infer\pipeline.py", line 601, in pipeline
    pitch, pitchf = self.get_f0(
  File "F:\Applio\rvc\infer\pipeline.py", line 387, in get_f0
    f0 *= pow(2, pitch / 12)
TypeError: can't multiply sequence by non-int of type 'float'

> can you share a file that fails?

**Comment by AznamirWoW** [comment]
what's the command line parameters you're using?

![image](https://github.com/user-attachments/assets/fd70688d-91da-47d3-8d8d-75d3b7ec09d5)

**Comment by IvanFromGardarike** [comment]
> what's the command line parameters you're using?
> 
> ![image](https://private-user-images.githubusercontent.com/101997116/398438123-fd70688d-91da-47d3-8d8d-75d3b7ec09d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTQxNDMsIm5iZiI6MTczNTA1Mzg0MywicGF0aCI6Ii8xMDE5OTcxMTYvMzk4NDM4MTIzLWZkNzA2ODhkLTkxZGEtNDdkMy04ZDhkLTc1ZDNiN2VjMDlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjExZmRlOWU0MmY5YTU5MDRmMzE5NjI5Mzk5ZmQ0ZTBjYTYzOTQ3YzFkY2VkMWE0YzAxYjUwZDAzOWZhNGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bJ97loc9cGPPEJzvOW_dB9SYa6rqNjyXPvuWk0lgmt8)

I don't thin i use any. I downloaded the already compiled version from HugginFace and just unzipped to disk.

**Comment by AznamirWoW** [comment]
So the only thing you're doing is selecting a model, index, the file to infer and under advanced options you click Split Audio and you do not change any other setting?

**Comment by IvanFromGardarike** [comment]
> So the only thing you're doing is selecting a model, index, the file to infer and under advanced options you click Split Audio and you do not change any other setting?

As far as I noticed neither the choice of model nor changing other parameters does not particularly affect the frequency of error occurrence.

Sometimes it happens sometimes it doesn't

**Comment by IvanFromGardarike** [comment]
The type of audio file is also unaffected: mp3, flac, wav does not matter.

**Comment by AznamirWoW** [comment]
Did you change the pitch value when you got this error?

**Comment by IvanFromGardarike** [comment]
> Did you change the pitch value when you got this error?

Yes

**Comment by IvanFromGardarike** [comment]
no Formant Shifting used

**Comment by IvanFromGardarike** [comment]
i can write my settings

**Comment by IvanFromGardarike** [comment]
![image](https://github.com/user-attachments/assets/71b9baf2-c447-4352-8d2e-e6b1ed024421)
![image](https://github.com/user-attachments/assets/ea99da89-eacc-4f5d-9cf7-e25d32cabb61)

**Comment by AznamirWoW** [comment]
use RMVPE, dont use FCPE

**Comment by IvanFromGardarike** [comment]
> use RMVPE, dont use FCPE

what about the Hybrid?

**Comment by blaisewf** [comment]
if fcpe is not working well, and hybrid uses fcpe, the answer is there...

**Comment by IvanFromGardarike** [comment]
Oh. I see. 

Thanks for your help.

**Comment by AznamirWoW** [comment]
I've updated the code to fix your issue. It was caused by the first chunk having no voiced sections and triggering some weird condition in FCPE.
