### ISSUE TITLE
[Bug]: when uploading the index it sends an error

### ISSUE THREAD

**Issue by agyttv** [IAHispano/Applio#926]
### Project Version

2024.10.0

### Platform and OS Version

windows 10

### Affected Devices

pc

### What happened?

when uploading the index it sends an error

### Steps to reproduce

1. up index 
2. 
3. 
...

### Expected behavior

that index is uploaded properly

### Screenshots or Videos

[recording.webm](https://github.com/user-attachments/assets/f2e1b6e2-d90b-43a9-8170-f745a689a0e6)

**Comment by MalcolmReed-ent** [comment]
Is there any logs you can provide from the powershell or from the cmd, its difficult to pinpoint the problem

**Comment by Vidalnt** [comment]
rename the index to example.index
