### ISSUE TITLE
[Feature]: Replacement for downloading models?

### ISSUE THREAD

**Issue by Xeddius** [IAHispano/Applio#927]
### Description

Latest patch removed supabase for downloading models.

### Problem

It's difficult to find good voice models without a decent scraper.

### Proposed Solution

Find an alternative site/source for scraping models and save to a simple database file hosted publicly?

### Alternatives Considered

Suffer without it, I guess?

**Comment by blaisewf** [comment]
https://discord.com/channels/1096877223765606521/1286901735377604680/1315774636381831189
